package main

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"weave-os/router/internal/policyregistry"
	"weave-os/router/internal/providers"
	"weave-os/router/internal/router"
	"weave-os/router/internal/router/hmm/rosterdata"
	"weave-os/router/internal/router/policy"
)

// Exercise the production composition builder, v4 HTTP contract, Go selector
// and both admission paths. Expected picks are authored, not generated by one
// path and accepted unconditionally as the other path's oracle.
func TestLocalPinnedManagedDecisionParity(t *testing.T) {
	const primary = "openai/gpt-5.6-sol"
	const alternative = "anthropic/claude-fable-5.1"
	const primaryModel = "gpt-5.6-sol"
	const alternativeModel = "claude-fable-5-1"
	digest := strings.Repeat("a", 64)
	classes := []string{"high"}
	var failClassifier atomic.Bool
	queries := make(chan map[string]any, 32)
	classifier := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, request *http.Request) {
		switch request.URL.Path {
		case "/readyz":
			_ = json.NewEncoder(w).Encode(map[string]any{
				"schema_version": policy.SchemaVersionV4, "classifier_artifact_id": "synthetic_classifier",
				"classifier_artifact_sha256": digest, "classifier_image_digest": "sha256:" + digest,
				"classifier_class_order": classes, "classifier_taxonomy_sha256": policyregistry.TaxonomyDigest(classes),
			})
		case "/capabilities":
			_ = json.NewEncoder(w).Encode(policy.Capabilities{SchemaVersion: policy.SchemaVersionV4})
		case "/route":
			if failClassifier.Load() {
				http.Error(w, "synthetic unavailable", http.StatusServiceUnavailable)
				return
			}
			var query map[string]any
			if err := json.NewDecoder(request.Body).Decode(&query); err != nil {
				http.Error(w, "invalid request", http.StatusBadRequest)
				return
			}
			_ = json.NewEncoder(w).Encode(map[string]any{
				"schema_version": policy.SchemaVersionV4, "route_id": query["route_id"],
				"classifier_artifact_id": "synthetic_classifier", "classifier_artifact_sha256": digest,
				"predicted_label": "high", "class_order": classes,
				"class_probabilities":   map[string]float64{"high": 1},
				"classifier_confidence": 1, "classifier_margin": 1,
				"hmm_state_id": 0, "hmm_state_path": []int{0}, "hmm_state_probabilities": []float64{1},
			})
			delete(query, "route_id")
			queries <- query
		default:
			http.NotFound(w, request)
		}
	}))
	defer classifier.Close()
	candidate := policyregistry.Candidate{
		Policy: &rosterdata.Roster{
			SchemaVersion: rosterdata.SchemaVersionPolicyV1, ClassOrder: classes,
			Preferences: rosterdata.PreferencePolicy{PreferredModelBonus: 0.5, SubscriptionBonus: 0.35},
			Clusters: map[string]rosterdata.Cluster{"high": {
				Arms: []string{primary, alternative}, ArmScores: map[string]float64{primary: 30, alternative: 29.8},
			}},
		},
	}
	candidate.HeadSnapshot.Head.ClassifierRevisionURL = classifier.URL
	candidate.Release.Classifier.ArtifactID = "synthetic_classifier"
	candidate.Release.Classifier.PackageSHA256 = digest
	candidate.Release.Classifier.ImageDigest = "sha256:" + digest
	candidate.Release.Classifier.WireSchema = policy.SchemaVersionV4
	candidate.Release.Classifier.ClassOrder = classes
	candidate.Release.Classifier.TaxonomySHA256 = policyregistry.TaxonomyDigest(classes)
	candidate.Release.Policy.SHA256 = digest
	buildRouters := hmmPolicySnapshotBuilder(map[string]struct{}{providers.ProviderOpenAI: {}, providers.ProviderAnthropic: {}}, []router.Strategy{router.StrategyHMMEmbedding}, policySidecarAuthNone, time.Second, 400*time.Millisecond)
	localRouters, err := buildRouters(context.Background(), candidate)
	require.NoError(t, err)
	managedRouters, err := buildRouters(context.Background(), candidate)
	require.NoError(t, err)
	localSnapshot := &policyregistry.Snapshot{Candidate: candidate, Routers: localRouters}
	managedSnapshot := &policyregistry.Snapshot{Candidate: candidate, Routers: managedRouters}
	local := policyregistry.NewLocalPinnedRouter(router.StrategyHMMEmbedding, localSnapshot)
	managed := policyregistry.NewAdmittedRouter(router.StrategyHMMEmbedding, managedSnapshot)
	servingContext := policyregistry.WithServingSnapshot(context.Background(), managedSnapshot)
	for _, clientApp := range []string{"claude-code", "codex"} {
		for _, scenario := range []struct {
			name    string
			request router.Request
			want    string
		}{
			{"default", router.Request{}, primaryModel},
			{"eligibility", router.Request{ExcludedModels: map[string]struct{}{primaryModel: {}}}, alternativeModel},
			{"preference", router.Request{PreferredModels: []string{alternativeModel}}, alternativeModel},
			{"subscription", router.Request{SubscriptionStatePreferredModels: []string{alternativeModel}}, alternativeModel},
			{"continued-session", router.Request{PolicyTurnContext: &router.PolicyTurnContext{SessionTurnCount: 3, PreviousServedModel: alternativeModel}}, primaryModel},
		} {
			t.Run(clientApp+"/"+scenario.name, func(t *testing.T) {
				req := scenario.request
				req.ClientApp = clientApp
				req.PromptText = "Synthetic routing parity request"
				localDecision, err := local.Route(context.Background(), req)
				require.NoError(t, err)
				managedDecision, err := managed.Route(servingContext, req)
				require.NoError(t, err)
				require.Equal(t, scenario.want, localDecision.Model)
				require.Equal(t, scenario.want, managedDecision.Model)
				require.Equal(t, managedDecision.Provider, localDecision.Provider)
				require.Equal(t, managedDecision.Metadata.CandidateScores, localDecision.Metadata.CandidateScores)
				require.Equal(t, digest, localDecision.Metadata.SelectionPolicySHA256)
				localQuery, managedQuery := <-queries, <-queries
				require.Equal(t, managedQuery, localQuery, "classification inputs must be identical apart from request identity")
				if req.PolicyTurnContext != nil {
					require.Equal(t, float64(3), localQuery["session_turn_count"])
				}
			})
		}
	}
	_, err = managed.Route(context.Background(), router.Request{})
	require.ErrorIs(t, err, policyregistry.ErrNoActivePolicy)
	candidate.Release.Classifier.PackageSHA256 = strings.Repeat("b", 64)
	_, err = buildRouters(context.Background(), candidate)
	require.ErrorContains(t, err, "classifier package digest")
	failClassifier.Store(true)
	_, err = local.Route(context.Background(), router.Request{PromptText: "Synthetic failure"})
	require.Error(t, err, "local HMM failure must not fall back to another strategy")
	_, err = managed.Route(servingContext, router.Request{PromptText: "Synthetic failure"})
	require.Error(t, err)
}
