// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classifier_sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getClassifierPrediction = `-- name: GetClassifierPrediction :one
SELECT thread_id, turn_digest, root_turn_digest, user_message_count, tool_call_count, tool_error_count, completed_response_count, complexity, probabilities, created_at, input_message_count FROM router.classifier_predictions
WHERE thread_id = $1::uuid AND turn_digest = $2::text
`

type GetClassifierPredictionParams struct {
	ThreadID   uuid.UUID
	TurnDigest string
}

// A prediction lookup is always under an authenticated thread lock.
//
//	SELECT thread_id, turn_digest, root_turn_digest, user_message_count, tool_call_count, tool_error_count, completed_response_count, complexity, probabilities, created_at, input_message_count FROM router.classifier_predictions
//	WHERE thread_id = $1::uuid AND turn_digest = $2::text
func (q *Queries) GetClassifierPrediction(ctx context.Context, arg GetClassifierPredictionParams) (RouterClassifierPrediction, error) {
	row := q.db.QueryRow(ctx, getClassifierPrediction, arg.ThreadID, arg.TurnDigest)
	var i RouterClassifierPrediction
	err := row.Scan(
		&i.ThreadID,
		&i.TurnDigest,
		&i.RootTurnDigest,
		&i.UserMessageCount,
		&i.ToolCallCount,
		&i.ToolErrorCount,
		&i.CompletedResponseCount,
		&i.Complexity,
		&i.Probabilities,
		&i.CreatedAt,
		&i.InputMessageCount,
	)
	return i, err
}

const getClassifierPredictionBeforeMessage = `-- name: GetClassifierPredictionBeforeMessage :one
SELECT thread_id, turn_digest, root_turn_digest, user_message_count, tool_call_count, tool_error_count, completed_response_count, complexity, probabilities, created_at, input_message_count FROM router.classifier_predictions
WHERE thread_id = $1::uuid
  AND input_message_count > 0 AND input_message_count <= $2::integer
ORDER BY input_message_count DESC LIMIT 1
`

type GetClassifierPredictionBeforeMessageParams struct {
	ThreadID     uuid.UUID
	MessageIndex int32
}

// Output items belong to the latest admitted call before their input position,
// not necessarily to a separate invocation per assistant message/text block.
//
//	SELECT thread_id, turn_digest, root_turn_digest, user_message_count, tool_call_count, tool_error_count, completed_response_count, complexity, probabilities, created_at, input_message_count FROM router.classifier_predictions
//	WHERE thread_id = $1::uuid
//	  AND input_message_count > 0 AND input_message_count <= $2::integer
//	ORDER BY input_message_count DESC LIMIT 1
func (q *Queries) GetClassifierPredictionBeforeMessage(ctx context.Context, arg GetClassifierPredictionBeforeMessageParams) (RouterClassifierPrediction, error) {
	row := q.db.QueryRow(ctx, getClassifierPredictionBeforeMessage, arg.ThreadID, arg.MessageIndex)
	var i RouterClassifierPrediction
	err := row.Scan(
		&i.ThreadID,
		&i.TurnDigest,
		&i.RootTurnDigest,
		&i.UserMessageCount,
		&i.ToolCallCount,
		&i.ToolErrorCount,
		&i.CompletedResponseCount,
		&i.Complexity,
		&i.Probabilities,
		&i.CreatedAt,
		&i.InputMessageCount,
	)
	return i, err
}

const getClassifierThreadForUpdate = `-- name: GetClassifierThreadForUpdate :one
SELECT thread_id, installation_id, credential_sha256, request_id, release, release_sha256, selection_policy_sha256, expires_at, created_at, prefix_message_count, prefix_digest FROM router.classifier_threads
WHERE thread_id = $1::uuid
  AND installation_id = $2::uuid
  AND credential_sha256 = $3::bytea
  AND release = $4::text
  AND release_sha256 = $5::text
  AND selection_policy_sha256 = $6::text
  AND expires_at > CURRENT_TIMESTAMP
FOR UPDATE
`

type GetClassifierThreadForUpdateParams struct {
	ThreadID              uuid.UUID
	InstallationID        uuid.UUID
	CredentialSha256      []byte
	Release               string
	ReleaseSha256         string
	SelectionPolicySha256 string
}

// The lock covers inference and prediction commit, preventing competing replicas
// from producing different historical predictions for one thread.
//
//	SELECT thread_id, installation_id, credential_sha256, request_id, release, release_sha256, selection_policy_sha256, expires_at, created_at, prefix_message_count, prefix_digest FROM router.classifier_threads
//	WHERE thread_id = $1::uuid
//	  AND installation_id = $2::uuid
//	  AND credential_sha256 = $3::bytea
//	  AND release = $4::text
//	  AND release_sha256 = $5::text
//	  AND selection_policy_sha256 = $6::text
//	  AND expires_at > CURRENT_TIMESTAMP
//	FOR UPDATE
func (q *Queries) GetClassifierThreadForUpdate(ctx context.Context, arg GetClassifierThreadForUpdateParams) (RouterClassifierThread, error) {
	row := q.db.QueryRow(ctx, getClassifierThreadForUpdate,
		arg.ThreadID,
		arg.InstallationID,
		arg.CredentialSha256,
		arg.Release,
		arg.ReleaseSha256,
		arg.SelectionPolicySha256,
	)
	var i RouterClassifierThread
	err := row.Scan(
		&i.ThreadID,
		&i.InstallationID,
		&i.CredentialSha256,
		&i.RequestID,
		&i.Release,
		&i.ReleaseSha256,
		&i.SelectionPolicySha256,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.PrefixMessageCount,
		&i.PrefixDigest,
	)
	return i, err
}

const getClassifierThreadRoot = `-- name: GetClassifierThreadRoot :one
SELECT turn_digest FROM router.classifier_predictions
WHERE thread_id = $1::uuid AND turn_digest = root_turn_digest
`

// Root identity survives compaction and rules out re-enrollment of an old thread.
//
//	SELECT turn_digest FROM router.classifier_predictions
//	WHERE thread_id = $1::uuid AND turn_digest = root_turn_digest
func (q *Queries) GetClassifierThreadRoot(ctx context.Context, threadID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getClassifierThreadRoot, threadID)
	var turn_digest string
	err := row.Scan(&turn_digest)
	return turn_digest, err
}

const insertClassifierPrediction = `-- name: InsertClassifierPrediction :exec
INSERT INTO router.classifier_predictions (
    thread_id, turn_digest, root_turn_digest, user_message_count, tool_call_count,
    tool_error_count, completed_response_count, complexity, probabilities, input_message_count
) VALUES (
    $1::uuid, $2::text, $3::text,
    $4::integer, $5::integer, $6::integer,
    $7::integer, $8::smallint, $9::double precision[], $10::integer
)
`

type InsertClassifierPredictionParams struct {
	ThreadID               uuid.UUID
	TurnDigest             string
	RootTurnDigest         string
	UserMessageCount       int32
	ToolCallCount          int32
	ToolErrorCount         int32
	CompletedResponseCount int32
	Complexity             int16
	Probabilities          []float64
	InputMessageCount      int32
}

// Unique ordinal and digest constraints reject divergent histories; no overwrite.
//
//	INSERT INTO router.classifier_predictions (
//	    thread_id, turn_digest, root_turn_digest, user_message_count, tool_call_count,
//	    tool_error_count, completed_response_count, complexity, probabilities, input_message_count
//	) VALUES (
//	    $1::uuid, $2::text, $3::text,
//	    $4::integer, $5::integer, $6::integer,
//	    $7::integer, $8::smallint, $9::double precision[], $10::integer
//	)
func (q *Queries) InsertClassifierPrediction(ctx context.Context, arg InsertClassifierPredictionParams) error {
	_, err := q.db.Exec(ctx, insertClassifierPrediction,
		arg.ThreadID,
		arg.TurnDigest,
		arg.RootTurnDigest,
		arg.UserMessageCount,
		arg.ToolCallCount,
		arg.ToolErrorCount,
		arg.CompletedResponseCount,
		arg.Complexity,
		arg.Probabilities,
		arg.InputMessageCount,
	)
	return err
}

const insertClassifierThread = `-- name: InsertClassifierThread :one
INSERT INTO router.classifier_threads (
    thread_id, installation_id, credential_sha256, request_id, release, release_sha256, selection_policy_sha256, expires_at
) VALUES (
    $1::uuid, $2::uuid, $3::bytea,
    $4::uuid, $5::text, $6::text, $7::text, $8::timestamptz
)
ON CONFLICT (installation_id, credential_sha256, request_id)
DO UPDATE SET request_id = EXCLUDED.request_id
RETURNING thread_id, installation_id, credential_sha256, request_id, release, release_sha256, selection_policy_sha256, expires_at, created_at, prefix_message_count, prefix_digest
`

type InsertClassifierThreadParams struct {
	ThreadID              uuid.UUID
	InstallationID        uuid.UUID
	CredentialSha256      []byte
	RequestID             uuid.UUID
	Release               string
	ReleaseSha256         string
	SelectionPolicySha256 string
	ExpiresAt             pgtype.Timestamptz
}

// Handshake retries return the original thread, including its original release
// and expiry. A release change cannot rebind an existing idempotency key.
//
//	INSERT INTO router.classifier_threads (
//	    thread_id, installation_id, credential_sha256, request_id, release, release_sha256, selection_policy_sha256, expires_at
//	) VALUES (
//	    $1::uuid, $2::uuid, $3::bytea,
//	    $4::uuid, $5::text, $6::text, $7::text, $8::timestamptz
//	)
//	ON CONFLICT (installation_id, credential_sha256, request_id)
//	DO UPDATE SET request_id = EXCLUDED.request_id
//	RETURNING thread_id, installation_id, credential_sha256, request_id, release, release_sha256, selection_policy_sha256, expires_at, created_at, prefix_message_count, prefix_digest
func (q *Queries) InsertClassifierThread(ctx context.Context, arg InsertClassifierThreadParams) (RouterClassifierThread, error) {
	row := q.db.QueryRow(ctx, insertClassifierThread,
		arg.ThreadID,
		arg.InstallationID,
		arg.CredentialSha256,
		arg.RequestID,
		arg.Release,
		arg.ReleaseSha256,
		arg.SelectionPolicySha256,
		arg.ExpiresAt,
	)
	var i RouterClassifierThread
	err := row.Scan(
		&i.ThreadID,
		&i.InstallationID,
		&i.CredentialSha256,
		&i.RequestID,
		&i.Release,
		&i.ReleaseSha256,
		&i.SelectionPolicySha256,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.PrefixMessageCount,
		&i.PrefixDigest,
	)
	return i, err
}

const updateClassifierThreadPrefix = `-- name: UpdateClassifierThreadPrefix :exec
UPDATE router.classifier_threads
SET prefix_message_count = $1::integer, prefix_digest = $2::text
WHERE thread_id = $3::uuid
`

type UpdateClassifierThreadPrefixParams struct {
	PrefixMessageCount int32
	PrefixDigest       string
	ThreadID           uuid.UUID
}

// The authenticated thread lock serializes append-only request checkpoints.
//
//	UPDATE router.classifier_threads
//	SET prefix_message_count = $1::integer, prefix_digest = $2::text
//	WHERE thread_id = $3::uuid
func (q *Queries) UpdateClassifierThreadPrefix(ctx context.Context, arg UpdateClassifierThreadPrefixParams) error {
	_, err := q.db.Exec(ctx, updateClassifierThreadPrefix, arg.PrefixMessageCount, arg.PrefixDigest, arg.ThreadID)
	return err
}
