// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compaction_checkpoints.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredCompactionCheckpoints = `-- name: DeleteExpiredCompactionCheckpoints :exec
DELETE FROM router.compaction_checkpoints WHERE expires_at <= NOW()
`

// DeleteExpiredCompactionCheckpoints removes summaries after their reuse window.
//
//	DELETE FROM router.compaction_checkpoints WHERE expires_at <= NOW()
func (q *Queries) DeleteExpiredCompactionCheckpoints(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredCompactionCheckpoints)
	return err
}

const getCompactionCheckpoint = `-- name: GetCompactionCheckpoint :one
SELECT credential_identity, session_key, endpoint, prefix_digest, policy_digest,
  boundary, summary_ciphertext, summary_model, expires_at
FROM router.compaction_checkpoints
WHERE credential_identity = $1::varchar
  AND session_key = $2::bytea
  AND endpoint = $3::varchar
  AND expires_at > NOW()
`

type GetCompactionCheckpointParams struct {
	CredentialIdentity string
	SessionKey         []byte
	Endpoint           string
}

// GetCompactionCheckpoint returns an unexpired checkpoint for a single credential, session, and endpoint.
//
//	SELECT credential_identity, session_key, endpoint, prefix_digest, policy_digest,
//	  boundary, summary_ciphertext, summary_model, expires_at
//	FROM router.compaction_checkpoints
//	WHERE credential_identity = $1::varchar
//	  AND session_key = $2::bytea
//	  AND endpoint = $3::varchar
//	  AND expires_at > NOW()
func (q *Queries) GetCompactionCheckpoint(ctx context.Context, arg GetCompactionCheckpointParams) (RouterCompactionCheckpoint, error) {
	row := q.db.QueryRow(ctx, getCompactionCheckpoint, arg.CredentialIdentity, arg.SessionKey, arg.Endpoint)
	var i RouterCompactionCheckpoint
	err := row.Scan(
		&i.CredentialIdentity,
		&i.SessionKey,
		&i.Endpoint,
		&i.PrefixDigest,
		&i.PolicyDigest,
		&i.Boundary,
		&i.SummaryCiphertext,
		&i.SummaryModel,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertCompactionCheckpoint = `-- name: UpsertCompactionCheckpoint :exec
INSERT INTO router.compaction_checkpoints (
  credential_identity, session_key, endpoint, prefix_digest, policy_digest,
  boundary, summary_ciphertext, summary_model, expires_at
) VALUES (
  $1::varchar, $2::bytea, $3::varchar,
  $4::bytea, $5::bytea, $6::int,
  $7::bytea, $8::varchar, $9::timestamptz
)
ON CONFLICT (credential_identity, session_key, endpoint) DO UPDATE SET
  prefix_digest = EXCLUDED.prefix_digest,
  policy_digest = EXCLUDED.policy_digest,
  boundary = EXCLUDED.boundary,
  summary_ciphertext = EXCLUDED.summary_ciphertext,
  summary_model = EXCLUDED.summary_model,
  expires_at = EXCLUDED.expires_at
`

type UpsertCompactionCheckpointParams struct {
	CredentialIdentity string
	SessionKey         []byte
	Endpoint           string
	PrefixDigest       []byte
	PolicyDigest       []byte
	Boundary           int32
	SummaryCiphertext  []byte
	SummaryModel       string
	ExpiresAt          pgtype.Timestamptz
}

// UpsertCompactionCheckpoint replaces a session's verified prefix and encrypted summary.
//
//	INSERT INTO router.compaction_checkpoints (
//	  credential_identity, session_key, endpoint, prefix_digest, policy_digest,
//	  boundary, summary_ciphertext, summary_model, expires_at
//	) VALUES (
//	  $1::varchar, $2::bytea, $3::varchar,
//	  $4::bytea, $5::bytea, $6::int,
//	  $7::bytea, $8::varchar, $9::timestamptz
//	)
//	ON CONFLICT (credential_identity, session_key, endpoint) DO UPDATE SET
//	  prefix_digest = EXCLUDED.prefix_digest,
//	  policy_digest = EXCLUDED.policy_digest,
//	  boundary = EXCLUDED.boundary,
//	  summary_ciphertext = EXCLUDED.summary_ciphertext,
//	  summary_model = EXCLUDED.summary_model,
//	  expires_at = EXCLUDED.expires_at
func (q *Queries) UpsertCompactionCheckpoint(ctx context.Context, arg UpsertCompactionCheckpointParams) error {
	_, err := q.db.Exec(ctx, upsertCompactionCheckpoint,
		arg.CredentialIdentity,
		arg.SessionKey,
		arg.Endpoint,
		arg.PrefixDigest,
		arg.PolicyDigest,
		arg.Boundary,
		arg.SummaryCiphertext,
		arg.SummaryModel,
		arg.ExpiresAt,
	)
	return err
}
