// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential_subject_identities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getCredentialSubjectForRequestEmail = `-- name: GetCredentialSubjectForRequestEmail :one
SELECT identity.subject_id
FROM router.credential_subject_identities identity
JOIN router.credential_subject_installations access
    ON access.subject_id = identity.subject_id
    AND access.installation_id = identity.installation_id
    AND access.access_enabled
JOIN router.credential_subjects subject
    ON subject.id = identity.subject_id
    AND subject.revoked_at IS NULL
WHERE identity.installation_id = $1::uuid
  AND identity.email = $2::varchar
  AND identity.revoked_at IS NULL
`

type GetCredentialSubjectForRequestEmailParams struct {
	InstallationID uuid.UUID
	Email          string
}

// Resolves the person behind a request's X-Weave-User-Email within the
// authenticated installation. A subject whose installation access was
// withdrawn or whose projection was revoked resolves to no rows, so the
// caller falls back to the key's own identity instead of the stale person.
//
//	SELECT identity.subject_id
//	FROM router.credential_subject_identities identity
//	JOIN router.credential_subject_installations access
//	    ON access.subject_id = identity.subject_id
//	    AND access.installation_id = identity.installation_id
//	    AND access.access_enabled
//	JOIN router.credential_subjects subject
//	    ON subject.id = identity.subject_id
//	    AND subject.revoked_at IS NULL
//	WHERE identity.installation_id = $1::uuid
//	  AND identity.email = $2::varchar
//	  AND identity.revoked_at IS NULL
func (q *Queries) GetCredentialSubjectForRequestEmail(ctx context.Context, arg GetCredentialSubjectForRequestEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCredentialSubjectForRequestEmail, arg.InstallationID, arg.Email)
	var subject_id uuid.UUID
	err := row.Scan(&subject_id)
	return subject_id, err
}
