// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential_subjects.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getServingInstallationsForProjection = `-- name: GetServingInstallationsForProjection :many
SELECT id FROM router.model_router_installations
WHERE id = ANY($1::uuid[]) AND external_id = $2::varchar AND deleted_at IS NULL
ORDER BY id FOR UPDATE
`

type GetServingInstallationsForProjectionParams struct {
	InstallationIds []uuid.UUID
	ExternalID      string
}

// Lock all affected installations in deterministic order before profile/access projection.
//
//	SELECT id FROM router.model_router_installations
//	WHERE id = ANY($1::uuid[]) AND external_id = $2::varchar AND deleted_at IS NULL
//	ORDER BY id FOR UPDATE
func (q *Queries) GetServingInstallationsForProjection(ctx context.Context, arg GetServingInstallationsForProjectionParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getServingInstallationsForProjection, arg.InstallationIds, arg.ExternalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCredentialSubject = `-- name: InsertCredentialSubject :one
INSERT INTO router.credential_subjects DEFAULT VALUES RETURNING id, projection_complete, internal_enrolled, enrollment_generation, created_at, revoked_at
`

// Setup creates a pending subject and installation access in the key-issuance transaction.
//
//	INSERT INTO router.credential_subjects DEFAULT VALUES RETURNING id, projection_complete, internal_enrolled, enrollment_generation, created_at, revoked_at
func (q *Queries) InsertCredentialSubject(ctx context.Context) (RouterCredentialSubject, error) {
	row := q.db.QueryRow(ctx, insertCredentialSubject)
	var i RouterCredentialSubject
	err := row.Scan(
		&i.ID,
		&i.ProjectionComplete,
		&i.InternalEnrolled,
		&i.EnrollmentGeneration,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertCredentialSubjectInstallation = `-- name: InsertCredentialSubjectInstallation :exec
INSERT INTO router.credential_subject_installations(subject_id, installation_id)
VALUES ($1::uuid, $2::uuid)
`

type InsertCredentialSubjectInstallationParams struct {
	SubjectID      uuid.UUID
	InstallationID uuid.UUID
}

// Access remains disabled until the authenticated control-plane mapping has succeeded.
//
//	INSERT INTO router.credential_subject_installations(subject_id, installation_id)
//	VALUES ($1::uuid, $2::uuid)
func (q *Queries) InsertCredentialSubjectInstallation(ctx context.Context, arg InsertCredentialSubjectInstallationParams) error {
	_, err := q.db.Exec(ctx, insertCredentialSubjectInstallation, arg.SubjectID, arg.InstallationID)
	return err
}

const insertPersonalRoutingKey = `-- name: InsertPersonalRoutingKey :one
INSERT INTO router.model_router_api_keys (
    installation_id, external_id, name, key_prefix, key_hash, key_suffix, scope, credential_subject_id
) VALUES (
    $1::uuid, $2::varchar, $3::varchar,
    $4::varchar, $5::varchar, $6::varchar, 'routing', $7::uuid
) RETURNING id, installation_id, external_id, name, key_prefix, key_hash, key_suffix, last_used_at, created_at, deleted_at, created_by, spend_cap_usd_micros, spent_usd_micros, scope, credential_subject_id
`

type InsertPersonalRoutingKeyParams struct {
	InstallationID uuid.UUID
	ExternalID     string
	Name           *string
	KeyPrefix      string
	KeyHash        string
	KeySuffix      string
	SubjectID      uuid.UUID
}

// Personal issuance never rebinds or rotates an installation-shared key.
//
//	INSERT INTO router.model_router_api_keys (
//	    installation_id, external_id, name, key_prefix, key_hash, key_suffix, scope, credential_subject_id
//	) VALUES (
//	    $1::uuid, $2::varchar, $3::varchar,
//	    $4::varchar, $5::varchar, $6::varchar, 'routing', $7::uuid
//	) RETURNING id, installation_id, external_id, name, key_prefix, key_hash, key_suffix, last_used_at, created_at, deleted_at, created_by, spend_cap_usd_micros, spent_usd_micros, scope, credential_subject_id
func (q *Queries) InsertPersonalRoutingKey(ctx context.Context, arg InsertPersonalRoutingKeyParams) (RouterModelRouterAPIKey, error) {
	row := q.db.QueryRow(ctx, insertPersonalRoutingKey,
		arg.InstallationID,
		arg.ExternalID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.KeySuffix,
		arg.SubjectID,
	)
	var i RouterModelRouterAPIKey
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.ExternalID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.KeySuffix,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.SpendCapUsdMicros,
		&i.SpentUsdMicros,
		&i.Scope,
		&i.CredentialSubjectID,
	)
	return i, err
}

const updateCredentialSubjectEnrollment = `-- name: UpdateCredentialSubjectEnrollment :execrows
UPDATE router.credential_subjects
SET internal_enrolled = $1::boolean, enrollment_generation = enrollment_generation + 1
WHERE id = $2::uuid AND projection_complete AND revoked_at IS NULL
  AND internal_enrolled IS DISTINCT FROM $1::boolean
`

type UpdateCredentialSubjectEnrollmentParams struct {
	Enrolled  bool
	SubjectID uuid.UUID
}

// Enrollment is effective only for fully projected, non-revoked personal subjects.
//
//	UPDATE router.credential_subjects
//	SET internal_enrolled = $1::boolean, enrollment_generation = enrollment_generation + 1
//	WHERE id = $2::uuid AND projection_complete AND revoked_at IS NULL
//	  AND internal_enrolled IS DISTINCT FROM $1::boolean
func (q *Queries) UpdateCredentialSubjectEnrollment(ctx context.Context, arg UpdateCredentialSubjectEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCredentialSubjectEnrollment, arg.Enrolled, arg.SubjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCredentialSubjectInstallationAccess = `-- name: UpdateCredentialSubjectInstallationAccess :execrows
UPDATE router.credential_subject_installations SET access_enabled = $1::boolean
WHERE subject_id = $2::uuid AND installation_id = $3::uuid
`

type UpdateCredentialSubjectInstallationAccessParams struct {
	AccessEnabled  bool
	SubjectID      uuid.UUID
	InstallationID uuid.UUID
}

// Installation access changes take the installation lock before updating this row.
//
//	UPDATE router.credential_subject_installations SET access_enabled = $1::boolean
//	WHERE subject_id = $2::uuid AND installation_id = $3::uuid
func (q *Queries) UpdateCredentialSubjectInstallationAccess(ctx context.Context, arg UpdateCredentialSubjectInstallationAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCredentialSubjectInstallationAccess, arg.AccessEnabled, arg.SubjectID, arg.InstallationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCredentialSubjectProjection = `-- name: UpdateCredentialSubjectProjection :execrows
UPDATE router.credential_subjects
SET projection_complete = true, enrollment_generation = enrollment_generation + 1
WHERE id = $1::uuid AND revoked_at IS NULL AND NOT projection_complete
`

// The backend calls completion only after persisting its authenticated account mapping.
//
//	UPDATE router.credential_subjects
//	SET projection_complete = true, enrollment_generation = enrollment_generation + 1
//	WHERE id = $1::uuid AND revoked_at IS NULL AND NOT projection_complete
func (q *Queries) UpdateCredentialSubjectProjection(ctx context.Context, subjectID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, updateCredentialSubjectProjection, subjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCredentialSubjectRevoked = `-- name: UpdateCredentialSubjectRevoked :execrows
UPDATE router.credential_subjects
SET revoked_at = clock_timestamp(), internal_enrolled = false, enrollment_generation = enrollment_generation + 1
WHERE id = $1::uuid AND revoked_at IS NULL
`

// Revocation withdraws internal eligibility and changes generation without rotating shared keys.
//
//	UPDATE router.credential_subjects
//	SET revoked_at = clock_timestamp(), internal_enrolled = false, enrollment_generation = enrollment_generation + 1
//	WHERE id = $1::uuid AND revoked_at IS NULL
func (q *Queries) UpdateCredentialSubjectRevoked(ctx context.Context, subjectID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, updateCredentialSubjectRevoked, subjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertServingProfileAssignment = `-- name: UpsertServingProfileAssignment :execrows
INSERT INTO router.installation_profile_assignments(installation_id, profile_key, assignment_generation)
VALUES ($1::uuid, $2::uuid, 1)
ON CONFLICT (installation_id) DO UPDATE SET
    profile_key = EXCLUDED.profile_key,
    assignment_generation = router.installation_profile_assignments.assignment_generation + 1,
    updated_at = clock_timestamp()
WHERE router.installation_profile_assignments.profile_key IS DISTINCT FROM EXCLUDED.profile_key
`

type UpsertServingProfileAssignmentParams struct {
	InstallationID uuid.UUID
	ProfileKey     pgtype.UUID
}

// Projection is transaction-wide for the organization's installation set; no mutable release pointer here.
//
//	INSERT INTO router.installation_profile_assignments(installation_id, profile_key, assignment_generation)
//	VALUES ($1::uuid, $2::uuid, 1)
//	ON CONFLICT (installation_id) DO UPDATE SET
//	    profile_key = EXCLUDED.profile_key,
//	    assignment_generation = router.installation_profile_assignments.assignment_generation + 1,
//	    updated_at = clock_timestamp()
//	WHERE router.installation_profile_assignments.profile_key IS DISTINCT FROM EXCLUDED.profile_key
func (q *Queries) UpsertServingProfileAssignment(ctx context.Context, arg UpsertServingProfileAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertServingProfileAssignment, arg.InstallationID, arg.ProfileKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
