// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: escalation_check_fixtures.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteEscalationCheckFixture = `-- name: DeleteEscalationCheckFixture :execrows
DELETE FROM router.model_router_installations
WHERE id = $1::uuid AND external_id = $2::varchar
`

type DeleteEscalationCheckFixtureParams struct {
	InstallationID uuid.UUID
	ExternalID     string
}

// The opt-in database check removes its installation and cascaded session records.
//
//	DELETE FROM router.model_router_installations
//	WHERE id = $1::uuid AND external_id = $2::varchar
func (q *Queries) DeleteEscalationCheckFixture(ctx context.Context, arg DeleteEscalationCheckFixtureParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEscalationCheckFixture, arg.InstallationID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEscalationCheckFixtureRemaining = `-- name: GetEscalationCheckFixtureRemaining :one
SELECT (
    (SELECT count(*) FROM router.model_router_installations WHERE id = $1::uuid)
    + (SELECT count(*) FROM router.escalation_sessions WHERE scope = $2::bytea)
    + (SELECT count(*) FROM router.escalation_checkpoints WHERE scope = $2::bytea)
    + (SELECT count(*) FROM router.escalation_continuations WHERE scope = $2::bytea)
    )::bigint AS remaining
`

type GetEscalationCheckFixtureRemainingParams struct {
	InstallationID uuid.UUID
	Scope          []byte
}

// The check verifies physical cleanup, including all session-dependent tables.
//
//	SELECT (
//	    (SELECT count(*) FROM router.model_router_installations WHERE id = $1::uuid)
//	    + (SELECT count(*) FROM router.escalation_sessions WHERE scope = $2::bytea)
//	    + (SELECT count(*) FROM router.escalation_checkpoints WHERE scope = $2::bytea)
//	    + (SELECT count(*) FROM router.escalation_continuations WHERE scope = $2::bytea)
//	    )::bigint AS remaining
func (q *Queries) GetEscalationCheckFixtureRemaining(ctx context.Context, arg GetEscalationCheckFixtureRemainingParams) (int64, error) {
	row := q.db.QueryRow(ctx, getEscalationCheckFixtureRemaining, arg.InstallationID, arg.Scope)
	var remaining int64
	err := row.Scan(&remaining)
	return remaining, err
}

const updateEscalationCheckFixtureExpired = `-- name: UpdateEscalationCheckFixtureExpired :execrows
UPDATE router.escalation_sessions s
SET expires_at = clock_timestamp() - interval '1 second'
FROM router.model_router_installations i
WHERE s.scope = $1::bytea AND s.installation_id = i.id
    AND i.id = $2::uuid AND i.external_id = $3::varchar
`

type UpdateEscalationCheckFixtureExpiredParams struct {
	Scope          []byte
	InstallationID uuid.UUID
	ExternalID     string
}

// The opt-in database check expires only its own installation's session.
//
//	UPDATE router.escalation_sessions s
//	SET expires_at = clock_timestamp() - interval '1 second'
//	FROM router.model_router_installations i
//	WHERE s.scope = $1::bytea AND s.installation_id = i.id
//	    AND i.id = $2::uuid AND i.external_id = $3::varchar
func (q *Queries) UpdateEscalationCheckFixtureExpired(ctx context.Context, arg UpdateEscalationCheckFixtureExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEscalationCheckFixtureExpired, arg.Scope, arg.InstallationID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
