// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: escalation_sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteExpiredEscalationSession = `-- name: DeleteExpiredEscalationSession :exec
DELETE FROM router.escalation_sessions
WHERE scope = $1::bytea AND expires_at <= clock_timestamp()
`

// Expiry starts a new lifetime and cascades its prior boundary records.
//
//	DELETE FROM router.escalation_sessions
//	WHERE scope = $1::bytea AND expires_at <= clock_timestamp()
func (q *Queries) DeleteExpiredEscalationSession(ctx context.Context, scope []byte) error {
	_, err := q.db.Exec(ctx, deleteExpiredEscalationSession, scope)
	return err
}

const deleteExpiredEscalationSessions = `-- name: DeleteExpiredEscalationSessions :exec
DELETE FROM router.escalation_sessions WHERE expires_at <= clock_timestamp()
`

// Expired feature state and checkpoint identities share one retention boundary.
//
//	DELETE FROM router.escalation_sessions WHERE expires_at <= clock_timestamp()
func (q *Queries) DeleteExpiredEscalationSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEscalationSessions)
	return err
}

const getEscalationCheckpoint = `-- name: GetEscalationCheckpoint :one
SELECT c.checkpoint FROM router.escalation_checkpoints c
JOIN router.escalation_sessions s ON s.scope = c.scope
WHERE c.scope = $1::bytea AND c.boundary = $2::bytea
    AND s.expires_at > clock_timestamp()
`

type GetEscalationCheckpointParams struct {
	Scope    []byte
	Boundary []byte
}

// A checkpoint belongs to the current unexpired session lifetime.
//
//	SELECT c.checkpoint FROM router.escalation_checkpoints c
//	JOIN router.escalation_sessions s ON s.scope = c.scope
//	WHERE c.scope = $1::bytea AND c.boundary = $2::bytea
//	    AND s.expires_at > clock_timestamp()
func (q *Queries) GetEscalationCheckpoint(ctx context.Context, arg GetEscalationCheckpointParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEscalationCheckpoint, arg.Scope, arg.Boundary)
	var checkpoint []byte
	err := row.Scan(&checkpoint)
	return checkpoint, err
}

const getEscalationContinuation = `-- name: GetEscalationContinuation :one
SELECT c.scope, c.history FROM router.escalation_continuations c
JOIN router.escalation_sessions s ON s.scope = c.scope
WHERE c.activation = $1::bytea AND c.response_digest = $2::bytea
    AND s.expires_at > clock_timestamp()
`

type GetEscalationContinuationParams struct {
	Activation     []byte
	ResponseDigest []byte
}

type GetEscalationContinuationRow struct {
	Scope   []byte
	History []byte
}

// Response references are isolated by activation and expire with their owning session.
//
//	SELECT c.scope, c.history FROM router.escalation_continuations c
//	JOIN router.escalation_sessions s ON s.scope = c.scope
//	WHERE c.activation = $1::bytea AND c.response_digest = $2::bytea
//	    AND s.expires_at > clock_timestamp()
func (q *Queries) GetEscalationContinuation(ctx context.Context, arg GetEscalationContinuationParams) (GetEscalationContinuationRow, error) {
	row := q.db.QueryRow(ctx, getEscalationContinuation, arg.Activation, arg.ResponseDigest)
	var i GetEscalationContinuationRow
	err := row.Scan(&i.Scope, &i.History)
	return i, err
}

const insertEscalationCheckpoint = `-- name: InsertEscalationCheckpoint :exec
INSERT INTO router.escalation_checkpoints (scope, boundary, checkpoint)
VALUES ($1::bytea, $2::bytea, $3::jsonb)
`

type InsertEscalationCheckpointParams struct {
	Scope      []byte
	Boundary   []byte
	Checkpoint []byte
}

// The boundary uniqueness constraint makes repeated intervention commits atomic failures.
//
//	INSERT INTO router.escalation_checkpoints (scope, boundary, checkpoint)
//	VALUES ($1::bytea, $2::bytea, $3::jsonb)
func (q *Queries) InsertEscalationCheckpoint(ctx context.Context, arg InsertEscalationCheckpointParams) error {
	_, err := q.db.Exec(ctx, insertEscalationCheckpoint, arg.Scope, arg.Boundary, arg.Checkpoint)
	return err
}

const insertEscalationContinuation = `-- name: InsertEscalationContinuation :exec
WITH completed_session AS (
    SELECT scope FROM router.escalation_sessions
    WHERE scope = $4::bytea AND ordinal = $5::bigint
        AND lease_token IS NULL AND expires_at > clock_timestamp()
    FOR UPDATE
)
INSERT INTO router.escalation_continuations (activation, response_digest, scope, history)
SELECT $1::bytea, $2::bytea, scope, $3::jsonb
FROM completed_session
ON CONFLICT (activation, response_digest) DO NOTHING
`

type InsertEscalationContinuationParams struct {
	Activation     []byte
	ResponseDigest []byte
	History        []byte
	Scope          []byte
	Ordinal        int64
}

// Lock the session while checking ordinal so a successor cannot race the response write.
//
//	WITH completed_session AS (
//	    SELECT scope FROM router.escalation_sessions
//	    WHERE scope = $4::bytea AND ordinal = $5::bigint
//	        AND lease_token IS NULL AND expires_at > clock_timestamp()
//	    FOR UPDATE
//	)
//	INSERT INTO router.escalation_continuations (activation, response_digest, scope, history)
//	SELECT $1::bytea, $2::bytea, scope, $3::jsonb
//	FROM completed_session
//	ON CONFLICT (activation, response_digest) DO NOTHING
func (q *Queries) InsertEscalationContinuation(ctx context.Context, arg InsertEscalationContinuationParams) error {
	_, err := q.db.Exec(ctx, insertEscalationContinuation,
		arg.Activation,
		arg.ResponseDigest,
		arg.History,
		arg.Scope,
		arg.Ordinal,
	)
	return err
}

const updateEscalationSessionCommit = `-- name: UpdateEscalationSessionCommit :execrows
UPDATE router.escalation_sessions SET
    ordinal = $1::bigint,
    session_state = $2::jsonb,
    lease_token = NULL,
    lease_until = NULL,
    expires_at = clock_timestamp() + interval '24 hours'
WHERE scope = $3::bytea AND lease_token = $4::uuid
    AND lease_until > clock_timestamp() AND expires_at > clock_timestamp()
    AND ordinal + 1 = $1::bigint
`

type UpdateEscalationSessionCommitParams struct {
	Ordinal      int64
	SessionState []byte
	Scope        []byte
	LeaseToken   uuid.UUID
}

// The nonce and deadline prevent a late inference from overwriting a successor.
//
//	UPDATE router.escalation_sessions SET
//	    ordinal = $1::bigint,
//	    session_state = $2::jsonb,
//	    lease_token = NULL,
//	    lease_until = NULL,
//	    expires_at = clock_timestamp() + interval '24 hours'
//	WHERE scope = $3::bytea AND lease_token = $4::uuid
//	    AND lease_until > clock_timestamp() AND expires_at > clock_timestamp()
//	    AND ordinal + 1 = $1::bigint
func (q *Queries) UpdateEscalationSessionCommit(ctx context.Context, arg UpdateEscalationSessionCommitParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEscalationSessionCommit,
		arg.Ordinal,
		arg.SessionState,
		arg.Scope,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEscalationSessionInvalidated = `-- name: UpdateEscalationSessionInvalidated :exec
UPDATE router.escalation_sessions SET
    session_state = session_state || '{"feature_state":null,"feature_turns":0,"previous_outcome":null}'::jsonb,
    lease_token = NULL,
    lease_until = NULL
WHERE scope = $1::bytea AND expires_at > clock_timestamp()
`

// A missed action revokes in-flight observations without undoing accepted class intent.
//
//	UPDATE router.escalation_sessions SET
//	    session_state = session_state || '{"feature_state":null,"feature_turns":0,"previous_outcome":null}'::jsonb,
//	    lease_token = NULL,
//	    lease_until = NULL
//	WHERE scope = $1::bytea AND expires_at > clock_timestamp()
func (q *Queries) UpdateEscalationSessionInvalidated(ctx context.Context, scope []byte) error {
	_, err := q.db.Exec(ctx, updateEscalationSessionInvalidated, scope)
	return err
}

const updateEscalationSessionOutcome = `-- name: UpdateEscalationSessionOutcome :exec
UPDATE router.escalation_sessions
SET session_state = jsonb_set(session_state, '{previous_outcome}', $1::jsonb)
WHERE scope = $2::bytea AND ordinal = $3::bigint
    AND lease_token IS NULL AND expires_at > clock_timestamp()
    AND session_state->'feature_state' IS NOT NULL
    AND session_state->'feature_state' <> 'null'::jsonb
`

type UpdateEscalationSessionOutcomeParams struct {
	PreviousOutcome []byte
	Scope           []byte
	Ordinal         int64
}

// A completed response never changes an observation already claimed by a successor.
//
//	UPDATE router.escalation_sessions
//	SET session_state = jsonb_set(session_state, '{previous_outcome}', $1::jsonb)
//	WHERE scope = $2::bytea AND ordinal = $3::bigint
//	    AND lease_token IS NULL AND expires_at > clock_timestamp()
//	    AND session_state->'feature_state' IS NOT NULL
//	    AND session_state->'feature_state' <> 'null'::jsonb
func (q *Queries) UpdateEscalationSessionOutcome(ctx context.Context, arg UpdateEscalationSessionOutcomeParams) error {
	_, err := q.db.Exec(ctx, updateEscalationSessionOutcome, arg.PreviousOutcome, arg.Scope, arg.Ordinal)
	return err
}

const updateEscalationSessionRelease = `-- name: UpdateEscalationSessionRelease :exec
UPDATE router.escalation_sessions SET lease_token = NULL, lease_until = NULL
WHERE scope = $1::bytea AND lease_token = $2::uuid
`

type UpdateEscalationSessionReleaseParams struct {
	Scope      []byte
	LeaseToken uuid.UUID
}

// Releasing an old nonce cannot cancel a later owner's lease.
//
//	UPDATE router.escalation_sessions SET lease_token = NULL, lease_until = NULL
//	WHERE scope = $1::bytea AND lease_token = $2::uuid
func (q *Queries) UpdateEscalationSessionRelease(ctx context.Context, arg UpdateEscalationSessionReleaseParams) error {
	_, err := q.db.Exec(ctx, updateEscalationSessionRelease, arg.Scope, arg.LeaseToken)
	return err
}

const upsertEscalationSessionClaim = `-- name: UpsertEscalationSessionClaim :one
INSERT INTO router.escalation_sessions (
    scope, installation_id, lease_token, lease_until, expires_at
) VALUES (
    $1::bytea, $2::uuid, $3::uuid,
    clock_timestamp() + interval '15 seconds', clock_timestamp() + interval '24 hours'
)
ON CONFLICT (scope) DO UPDATE SET
    lease_token = EXCLUDED.lease_token,
    lease_until = EXCLUDED.lease_until,
    expires_at = EXCLUDED.expires_at
WHERE router.escalation_sessions.installation_id = EXCLUDED.installation_id
    AND (router.escalation_sessions.lease_until IS NULL
         OR router.escalation_sessions.lease_until <= clock_timestamp())
RETURNING session_state
`

type UpsertEscalationSessionClaimParams struct {
	Scope          []byte
	InstallationID uuid.UUID
	LeaseToken     uuid.UUID
}

// Only an expired or released lease can be acquired; no lock spans inference.
//
//	INSERT INTO router.escalation_sessions (
//	    scope, installation_id, lease_token, lease_until, expires_at
//	) VALUES (
//	    $1::bytea, $2::uuid, $3::uuid,
//	    clock_timestamp() + interval '15 seconds', clock_timestamp() + interval '24 hours'
//	)
//	ON CONFLICT (scope) DO UPDATE SET
//	    lease_token = EXCLUDED.lease_token,
//	    lease_until = EXCLUDED.lease_until,
//	    expires_at = EXCLUDED.expires_at
//	WHERE router.escalation_sessions.installation_id = EXCLUDED.installation_id
//	    AND (router.escalation_sessions.lease_until IS NULL
//	         OR router.escalation_sessions.lease_until <= clock_timestamp())
//	RETURNING session_state
func (q *Queries) UpsertEscalationSessionClaim(ctx context.Context, arg UpsertEscalationSessionClaimParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, upsertEscalationSessionClaim, arg.Scope, arg.InstallationID, arg.LeaseToken)
	var session_state []byte
	err := row.Scan(&session_state)
	return session_state, err
}
