// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback_request_history.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getFeedbackHistoryByRequest = `-- name: GetFeedbackHistoryByRequest :one
SELECT installation_id, session_key, role, sequence, request_id, completed_at, served_model, served_provider, strategy, route_id, training_allowed FROM router.feedback_request_history
WHERE installation_id = $1::uuid AND request_id = $2::varchar
`

type GetFeedbackHistoryByRequestParams struct {
	InstallationID uuid.UUID
	RequestID      string
}

// A repeated completion must not allocate another history position.
//
//	SELECT installation_id, session_key, role, sequence, request_id, completed_at, served_model, served_provider, strategy, route_id, training_allowed FROM router.feedback_request_history
//	WHERE installation_id = $1::uuid AND request_id = $2::varchar
func (q *Queries) GetFeedbackHistoryByRequest(ctx context.Context, arg GetFeedbackHistoryByRequestParams) (RouterFeedbackRequestHistory, error) {
	row := q.db.QueryRow(ctx, getFeedbackHistoryByRequest, arg.InstallationID, arg.RequestID)
	var i RouterFeedbackRequestHistory
	err := row.Scan(
		&i.InstallationID,
		&i.SessionKey,
		&i.Role,
		&i.Sequence,
		&i.RequestID,
		&i.CompletedAt,
		&i.ServedModel,
		&i.ServedProvider,
		&i.Strategy,
		&i.RouteID,
		&i.TrainingAllowed,
	)
	return i, err
}

const getFeedbackHistoryBySequence = `-- name: GetFeedbackHistoryBySequence :one
SELECT installation_id, session_key, role, sequence, request_id, completed_at, served_model, served_provider, strategy, route_id, training_allowed FROM router.feedback_request_history
WHERE installation_id = $1::uuid AND session_key = $2::bytea
    AND role = $3::varchar AND sequence = $4::bigint
`

type GetFeedbackHistoryBySequenceParams struct {
	InstallationID uuid.UUID
	SessionKey     []byte
	Role           string
	Sequence       int64
}

// Read the exact selected position after acquiring the scope lock.
//
//	SELECT installation_id, session_key, role, sequence, request_id, completed_at, served_model, served_provider, strategy, route_id, training_allowed FROM router.feedback_request_history
//	WHERE installation_id = $1::uuid AND session_key = $2::bytea
//	    AND role = $3::varchar AND sequence = $4::bigint
func (q *Queries) GetFeedbackHistoryBySequence(ctx context.Context, arg GetFeedbackHistoryBySequenceParams) (RouterFeedbackRequestHistory, error) {
	row := q.db.QueryRow(ctx, getFeedbackHistoryBySequence,
		arg.InstallationID,
		arg.SessionKey,
		arg.Role,
		arg.Sequence,
	)
	var i RouterFeedbackRequestHistory
	err := row.Scan(
		&i.InstallationID,
		&i.SessionKey,
		&i.Role,
		&i.Sequence,
		&i.RequestID,
		&i.CompletedAt,
		&i.ServedModel,
		&i.ServedProvider,
		&i.Strategy,
		&i.RouteID,
		&i.TrainingAllowed,
	)
	return i, err
}

const getFeedbackHistoryScopeForUpdate = `-- name: GetFeedbackHistoryScopeForUpdate :one
SELECT last_sequence FROM router.feedback_history_scopes
WHERE installation_id = $1::uuid AND session_key = $2::bytea AND role = $3::varchar
FOR UPDATE
`

type GetFeedbackHistoryScopeForUpdateParams struct {
	InstallationID uuid.UUID
	SessionKey     []byte
	Role           string
}

// Serialize completions and feedback acceptance only within one logical scope.
//
//	SELECT last_sequence FROM router.feedback_history_scopes
//	WHERE installation_id = $1::uuid AND session_key = $2::bytea AND role = $3::varchar
//	FOR UPDATE
func (q *Queries) GetFeedbackHistoryScopeForUpdate(ctx context.Context, arg GetFeedbackHistoryScopeForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getFeedbackHistoryScopeForUpdate, arg.InstallationID, arg.SessionKey, arg.Role)
	var last_sequence int64
	err := row.Scan(&last_sequence)
	return last_sequence, err
}

const insertFeedbackHistoryScope = `-- name: InsertFeedbackHistoryScope :exec
INSERT INTO router.feedback_history_scopes (installation_id, session_key, role)
VALUES ($1::uuid, $2::bytea, $3::varchar)
ON CONFLICT DO NOTHING
`

type InsertFeedbackHistoryScopeParams struct {
	InstallationID uuid.UUID
	SessionKey     []byte
	Role           string
}

// Create the scope lock without resetting existing numbering.
//
//	INSERT INTO router.feedback_history_scopes (installation_id, session_key, role)
//	VALUES ($1::uuid, $2::bytea, $3::varchar)
//	ON CONFLICT DO NOTHING
func (q *Queries) InsertFeedbackHistoryScope(ctx context.Context, arg InsertFeedbackHistoryScopeParams) error {
	_, err := q.db.Exec(ctx, insertFeedbackHistoryScope, arg.InstallationID, arg.SessionKey, arg.Role)
	return err
}

const insertFeedbackRequestHistory = `-- name: InsertFeedbackRequestHistory :one
INSERT INTO router.feedback_request_history (
    installation_id, session_key, role, sequence, request_id, served_model, served_provider, strategy, route_id, training_allowed
) VALUES (
    $1::uuid, $2::bytea, $3::varchar, $4::bigint,
    $5::varchar, $6::varchar, $7::varchar,
    $8::varchar, $9::varchar, $10::boolean
)
ON CONFLICT (installation_id, request_id) DO NOTHING
RETURNING sequence
`

type InsertFeedbackRequestHistoryParams struct {
	InstallationID  uuid.UUID
	SessionKey      []byte
	Role            string
	Sequence        int64
	RequestID       string
	ServedModel     string
	ServedProvider  string
	Strategy        string
	RouteID         string
	TrainingAllowed bool
}

// Request uniqueness also fences duplicate completions arriving under another scope.
//
//	INSERT INTO router.feedback_request_history (
//	    installation_id, session_key, role, sequence, request_id, served_model, served_provider, strategy, route_id, training_allowed
//	) VALUES (
//	    $1::uuid, $2::bytea, $3::varchar, $4::bigint,
//	    $5::varchar, $6::varchar, $7::varchar,
//	    $8::varchar, $9::varchar, $10::boolean
//	)
//	ON CONFLICT (installation_id, request_id) DO NOTHING
//	RETURNING sequence
func (q *Queries) InsertFeedbackRequestHistory(ctx context.Context, arg InsertFeedbackRequestHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertFeedbackRequestHistory,
		arg.InstallationID,
		arg.SessionKey,
		arg.Role,
		arg.Sequence,
		arg.RequestID,
		arg.ServedModel,
		arg.ServedProvider,
		arg.Strategy,
		arg.RouteID,
		arg.TrainingAllowed,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const updateFeedbackHistorySequence = `-- name: UpdateFeedbackHistorySequence :exec
UPDATE router.feedback_history_scopes SET last_sequence = $1::bigint
WHERE installation_id = $2::uuid AND session_key = $3::bytea AND role = $4::varchar
`

type UpdateFeedbackHistorySequenceParams struct {
	Sequence       int64
	InstallationID uuid.UUID
	SessionKey     []byte
	Role           string
}

// Advance only after inserting history in the same scope-locked transaction.
//
//	UPDATE router.feedback_history_scopes SET last_sequence = $1::bigint
//	WHERE installation_id = $2::uuid AND session_key = $3::bytea AND role = $4::varchar
func (q *Queries) UpdateFeedbackHistorySequence(ctx context.Context, arg UpdateFeedbackHistorySequenceParams) error {
	_, err := q.db.Exec(ctx, updateFeedbackHistorySequence,
		arg.Sequence,
		arg.InstallationID,
		arg.SessionKey,
		arg.Role,
	)
	return err
}
