// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flag_definitions.sql

package sqlc

import (
	"context"
)

const deleteFlagDefinitionsNotIn = `-- name: DeleteFlagDefinitionsNotIn :exec
DELETE FROM router.flag_definitions
WHERE registry_version <= $1::integer
  AND key <> ALL($2::text[])
`

type DeleteFlagDefinitionsNotInParams struct {
	RegistryVersion int32
	Keys            []string
}

// Drops rows for flags no longer in the compiled-in registry. The registry
// version guard makes this safe during rolling deploys: an older revision may
// prune definitions at its own version, but cannot remove rows published by a
// newer revision whose registry may have grown.
//
//	DELETE FROM router.flag_definitions
//	WHERE registry_version <= $1::integer
//	  AND key <> ALL($2::text[])
func (q *Queries) DeleteFlagDefinitionsNotIn(ctx context.Context, arg DeleteFlagDefinitionsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteFlagDefinitionsNotIn, arg.RegistryVersion, arg.Keys)
	return err
}

const listFlagDefinitions = `-- name: ListFlagDefinitions :many
SELECT key, kind, env_var, deployment_default, org_overridable, description, registry_version, updated_at
FROM router.flag_definitions
ORDER BY key
`

// ListFlagDefinitions
//
//	SELECT key, kind, env_var, deployment_default, org_overridable, description, registry_version, updated_at
//	FROM router.flag_definitions
//	ORDER BY key
func (q *Queries) ListFlagDefinitions(ctx context.Context) ([]RouterFlagDefinition, error) {
	rows, err := q.db.Query(ctx, listFlagDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterFlagDefinition
	for rows.Next() {
		var i RouterFlagDefinition
		if err := rows.Scan(
			&i.Key,
			&i.Kind,
			&i.EnvVar,
			&i.DeploymentDefault,
			&i.OrgOverridable,
			&i.Description,
			&i.RegistryVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFlagDefinition = `-- name: UpsertFlagDefinition :exec
INSERT INTO router.flag_definitions (
    key,
    kind,
    env_var,
    deployment_default,
    org_overridable,
    description,
    registry_version,
    updated_at
)
VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::text,
    $5::boolean,
    $6::text,
    $7::integer,
    NOW()
)
ON CONFLICT (key) DO UPDATE
SET kind = EXCLUDED.kind,
    env_var = EXCLUDED.env_var,
    deployment_default = EXCLUDED.deployment_default,
    org_overridable = EXCLUDED.org_overridable,
    description = EXCLUDED.description,
    registry_version = EXCLUDED.registry_version,
    updated_at = NOW()
`

type UpsertFlagDefinitionParams struct {
	Key               string
	Kind              string
	EnvVar            string
	DeploymentDefault string
	OrgOverridable    bool
	Description       string
	RegistryVersion   int32
}

// Upserts one row of the published flag registry. Called once per flag at router
// boot. Idempotent by design: every replica boots with the same compiled-in
// registry and writes identical rows, so concurrent boots converge rather than
// conflict. During a deploy that changes an env default, last writer wins on
// deployment_default -- acceptable because the column is display-only and the
// routing path reads the live in-process value.
//
//	INSERT INTO router.flag_definitions (
//	    key,
//	    kind,
//	    env_var,
//	    deployment_default,
//	    org_overridable,
//	    description,
//	    registry_version,
//	    updated_at
//	)
//	VALUES (
//	    $1::text,
//	    $2::text,
//	    $3::text,
//	    $4::text,
//	    $5::boolean,
//	    $6::text,
//	    $7::integer,
//	    NOW()
//	)
//	ON CONFLICT (key) DO UPDATE
//	SET kind = EXCLUDED.kind,
//	    env_var = EXCLUDED.env_var,
//	    deployment_default = EXCLUDED.deployment_default,
//	    org_overridable = EXCLUDED.org_overridable,
//	    description = EXCLUDED.description,
//	    registry_version = EXCLUDED.registry_version,
//	    updated_at = NOW()
func (q *Queries) UpsertFlagDefinition(ctx context.Context, arg UpsertFlagDefinitionParams) error {
	_, err := q.db.Exec(ctx, upsertFlagDefinition,
		arg.Key,
		arg.Kind,
		arg.EnvVar,
		arg.DeploymentDefault,
		arg.OrgOverridable,
		arg.Description,
		arg.RegistryVersion,
	)
	return err
}
