// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: global_automatic_routing_exclusions.sql

package sqlc

import (
	"context"
)

const listGlobalAutomaticRoutingExclusions = `-- name: ListGlobalAutomaticRoutingExclusions :many
SELECT model, reason, created_at, created_by
FROM router.global_automatic_routing_exclusions
ORDER BY model
`

// Lists every model disabled for automatic routing across the deployment.
// Ordered so the request-path cache snapshot and the admin read agree.
//
//	SELECT model, reason, created_at, created_by
//	FROM router.global_automatic_routing_exclusions
//	ORDER BY model
func (q *Queries) ListGlobalAutomaticRoutingExclusions(ctx context.Context) ([]RouterGlobalAutomaticRoutingExclusion, error) {
	rows, err := q.db.Query(ctx, listGlobalAutomaticRoutingExclusions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterGlobalAutomaticRoutingExclusion
	for rows.Next() {
		var i RouterGlobalAutomaticRoutingExclusion
		if err := rows.Scan(
			&i.Model,
			&i.Reason,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
