// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: internal_test_plans.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getInternalTestBalance = `-- name: GetInternalTestBalance :one
SELECT balance_usd_micros FROM router.internal_test_budgets
WHERE subject_id = $1::uuid AND enabled
`

// Read only the isolated book; no customer balance or override lookup.
//
//	SELECT balance_usd_micros FROM router.internal_test_budgets
//	WHERE subject_id = $1::uuid AND enabled
func (q *Queries) GetInternalTestBalance(ctx context.Context, subjectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getInternalTestBalance, subjectID)
	var balance_usd_micros int64
	err := row.Scan(&balance_usd_micros)
	return balance_usd_micros, err
}

const getInternalTestIdentities = `-- name: GetInternalTestIdentities :many
SELECT b.subject_id, b.installation_id, b.label, b.balance_usd_micros, s.enrollment_generation
FROM router.internal_test_budgets b
JOIN router.credential_subjects s ON s.id = b.subject_id
JOIN router.credential_subject_installations a ON a.subject_id = b.subject_id AND a.installation_id = b.installation_id
JOIN router.model_router_installations i ON i.id = b.installation_id
WHERE b.enabled AND b.balance_usd_micros > 0 AND s.internal_enrolled AND s.projection_complete
  AND s.revoked_at IS NULL AND a.access_enabled AND i.deleted_at IS NULL
  AND EXISTS (SELECT 1 FROM router.model_router_api_keys k WHERE k.installation_id = b.installation_id
      AND k.credential_subject_id = b.subject_id AND k.scope = 'routing' AND k.deleted_at IS NULL)
ORDER BY b.label, b.subject_id
`

type GetInternalTestIdentitiesRow struct {
	SubjectID            uuid.UUID
	InstallationID       uuid.UUID
	Label                string
	BalanceUsdMicros     int64
	EnrollmentGeneration int64
}

// Eligible identities require their own enabled prepaid budget and an existing personal credential.
//
//	SELECT b.subject_id, b.installation_id, b.label, b.balance_usd_micros, s.enrollment_generation
//	FROM router.internal_test_budgets b
//	JOIN router.credential_subjects s ON s.id = b.subject_id
//	JOIN router.credential_subject_installations a ON a.subject_id = b.subject_id AND a.installation_id = b.installation_id
//	JOIN router.model_router_installations i ON i.id = b.installation_id
//	WHERE b.enabled AND b.balance_usd_micros > 0 AND s.internal_enrolled AND s.projection_complete
//	  AND s.revoked_at IS NULL AND a.access_enabled AND i.deleted_at IS NULL
//	  AND EXISTS (SELECT 1 FROM router.model_router_api_keys k WHERE k.installation_id = b.installation_id
//	      AND k.credential_subject_id = b.subject_id AND k.scope = 'routing' AND k.deleted_at IS NULL)
//	ORDER BY b.label, b.subject_id
func (q *Queries) GetInternalTestIdentities(ctx context.Context) ([]GetInternalTestIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, getInternalTestIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInternalTestIdentitiesRow
	for rows.Next() {
		var i GetInternalTestIdentitiesRow
		if err := rows.Scan(
			&i.SubjectID,
			&i.InstallationID,
			&i.Label,
			&i.BalanceUsdMicros,
			&i.EnrollmentGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInternalTestIdentity = `-- name: GetInternalTestIdentity :one
SELECT b.subject_id, b.installation_id, b.label, b.balance_usd_micros, s.enrollment_generation
FROM router.internal_test_budgets b
JOIN router.credential_subjects s ON s.id = b.subject_id
JOIN router.credential_subject_installations a ON a.subject_id = b.subject_id AND a.installation_id = b.installation_id
JOIN router.model_router_installations i ON i.id = b.installation_id
WHERE b.subject_id = $1::uuid AND b.enabled AND b.balance_usd_micros > 0
  AND s.internal_enrolled AND s.projection_complete AND s.revoked_at IS NULL AND a.access_enabled AND i.deleted_at IS NULL
  AND EXISTS (SELECT 1 FROM router.model_router_api_keys k WHERE k.installation_id = b.installation_id
      AND k.credential_subject_id = b.subject_id AND k.scope = 'routing' AND k.deleted_at IS NULL)
FOR SHARE OF b, s, a, i
`

type GetInternalTestIdentityRow struct {
	SubjectID            uuid.UUID
	InstallationID       uuid.UUID
	Label                string
	BalanceUsdMicros     int64
	EnrollmentGeneration int64
}

// Read authoritative eligibility without a stale enrollment or balance cache.
//
//	SELECT b.subject_id, b.installation_id, b.label, b.balance_usd_micros, s.enrollment_generation
//	FROM router.internal_test_budgets b
//	JOIN router.credential_subjects s ON s.id = b.subject_id
//	JOIN router.credential_subject_installations a ON a.subject_id = b.subject_id AND a.installation_id = b.installation_id
//	JOIN router.model_router_installations i ON i.id = b.installation_id
//	WHERE b.subject_id = $1::uuid AND b.enabled AND b.balance_usd_micros > 0
//	  AND s.internal_enrolled AND s.projection_complete AND s.revoked_at IS NULL AND a.access_enabled AND i.deleted_at IS NULL
//	  AND EXISTS (SELECT 1 FROM router.model_router_api_keys k WHERE k.installation_id = b.installation_id
//	      AND k.credential_subject_id = b.subject_id AND k.scope = 'routing' AND k.deleted_at IS NULL)
//	FOR SHARE OF b, s, a, i
func (q *Queries) GetInternalTestIdentity(ctx context.Context, subjectID uuid.UUID) (GetInternalTestIdentityRow, error) {
	row := q.db.QueryRow(ctx, getInternalTestIdentity, subjectID)
	var i GetInternalTestIdentityRow
	err := row.Scan(
		&i.SubjectID,
		&i.InstallationID,
		&i.Label,
		&i.BalanceUsdMicros,
		&i.EnrollmentGeneration,
	)
	return i, err
}

const insertInternalTestInferenceDebit = `-- name: InsertInternalTestInferenceDebit :one
WITH charged AS (
 UPDATE router.internal_test_budgets SET balance_usd_micros = balance_usd_micros + $1::bigint
 WHERE subject_id = $2::uuid AND $1::bigint <= 0
   AND balance_usd_micros + $1::bigint >= 0
   AND EXISTS (SELECT 1 FROM router.model_router_api_keys k WHERE k.id = $3::uuid
       AND k.credential_subject_id = router.internal_test_budgets.subject_id
       AND k.installation_id = router.internal_test_budgets.installation_id)
 RETURNING subject_id, balance_usd_micros
), ledger AS (
 INSERT INTO router.internal_test_credit_ledger(subject_id, delta_usd_micros, router_request_id, router_model, api_key_id)
 SELECT subject_id, $1::bigint, $4::varchar, $5::varchar, $3::uuid FROM charged
 RETURNING api_key_id
), metered AS (
 UPDATE router.model_router_api_keys SET spent_usd_micros = spent_usd_micros - $1::bigint
 WHERE id IN (SELECT api_key_id FROM ledger)
)
SELECT balance_usd_micros FROM charged
`

type InsertInternalTestInferenceDebitParams struct {
	DeltaUsdMicros  int64
	SubjectID       uuid.UUID
	APIKeyID        uuid.UUID
	RouterRequestID string
	RouterModel     string
}

// Record every served action and meter the authenticating key atomically.
//
//	WITH charged AS (
//	 UPDATE router.internal_test_budgets SET balance_usd_micros = balance_usd_micros + $1::bigint
//	 WHERE subject_id = $2::uuid AND $1::bigint <= 0
//	   AND balance_usd_micros + $1::bigint >= 0
//	   AND EXISTS (SELECT 1 FROM router.model_router_api_keys k WHERE k.id = $3::uuid
//	       AND k.credential_subject_id = router.internal_test_budgets.subject_id
//	       AND k.installation_id = router.internal_test_budgets.installation_id)
//	 RETURNING subject_id, balance_usd_micros
//	), ledger AS (
//	 INSERT INTO router.internal_test_credit_ledger(subject_id, delta_usd_micros, router_request_id, router_model, api_key_id)
//	 SELECT subject_id, $1::bigint, $4::varchar, $5::varchar, $3::uuid FROM charged
//	 RETURNING api_key_id
//	), metered AS (
//	 UPDATE router.model_router_api_keys SET spent_usd_micros = spent_usd_micros - $1::bigint
//	 WHERE id IN (SELECT api_key_id FROM ledger)
//	)
//	SELECT balance_usd_micros FROM charged
func (q *Queries) InsertInternalTestInferenceDebit(ctx context.Context, arg InsertInternalTestInferenceDebitParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertInternalTestInferenceDebit,
		arg.DeltaUsdMicros,
		arg.SubjectID,
		arg.APIKeyID,
		arg.RouterRequestID,
		arg.RouterModel,
	)
	var balance_usd_micros int64
	err := row.Scan(&balance_usd_micros)
	return balance_usd_micros, err
}

const insertInternalTestLaunch = `-- name: InsertInternalTestLaunch :exec
INSERT INTO router.internal_test_plan_launches(id, token_sha256, subject_id, installation_id, launch, created_at, expires_at)
VALUES ($1::uuid, $2::varchar, $3::uuid, $4::uuid, $5::jsonb, $6::timestamptz, $7::timestamptz)
`

type InsertInternalTestLaunchParams struct {
	ID             uuid.UUID
	TokenSha256    string
	SubjectID      uuid.UUID
	InstallationID uuid.UUID
	Launch         []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

// Persist only a digest of the bearer launch grant.
//
//	INSERT INTO router.internal_test_plan_launches(id, token_sha256, subject_id, installation_id, launch, created_at, expires_at)
//	VALUES ($1::uuid, $2::varchar, $3::uuid, $4::uuid, $5::jsonb, $6::timestamptz, $7::timestamptz)
func (q *Queries) InsertInternalTestLaunch(ctx context.Context, arg InsertInternalTestLaunchParams) error {
	_, err := q.db.Exec(ctx, insertInternalTestLaunch,
		arg.ID,
		arg.TokenSha256,
		arg.SubjectID,
		arg.InstallationID,
		arg.Launch,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const updateInternalTestLaunchRevoked = `-- name: UpdateInternalTestLaunchRevoked :execrows
UPDATE router.internal_test_plan_launches SET revoked_at = COALESCE(revoked_at, clock_timestamp())
WHERE id = $1::uuid
`

// Revocation changes only ephemeral internal grant state.
//
//	UPDATE router.internal_test_plan_launches SET revoked_at = COALESCE(revoked_at, clock_timestamp())
//	WHERE id = $1::uuid
func (q *Queries) UpdateInternalTestLaunchRevoked(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, updateInternalTestLaunchRevoked, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInternalTestLaunchSession = `-- name: UpdateInternalTestLaunchSession :one
UPDATE router.internal_test_plan_launches l SET session_id = $1::uuid
FROM router.model_router_api_keys k
WHERE l.token_sha256 = $2::varchar AND l.revoked_at IS NULL
  AND l.created_at <= clock_timestamp() AND clock_timestamp() < l.expires_at
  AND l.installation_id = $3::uuid AND k.id = $4::uuid
  AND k.installation_id = l.installation_id AND k.credential_subject_id = l.subject_id
  AND k.scope = 'routing' AND k.deleted_at IS NULL
  AND (l.session_id IS NULL OR l.session_id = $1::uuid)
RETURNING l.launch
`

type UpdateInternalTestLaunchSessionParams struct {
	SessionID      uuid.UUID
	TokenSha256    string
	InstallationID uuid.UUID
	APIKeyID       uuid.UUID
}

// A launch binds once to the CLI's fresh session and cannot be renewed.
//
//	UPDATE router.internal_test_plan_launches l SET session_id = $1::uuid
//	FROM router.model_router_api_keys k
//	WHERE l.token_sha256 = $2::varchar AND l.revoked_at IS NULL
//	  AND l.created_at <= clock_timestamp() AND clock_timestamp() < l.expires_at
//	  AND l.installation_id = $3::uuid AND k.id = $4::uuid
//	  AND k.installation_id = l.installation_id AND k.credential_subject_id = l.subject_id
//	  AND k.scope = 'routing' AND k.deleted_at IS NULL
//	  AND (l.session_id IS NULL OR l.session_id = $1::uuid)
//	RETURNING l.launch
func (q *Queries) UpdateInternalTestLaunchSession(ctx context.Context, arg UpdateInternalTestLaunchSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, updateInternalTestLaunchSession,
		arg.SessionID,
		arg.TokenSha256,
		arg.InstallationID,
		arg.APIKeyID,
	)
	var launch []byte
	err := row.Scan(&launch)
	return launch, err
}
