// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_escalation_config.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getEscalationSelection = `-- name: GetEscalationSelection :one
SELECT flag_overrides FROM router.model_router_installations
WHERE id = $1::uuid AND deleted_at IS NULL
`

// GetEscalationSelection
//
//	SELECT flag_overrides FROM router.model_router_installations
//	WHERE id = $1::uuid AND deleted_at IS NULL
func (q *Queries) GetEscalationSelection(ctx context.Context, installationID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEscalationSelection, installationID)
	var flag_overrides []byte
	err := row.Scan(&flag_overrides)
	return flag_overrides, err
}

const updateEscalationSelection = `-- name: UpdateEscalationSelection :one
UPDATE router.model_router_installations
SET flag_overrides = COALESCE(flag_overrides, '{}'::jsonb) || $1::jsonb,
    updated_at = NOW()
WHERE id = $2::uuid AND deleted_at IS NULL
  AND CASE WHEN flag_overrides ? 'escalation_active_classifier'
      THEN COALESCE((flag_overrides->>'escalation_epoch')::integer, 0)
      ELSE COALESCE((flag_overrides->>'escalation_xgb_epoch')::integer, 0) END = $3::integer
RETURNING flag_overrides
`

type UpdateEscalationSelectionParams struct {
	SelectionPatch []byte
	InstallationID uuid.UUID
	ExpectedEpoch  int32
}

// UpdateEscalationSelection
//
//	UPDATE router.model_router_installations
//	SET flag_overrides = COALESCE(flag_overrides, '{}'::jsonb) || $1::jsonb,
//	    updated_at = NOW()
//	WHERE id = $2::uuid AND deleted_at IS NULL
//	  AND CASE WHEN flag_overrides ? 'escalation_active_classifier'
//	      THEN COALESCE((flag_overrides->>'escalation_epoch')::integer, 0)
//	      ELSE COALESCE((flag_overrides->>'escalation_xgb_epoch')::integer, 0) END = $3::integer
//	RETURNING flag_overrides
func (q *Queries) UpdateEscalationSelection(ctx context.Context, arg UpdateEscalationSelectionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, updateEscalationSelection, arg.SelectionPatch, arg.InstallationID, arg.ExpectedEpoch)
	var flag_overrides []byte
	err := row.Scan(&flag_overrides)
	return flag_overrides, err
}
