// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_escalation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteExpiredLLMEscalationScope = `-- name: DeleteExpiredLLMEscalationScope :exec
DELETE FROM router.llm_escalation_sessions WHERE scope = $1::bytea AND expires_at <= clock_timestamp()
`

// A recreated scope gets a new lifetime, fencing old workers.
//
//	DELETE FROM router.llm_escalation_sessions WHERE scope = $1::bytea AND expires_at <= clock_timestamp()
func (q *Queries) DeleteExpiredLLMEscalationScope(ctx context.Context, scope []byte) error {
	_, err := q.db.Exec(ctx, deleteExpiredLLMEscalationScope, scope)
	return err
}

const deleteExpiredLLMEscalationSessions = `-- name: DeleteExpiredLLMEscalationSessions :exec
DELETE FROM router.llm_escalation_sessions WHERE expires_at<=clock_timestamp()
`

// Cascade operational metadata and continuation content together.
//
//	DELETE FROM router.llm_escalation_sessions WHERE expires_at<=clock_timestamp()
func (q *Queries) DeleteExpiredLLMEscalationSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredLLMEscalationSessions)
	return err
}

const expireLLMEscalationJobLeases = `-- name: ExpireLLMEscalationJobLeases :exec
UPDATE router.llm_escalation_jobs
SET status = 'failed',
    job = jsonb_set(
      jsonb_set(
        jsonb_set(job, '{status}', '"failed"'::jsonb),
        '{failure}', '"lease_expired"'::jsonb
      ),
      '{finished_at}', to_jsonb(clock_timestamp())
    )
WHERE status = 'running' AND lease_until <= clock_timestamp()
`

// Process loss leaves no durable transcript to retry; close expired claims as missed checks.
//
//	UPDATE router.llm_escalation_jobs
//	SET status = 'failed',
//	    job = jsonb_set(
//	      jsonb_set(
//	        jsonb_set(job, '{status}', '"failed"'::jsonb),
//	        '{failure}', '"lease_expired"'::jsonb
//	      ),
//	      '{finished_at}', to_jsonb(clock_timestamp())
//	    )
//	WHERE status = 'running' AND lease_until <= clock_timestamp()
func (q *Queries) ExpireLLMEscalationJobLeases(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireLLMEscalationJobLeases)
	return err
}

const getLLMEscalationCheckpointJob = `-- name: GetLLMEscalationCheckpointJob :one
SELECT job FROM router.llm_escalation_jobs
WHERE lifetime= $1::uuid AND generation= $2::bigint AND checkpoint= $3::bigint
`

type GetLLMEscalationCheckpointJobParams struct {
	Lifetime   uuid.UUID
	Generation int64
	Checkpoint int64
}

// Fetch the current generation's verdict while its session is locked.
//
//	SELECT job FROM router.llm_escalation_jobs
//	WHERE lifetime= $1::uuid AND generation= $2::bigint AND checkpoint= $3::bigint
func (q *Queries) GetLLMEscalationCheckpointJob(ctx context.Context, arg GetLLMEscalationCheckpointJobParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLLMEscalationCheckpointJob, arg.Lifetime, arg.Generation, arg.Checkpoint)
	var job []byte
	err := row.Scan(&job)
	return job, err
}

const getLLMEscalationContinuation = `-- name: GetLLMEscalationContinuation :one
SELECT s.scope,c.history FROM router.llm_escalation_continuations c
JOIN router.llm_escalation_sessions s ON s.lifetime=c.lifetime
WHERE c.activation= $1::bytea AND c.response_digest= $2::bytea AND s.expires_at>clock_timestamp()
`

type GetLLMEscalationContinuationParams struct {
	Activation     []byte
	ResponseDigest []byte
}

type GetLLMEscalationContinuationRow struct {
	Scope   []byte
	History []byte
}

// Continuations are isolated by activation and expire with the session.
//
//	SELECT s.scope,c.history FROM router.llm_escalation_continuations c
//	JOIN router.llm_escalation_sessions s ON s.lifetime=c.lifetime
//	WHERE c.activation= $1::bytea AND c.response_digest= $2::bytea AND s.expires_at>clock_timestamp()
func (q *Queries) GetLLMEscalationContinuation(ctx context.Context, arg GetLLMEscalationContinuationParams) (GetLLMEscalationContinuationRow, error) {
	row := q.db.QueryRow(ctx, getLLMEscalationContinuation, arg.Activation, arg.ResponseDigest)
	var i GetLLMEscalationContinuationRow
	err := row.Scan(&i.Scope, &i.History)
	return i, err
}

const getLLMEscalationJob = `-- name: GetLLMEscalationJob :one
SELECT j.job FROM router.llm_escalation_jobs j JOIN router.llm_escalation_sessions s ON s.lifetime=j.lifetime
WHERE s.installation_id= $1::uuid AND j.id= $2::uuid AND s.expires_at>clock_timestamp()
`

type GetLLMEscalationJobParams struct {
	InstallationID uuid.UUID
	ID             uuid.UUID
}

// A job id alone never grants cross-installation access.
//
//	SELECT j.job FROM router.llm_escalation_jobs j JOIN router.llm_escalation_sessions s ON s.lifetime=j.lifetime
//	WHERE s.installation_id= $1::uuid AND j.id= $2::uuid AND s.expires_at>clock_timestamp()
func (q *Queries) GetLLMEscalationJob(ctx context.Context, arg GetLLMEscalationJobParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLLMEscalationJob, arg.InstallationID, arg.ID)
	var job []byte
	err := row.Scan(&job)
	return job, err
}

const getLLMEscalationJobs = `-- name: GetLLMEscalationJobs :many
SELECT j.job FROM router.llm_escalation_jobs j JOIN router.llm_escalation_sessions s ON s.lifetime=j.lifetime
WHERE s.installation_id= $1::uuid AND s.expires_at>clock_timestamp()
ORDER BY s.updated_at DESC,j.checkpoint DESC LIMIT $2::int
`

type GetLLMEscalationJobsParams struct {
	InstallationID uuid.UUID
	PageLimit      int32
}

// Installation-scoped audit listing contains no captured transcript.
//
//	SELECT j.job FROM router.llm_escalation_jobs j JOIN router.llm_escalation_sessions s ON s.lifetime=j.lifetime
//	WHERE s.installation_id= $1::uuid AND s.expires_at>clock_timestamp()
//	ORDER BY s.updated_at DESC,j.checkpoint DESC LIMIT $2::int
func (q *Queries) GetLLMEscalationJobs(ctx context.Context, arg GetLLMEscalationJobsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getLLMEscalationJobs, arg.InstallationID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var job []byte
		if err := rows.Scan(&job); err != nil {
			return nil, err
		}
		items = append(items, job)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLLMEscalationLiveJob = `-- name: GetLLMEscalationLiveJob :one
SELECT id FROM router.llm_escalation_jobs WHERE lifetime= $1::uuid
AND status= $2::text AND lease_until>clock_timestamp() LIMIT 1
`

type GetLLMEscalationLiveJobParams struct {
	Lifetime uuid.UUID
	Status   string
}

// A running paid request remains in flight until its lease expires.
//
//	SELECT id FROM router.llm_escalation_jobs WHERE lifetime= $1::uuid
//	AND status= $2::text AND lease_until>clock_timestamp() LIMIT 1
func (q *Queries) GetLLMEscalationLiveJob(ctx context.Context, arg GetLLMEscalationLiveJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getLLMEscalationLiveJob, arg.Lifetime, arg.Status)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getLLMEscalationSessionDetail = `-- name: GetLLMEscalationSessionDetail :one
SELECT state FROM router.llm_escalation_sessions WHERE installation_id= $1::uuid AND scope= $2::bytea AND expires_at>clock_timestamp()
`

type GetLLMEscalationSessionDetailParams struct {
	InstallationID uuid.UUID
	Scope          []byte
}

// Session detail is scoped by installation and its public digest.
//
//	SELECT state FROM router.llm_escalation_sessions WHERE installation_id= $1::uuid AND scope= $2::bytea AND expires_at>clock_timestamp()
func (q *Queries) GetLLMEscalationSessionDetail(ctx context.Context, arg GetLLMEscalationSessionDetailParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLLMEscalationSessionDetail, arg.InstallationID, arg.Scope)
	var state []byte
	err := row.Scan(&state)
	return state, err
}

const getLLMEscalationSessionJobs = `-- name: GetLLMEscalationSessionJobs :many
SELECT job FROM router.llm_escalation_jobs WHERE lifetime= $1::uuid ORDER BY checkpoint DESC
`

// Detail checkpoints remain in source-turn order.
//
//	SELECT job FROM router.llm_escalation_jobs WHERE lifetime= $1::uuid ORDER BY checkpoint DESC
func (q *Queries) GetLLMEscalationSessionJobs(ctx context.Context, lifetime uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getLLMEscalationSessionJobs, lifetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var job []byte
		if err := rows.Scan(&job); err != nil {
			return nil, err
		}
		items = append(items, job)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLLMEscalationSessionLocked = `-- name: GetLLMEscalationSessionLocked :one
SELECT state FROM router.llm_escalation_sessions
WHERE scope= $1::bytea AND expires_at>clock_timestamp() FOR UPDATE
`

// Session bookkeeping is serialized only within short transactions.
//
//	SELECT state FROM router.llm_escalation_sessions
//	WHERE scope= $1::bytea AND expires_at>clock_timestamp() FOR UPDATE
func (q *Queries) GetLLMEscalationSessionLocked(ctx context.Context, scope []byte) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLLMEscalationSessionLocked, scope)
	var state []byte
	err := row.Scan(&state)
	return state, err
}

const getLLMEscalationSessions = `-- name: GetLLMEscalationSessions :many
SELECT state FROM router.llm_escalation_sessions
WHERE ($1::boolean OR installation_id= $2::uuid)
  AND expires_at>clock_timestamp()
ORDER BY updated_at DESC,lifetime DESC LIMIT $4::int OFFSET $3::int
`

type GetLLMEscalationSessionsParams struct {
	AllInstallations bool
	InstallationID   uuid.UUID
	PageOffset       int32
	PageLimit        int32
}

// Page sessions using a stable lifetime tie breaker.
//
//	SELECT state FROM router.llm_escalation_sessions
//	WHERE ($1::boolean OR installation_id= $2::uuid)
//	  AND expires_at>clock_timestamp()
//	ORDER BY updated_at DESC,lifetime DESC LIMIT $4::int OFFSET $3::int
func (q *Queries) GetLLMEscalationSessions(ctx context.Context, arg GetLLMEscalationSessionsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getLLMEscalationSessions,
		arg.AllInstallations,
		arg.InstallationID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var state []byte
		if err := rows.Scan(&state); err != nil {
			return nil, err
		}
		items = append(items, state)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLLMEscalationSummary = `-- name: GetLLMEscalationSummary :one
SELECT
  count(*) FILTER (WHERE j.job->'judgment'->>'escalate' = 'true')::bigint AS positive_judgments,
  count(*) FILTER (WHERE j.status = 'applied' AND s.state->'config'->>'mode' = 'active')::bigint AS actual_interventions,
  count(*) FILTER (WHERE j.status = 'applied' AND s.state->'config'->>'mode' = 'shadow')::bigint AS shadow_interventions,
  count(*) FILTER (WHERE j.status = 'stale')::bigint AS stale_results,
  count(*) FILTER (WHERE j.job->>'failure' = 'timeout')::bigint AS timeouts,
  count(*) FILTER (WHERE j.job->>'failure' = 'invalid_response')::bigint AS invalid_responses,
  count(*) FILTER (WHERE j.job->>'failure' = 'capacity')::bigint AS capacity_skips,
  count(*) FILTER (WHERE j.job->>'failure' = 'call_limit')::bigint AS attempt_limit_exhaustion
FROM router.llm_escalation_jobs j
JOIN router.llm_escalation_sessions s ON s.lifetime = j.lifetime
WHERE ($1::boolean OR s.installation_id = $2::uuid)
  AND s.expires_at > clock_timestamp()
`

type GetLLMEscalationSummaryParams struct {
	AllInstallations bool
	InstallationID   uuid.UUID
}

type GetLLMEscalationSummaryRow struct {
	PositiveJudgments      int64
	ActualInterventions    int64
	ShadowInterventions    int64
	StaleResults           int64
	Timeouts               int64
	InvalidResponses       int64
	CapacitySkips          int64
	AttemptLimitExhaustion int64
}

// Aggregate only bounded operational metadata; rationale and transcript are excluded.
//
//	SELECT
//	  count(*) FILTER (WHERE j.job->'judgment'->>'escalate' = 'true')::bigint AS positive_judgments,
//	  count(*) FILTER (WHERE j.status = 'applied' AND s.state->'config'->>'mode' = 'active')::bigint AS actual_interventions,
//	  count(*) FILTER (WHERE j.status = 'applied' AND s.state->'config'->>'mode' = 'shadow')::bigint AS shadow_interventions,
//	  count(*) FILTER (WHERE j.status = 'stale')::bigint AS stale_results,
//	  count(*) FILTER (WHERE j.job->>'failure' = 'timeout')::bigint AS timeouts,
//	  count(*) FILTER (WHERE j.job->>'failure' = 'invalid_response')::bigint AS invalid_responses,
//	  count(*) FILTER (WHERE j.job->>'failure' = 'capacity')::bigint AS capacity_skips,
//	  count(*) FILTER (WHERE j.job->>'failure' = 'call_limit')::bigint AS attempt_limit_exhaustion
//	FROM router.llm_escalation_jobs j
//	JOIN router.llm_escalation_sessions s ON s.lifetime = j.lifetime
//	WHERE ($1::boolean OR s.installation_id = $2::uuid)
//	  AND s.expires_at > clock_timestamp()
func (q *Queries) GetLLMEscalationSummary(ctx context.Context, arg GetLLMEscalationSummaryParams) (GetLLMEscalationSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLLMEscalationSummary, arg.AllInstallations, arg.InstallationID)
	var i GetLLMEscalationSummaryRow
	err := row.Scan(
		&i.PositiveJudgments,
		&i.ActualInterventions,
		&i.ShadowInterventions,
		&i.StaleResults,
		&i.Timeouts,
		&i.InvalidResponses,
		&i.CapacitySkips,
		&i.AttemptLimitExhaustion,
	)
	return i, err
}

const insertLLMEscalationCompletion = `-- name: InsertLLMEscalationCompletion :execrows
INSERT INTO router.llm_escalation_completions(lifetime,boundary)
VALUES($1::uuid, $2::bytea) ON CONFLICT DO NOTHING
`

type InsertLLMEscalationCompletionParams struct {
	Lifetime uuid.UUID
	Boundary []byte
}

// Duplicate responses neither advance cadence nor create another paid checkpoint.
//
//	INSERT INTO router.llm_escalation_completions(lifetime,boundary)
//	VALUES($1::uuid, $2::bytea) ON CONFLICT DO NOTHING
func (q *Queries) InsertLLMEscalationCompletion(ctx context.Context, arg InsertLLMEscalationCompletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLLMEscalationCompletion, arg.Lifetime, arg.Boundary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLLMEscalationContinuation = `-- name: InsertLLMEscalationContinuation :exec
INSERT INTO router.llm_escalation_continuations(activation,response_digest,lifetime,history)
SELECT $1::bytea, $2::bytea,lifetime, $3::jsonb
FROM router.llm_escalation_sessions WHERE lifetime= $4::uuid AND expires_at>clock_timestamp()
ON CONFLICT(activation,response_digest) DO NOTHING
`

type InsertLLMEscalationContinuationParams struct {
	Activation     []byte
	ResponseDigest []byte
	History        []byte
	Lifetime       uuid.UUID
}

// Immutable response histories remain available after later turns advance.
//
//	INSERT INTO router.llm_escalation_continuations(activation,response_digest,lifetime,history)
//	SELECT $1::bytea, $2::bytea,lifetime, $3::jsonb
//	FROM router.llm_escalation_sessions WHERE lifetime= $4::uuid AND expires_at>clock_timestamp()
//	ON CONFLICT(activation,response_digest) DO NOTHING
func (q *Queries) InsertLLMEscalationContinuation(ctx context.Context, arg InsertLLMEscalationContinuationParams) error {
	_, err := q.db.Exec(ctx, insertLLMEscalationContinuation,
		arg.Activation,
		arg.ResponseDigest,
		arg.History,
		arg.Lifetime,
	)
	return err
}

const insertLLMEscalationJob = `-- name: InsertLLMEscalationJob :exec
INSERT INTO router.llm_escalation_jobs(id,lifetime,generation,checkpoint,status,lease_until,job)
VALUES($1::uuid, $2::uuid, $3::bigint, $4::bigint, $5::text,clock_timestamp()+interval '30 seconds', $6::jsonb)
`

type InsertLLMEscalationJobParams struct {
	ID         uuid.UUID
	Lifetime   uuid.UUID
	Generation int64
	Checkpoint int64
	Status     string
	Job        []byte
}

// A checkpoint retains bounded operational metadata, never the transcript.
//
//	INSERT INTO router.llm_escalation_jobs(id,lifetime,generation,checkpoint,status,lease_until,job)
//	VALUES($1::uuid, $2::uuid, $3::bigint, $4::bigint, $5::text,clock_timestamp()+interval '30 seconds', $6::jsonb)
func (q *Queries) InsertLLMEscalationJob(ctx context.Context, arg InsertLLMEscalationJobParams) error {
	_, err := q.db.Exec(ctx, insertLLMEscalationJob,
		arg.ID,
		arg.Lifetime,
		arg.Generation,
		arg.Checkpoint,
		arg.Status,
		arg.Job,
	)
	return err
}

const insertLLMEscalationSession = `-- name: InsertLLMEscalationSession :exec
INSERT INTO router.llm_escalation_sessions(scope,lifetime,installation_id,state,expires_at)
VALUES($1::bytea, $2::uuid, $3::uuid, $4::jsonb,clock_timestamp()+interval '24 hours')
ON CONFLICT(scope) DO NOTHING
`

type InsertLLMEscalationSessionParams struct {
	Scope          []byte
	Lifetime       uuid.UUID
	InstallationID uuid.UUID
	State          []byte
}

// Concurrent starts share the existing lifetime.
//
//	INSERT INTO router.llm_escalation_sessions(scope,lifetime,installation_id,state,expires_at)
//	VALUES($1::bytea, $2::uuid, $3::uuid, $4::jsonb,clock_timestamp()+interval '24 hours')
//	ON CONFLICT(scope) DO NOTHING
func (q *Queries) InsertLLMEscalationSession(ctx context.Context, arg InsertLLMEscalationSessionParams) error {
	_, err := q.db.Exec(ctx, insertLLMEscalationSession,
		arg.Scope,
		arg.Lifetime,
		arg.InstallationID,
		arg.State,
	)
	return err
}

const updateLLMEscalationJobApplied = `-- name: UpdateLLMEscalationJobApplied :execrows
UPDATE router.llm_escalation_jobs SET status= $1::text,job= $2::jsonb
WHERE id= $3::uuid AND lifetime= $4::uuid AND status= $5::text
`

type UpdateLLMEscalationJobAppliedParams struct {
	Status          string
	Job             []byte
	ID              uuid.UUID
	Lifetime        uuid.UUID
	CompletedStatus string
}

// Applied metadata is written under the owning session's short lock.
//
//	UPDATE router.llm_escalation_jobs SET status= $1::text,job= $2::jsonb
//	WHERE id= $3::uuid AND lifetime= $4::uuid AND status= $5::text
func (q *Queries) UpdateLLMEscalationJobApplied(ctx context.Context, arg UpdateLLMEscalationJobAppliedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLLMEscalationJobApplied,
		arg.Status,
		arg.Job,
		arg.ID,
		arg.Lifetime,
		arg.CompletedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLLMEscalationJobFinished = `-- name: UpdateLLMEscalationJobFinished :execrows
UPDATE router.llm_escalation_jobs j SET status= $1::text,job= $2::jsonb
FROM router.llm_escalation_sessions s
WHERE j.id= $3::uuid AND j.lifetime= $4::uuid AND j.status= $5::text
AND j.lease_until>clock_timestamp() AND s.lifetime=j.lifetime AND s.expires_at>clock_timestamp()
AND (s.state->>'generation')::bigint=j.generation AND (s.state->>'latest_checkpoint')::bigint=j.checkpoint
`

type UpdateLLMEscalationJobFinishedParams struct {
	Status        string
	Job           []byte
	ID            uuid.UUID
	Lifetime      uuid.UUID
	RunningStatus string
}

// A result cannot outlive its session, generation, checkpoint, or inference lease.
//
//	UPDATE router.llm_escalation_jobs j SET status= $1::text,job= $2::jsonb
//	FROM router.llm_escalation_sessions s
//	WHERE j.id= $3::uuid AND j.lifetime= $4::uuid AND j.status= $5::text
//	AND j.lease_until>clock_timestamp() AND s.lifetime=j.lifetime AND s.expires_at>clock_timestamp()
//	AND (s.state->>'generation')::bigint=j.generation AND (s.state->>'latest_checkpoint')::bigint=j.checkpoint
func (q *Queries) UpdateLLMEscalationJobFinished(ctx context.Context, arg UpdateLLMEscalationJobFinishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLLMEscalationJobFinished,
		arg.Status,
		arg.Job,
		arg.ID,
		arg.Lifetime,
		arg.RunningStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLLMEscalationJobMetadata = `-- name: UpdateLLMEscalationJobMetadata :execrows
UPDATE router.llm_escalation_jobs SET job= $1::jsonb
WHERE id= $2::uuid AND lifetime= $3::uuid AND status= $4::text
`

type UpdateLLMEscalationJobMetadataParams struct {
	Job             []byte
	ID              uuid.UUID
	Lifetime        uuid.UUID
	CompletedStatus string
}

// Records an application attempt without consuming the pending verdict.
//
//	UPDATE router.llm_escalation_jobs SET job= $1::jsonb
//	WHERE id= $2::uuid AND lifetime= $3::uuid AND status= $4::text
func (q *Queries) UpdateLLMEscalationJobMetadata(ctx context.Context, arg UpdateLLMEscalationJobMetadataParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLLMEscalationJobMetadata,
		arg.Job,
		arg.ID,
		arg.Lifetime,
		arg.CompletedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLLMEscalationJobStale = `-- name: UpdateLLMEscalationJobStale :exec
UPDATE router.llm_escalation_jobs SET status = $1::text,job = $2::jsonb
WHERE id = $3::uuid AND lifetime = $4::uuid AND status = $5::text
`

type UpdateLLMEscalationJobStaleParams struct {
	Status        string
	Job           []byte
	ID            uuid.UUID
	Lifetime      uuid.UUID
	RunningStatus string
}

// Stale work retains measured spend but cannot become an applicable verdict.
//
//	UPDATE router.llm_escalation_jobs SET status = $1::text,job = $2::jsonb
//	WHERE id = $3::uuid AND lifetime = $4::uuid AND status = $5::text
func (q *Queries) UpdateLLMEscalationJobStale(ctx context.Context, arg UpdateLLMEscalationJobStaleParams) error {
	_, err := q.db.Exec(ctx, updateLLMEscalationJobStale,
		arg.Status,
		arg.Job,
		arg.ID,
		arg.Lifetime,
		arg.RunningStatus,
	)
	return err
}

const updateLLMEscalationSession = `-- name: UpdateLLMEscalationSession :execrows
UPDATE router.llm_escalation_sessions SET state= $1::jsonb,updated_at=clock_timestamp(),expires_at=clock_timestamp()+interval '24 hours'
WHERE scope= $2::bytea AND lifetime= $3::uuid AND expires_at>clock_timestamp()
`

type UpdateLLMEscalationSessionParams struct {
	State    []byte
	Scope    []byte
	Lifetime uuid.UUID
}

// Lifetime ownership prevents a stale request from resurrecting expired state.
//
//	UPDATE router.llm_escalation_sessions SET state= $1::jsonb,updated_at=clock_timestamp(),expires_at=clock_timestamp()+interval '24 hours'
//	WHERE scope= $2::bytea AND lifetime= $3::uuid AND expires_at>clock_timestamp()
func (q *Queries) UpdateLLMEscalationSession(ctx context.Context, arg UpdateLLMEscalationSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLLMEscalationSession, arg.State, arg.Scope, arg.Lifetime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
