// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_escalation_check_fixtures.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const updateLLMEscalationFixtureLeaseExpired = `-- name: UpdateLLMEscalationFixtureLeaseExpired :exec
UPDATE router.llm_escalation_jobs j SET lease_until=clock_timestamp()-interval '1 second'
FROM router.llm_escalation_sessions s
WHERE s.lifetime=j.lifetime AND s.installation_id = $1::uuid AND j.id = $2::uuid
`

type UpdateLLMEscalationFixtureLeaseExpiredParams struct {
	InstallationID uuid.UUID
	ID             uuid.UUID
}

// Only the disposable installation's job may be expired by the runtime check.
//
//	UPDATE router.llm_escalation_jobs j SET lease_until=clock_timestamp()-interval '1 second'
//	FROM router.llm_escalation_sessions s
//	WHERE s.lifetime=j.lifetime AND s.installation_id = $1::uuid AND j.id = $2::uuid
func (q *Queries) UpdateLLMEscalationFixtureLeaseExpired(ctx context.Context, arg UpdateLLMEscalationFixtureLeaseExpiredParams) error {
	_, err := q.db.Exec(ctx, updateLLMEscalationFixtureLeaseExpired, arg.InstallationID, arg.ID)
	return err
}

const updateLLMEscalationFixtureSessionExpired = `-- name: UpdateLLMEscalationFixtureSessionExpired :exec
UPDATE router.llm_escalation_sessions SET expires_at=clock_timestamp()-interval '1 second'
WHERE installation_id = $1::uuid AND lifetime = $2::uuid
`

type UpdateLLMEscalationFixtureSessionExpiredParams struct {
	InstallationID uuid.UUID
	Lifetime       uuid.UUID
}

// Explicit lifetime ownership confines test expiry to the disposable fixture.
//
//	UPDATE router.llm_escalation_sessions SET expires_at=clock_timestamp()-interval '1 second'
//	WHERE installation_id = $1::uuid AND lifetime = $2::uuid
func (q *Queries) UpdateLLMEscalationFixtureSessionExpired(ctx context.Context, arg UpdateLLMEscalationFixtureSessionExpiredParams) error {
	_, err := q.db.Exec(ctx, updateLLMEscalationFixtureSessionExpired, arg.InstallationID, arg.Lifetime)
	return err
}
