// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RouterClusterModelList struct {
	ID             uuid.UUID
	OrganizationID string
	APIKeyID       uuid.UUID
	ClusterLabel   string
	Models         []string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Published mirror of internal/flags.Registry, upserted by the router at boot. Read by the Weave control plane to render the per-org flag override admin UI. Never read on the request path.
type RouterFlagDefinition struct {
	Key string
	// Value type: bool, int, float, or string. A stored override whose JSON type disagrees is rejected at parse time.
	Kind   string
	EnvVar string
	// Deployment default as resolved from env_var at the last boot, rendered as text. Display only; the routing path reads the live in-process value, not this column.
	DeploymentDefault *string
	// Whether a per-organization override may be written for this flag. A registered-but-not-overridable flag is shown read-only and rejects writes.
	OrgOverridable bool
	Description    string
	// Monotonic internal/flags.Registry version. Pruning only considers rows at or below the current version, so an older rolling-deploy revision cannot delete a newer definition.
	RegistryVersion int32
	UpdatedAt       pgtype.Timestamptz
}

// Cyclic tool-call loop detections: ops signal and (session, looping_model) -> looped training labels
type RouterLoopEscalationEvent struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	InstallationID uuid.UUID
	// 16-byte digest matching router.session_pins.session_key; join key for post-escalation outcome
	SessionKey       []byte
	Role             string
	LoopingModel     string
	Action           string
	EscalationTarget string
	LoopTool         string
	LoopInputHash    string
	RepeatCount      int32
	DistinctRatio    float64
	WindowSize       int32
}

// Rotatable bearer keys (rk_ prefix). An installation may hold multiple active keys; identity is carried by router.model_router_users.
type RouterModelRouterAPIKey struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	ExternalID     string
	Name           *string
	KeyPrefix      string
	// SHA-256 of the full rk_ token
	KeyHash string
	// Last 4 chars for display
	KeySuffix         string
	LastUsedAt        pgtype.Timestamp
	CreatedAt         pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
	CreatedBy         *string
	SpendCapUsdMicros *int64
	SpentUsdMicros    int64
	// routing = rk_ data-plane key (can proxy and spend); analytics_read = ra_ export key (read-only, non-billable)
	Scope string
}

// Customer-owned provider API keys for BYOK routing
type RouterModelRouterExternalAPIKey struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	ExternalID     string
	Provider       string
	// AES-256-GCM encrypted API key with 12-byte nonce prepended
	KeyCiphertext []byte
	KeyPrefix     string
	KeySuffix     string
	// SHA-256 of plaintext for deduplication display
	KeyFingerprint string
	Name           *string
	LastUsedAt     pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
	CreatedBy      *string
	// Customer-supplied upstream base URL; NULL uses the deployment default for the provider
	BaseURL *string
	// Catalog model id -> upstream model id rewrite for this key's endpoint; NULL means no rewrite
	ModelAliases []byte
	// Header carrying the caller identity to this key's endpoint; NULL forwards nothing
	IdentityHeaderName *string
	// email = bare address, json = URL-encoded JSON property bag
	IdentityHeaderFormat *string
	// bearer = send the stored secret as-is, keypair_jwt = the secret is an RSA private key the router signs short-lived JWTs with, wif = no stored secret and the router attests its own workload identity, azure_entra = the secret is an Azure Entra client secret used to mint a short-lived bearer token
	AuthType string
	// Account identifier for keypair_jwt, or Microsoft Entra tenant ID for azure_entra
	AuthAccount *string
	// User/principal for keypair_jwt, or Microsoft Entra client ID for azure_entra
	AuthUser *string
	// Weave account that soft-deleted or replaced this key; NULL when the router deleted it internally or attribution predates the column
	DeletedBy *string
	// Inbound client header names copied verbatim to this key's endpoint; NULL forwards nothing
	ForwardedClientHeaders []string
	// JSON baggage header forwarded to this key's endpoint with the resolved caller email under on-behalf-of; NULL forwards nothing
	BaggageHeader *string
}

// Customer router installations; owns API keys
type RouterModelRouterInstallation struct {
	ID                          uuid.UUID
	ExternalID                  string
	Name                        string
	CreatedAt                   pgtype.Timestamp
	UpdatedAt                   pgtype.Timestamp
	DeletedAt                   pgtype.Timestamp
	CreatedBy                   *string
	ExcludedModels              []string
	ExcludedProviders           []string
	RoutingQualityWeight        *float64
	UsageBypassEnabled          bool
	UsageBypassThreshold        *float64
	PreferredModels             []string
	SubscriptionRoutingDisabled bool
	// Optional serving-strategy override. NULL follows the deployment default.
	RoutingStrategy              *string
	RoutingRolloutID             *string
	PolicyShadowStrategy         *string
	PolicyDebugEnabled           bool
	PolicyHeaderOverridesEnabled bool
	PolicyRoutingIntent          *string
	// Privacy snapshot synced from the organization AI-training setting. False disables policy learning.
	AiTrainingAllowed bool
	// Managed-mode opt-in: honor this installation's BYOK provider keys
	ByokEnabled bool
	// Per-installation capture ceiling (off|hashed|full); NULL uses the deployment default
	ContentCaptureMode   *string
	HideTerminalSurfaces bool
	// Org-level positive model allowlist. Empty = no restriction. Effective set = allowed_models minus excluded_models. Fail-closed: an allowlist with no eligible overlap refuses the turn.
	AllowedModels []string
	// Timestamp of the installation's first routed request. Monotonic — never moves backwards or clears on key rotation.
	FirstRequestServedAt pgtype.Timestamptz
	// Sparse per-org behavioral flag overrides, keyed by internal/flags registry key. Empty object = inherit every deployment default. Precedence: header override > this > env default, unless ROUTER_FLAG_OVERRIDES_DISABLED is set.
	FlagOverrides []byte
	// Optional model allowlist while the caller subscription is active; empty means no conditional restriction.
	ModelsWhenSubscriptionActive []string
	// Optional model allowlist while the caller subscription is exhausted; empty means no conditional restriction.
	ModelsWhenSubscriptionInactive []string
}

type RouterModelRouterRequestTelemetry struct {
	ID                     uuid.UUID
	InstallationID         uuid.UUID
	RequestID              string
	SpanType               string
	TraceID                string
	Timestamp              pgtype.Timestamptz
	RequestedModel         *string
	DecisionModel          *string
	DecisionProvider       *string
	DecisionReason         *string
	EstimatedInputTokens   *int32
	StickyHit              *bool
	EmbedInput             *string
	InputTokens            *int32
	OutputTokens           *int32
	RequestedInputCostUsd  *int64
	RequestedOutputCostUsd *int64
	ActualInputCostUsd     *int64
	ActualOutputCostUsd    *int64
	RouteLatencyMs         *int64
	UpstreamLatencyMs      *int64
	TotalLatencyMs         *int64
	CrossFormat            *bool
	UpstreamStatusCode     *int32
	CreatedAt              pgtype.Timestamptz
	ClusterIds             []int32
	CandidateModels        []string
	ChosenScore            *float64
	AlphaBreakdown         []byte
	ClusterRouterVersion   *string
	TtftMs                 *int64
	CacheCreationTokens    *int32
	CacheReadTokens        *int32
	DeviceID               *string
	SessionID              *string
	CandidateScores        []byte
	Propensity             *float64
	RouterUserID           pgtype.UUID
	ClientApp              *string
	TurnType               *string
	RolloutID              *string
	UpstreamFinishReason   *string
	StopReason             *string
	ToolUseBlocks          *int32
	InvalidToolArgsBlocks  *int32
	FailoverUsed           *bool
	DegenerateShadow       *bool
	// 16-byte session digest (matches session_pins / spiral_shadow_events). NULL on rows written before this column existed. Join key to spiral_shadow_events on (installation_id, session_key, role).
	SessionKey []byte
	// Session-pin role used for the turn (roleForTier of the requested model). Pairs with session_key to identify the turn thread; matches spiral_shadow_events.role.
	Role *string
	// The cluster scorer's fresh pick for this turn, recorded even when the planner returned STAY (decision_model then names the pinned model served). NULL when the scorer did not run.
	FreshDecisionModel *string
	// The fresh pre-argmax score vector (model -> blended score) from this turn's scorer run, recorded even on STAY. Sweep tau against served decision_model + catalog tier to measure the hysteresis downgrade opportunity. NULL when the scorer did not run.
	FreshCandidateScores []byte
	// Age of the loaded session pin in seconds at decision time; supports min-dwell analysis for the hysteresis policy. NULL when no pin was loaded.
	PinAgeSec *int64
	// Summed raw-JSON byte size of the trailing turn's tool_result payload(s) -- the incoming tool-output size. Structural triviality proxy for the tier-cap shadow. NULL when the turn carries no trailing tool_result.
	ToolResultBytes *int32
	// Safe display prefix (first 8 characters) of the upstream credential that served the turn. NULL on deployment-key turns.
	CredentialKeyPrefix *string
	// Safe display suffix (last 4 characters) of the upstream credential that served the turn. NULL on deployment-key turns or very short credentials.
	CredentialKeySuffix *string
	// Which credential precedence branch served the turn: subscription, codex_subscription, byok, or client. NULL on deployment-key turns.
	CredentialSource     *string
	APIKeyID             pgtype.UUID
	Strategy             *string
	RouteID              *string
	PolicyRouteKey       *string
	PolicyArtifactID     *string
	PolicyArtifactSha256 *string
	RosterVersion        *string
	SidecarSchemaVersion *string
	TrainingAllowed      *bool
	CaptureMode          *string
	DebugRef             *string
	UnifiedLimitHeaders  []byte
	// Planner verdict for this turn: stay or switch. NULL when the planner did not run.
	PlannerOutcome *string
	// Snake-case planner reason (ev_positive, ev_negative, same_model, no_pin, …). NULL when the planner did not run.
	PlannerReason *string
	// Pinned model the planner compared against. On a switch this is the model that was abandoned; decision_model is the one served.
	PlannerPinModel *string
	// Provider binding of the pin the planner priced. Distinct from decision_provider on a switch.
	PlannerPinProvider *string
	// Planner expected_savings as USD micros (USD × 1e6), not float USD. NULL when the planner did not run.
	PlannerExpectedSavingsUsdMicros *int64
	// Planner eviction_cost as USD micros (USD × 1e6), not float USD. NULL when the planner did not run.
	PlannerEvictionCostUsdMicros *int64
	// Whether the EV math priced the pin as cache-cold. NULL when the planner did not run.
	PlannerPinCacheCold *bool
	// Shadow (corrected-economics) verdict: stay or switch. NULL when the shadow was not computed.
	PlannerShadowOutcome *string
	// Shadow expected_savings as USD micros (USD × 1e6). NULL when the shadow was not computed.
	PlannerShadowSavingsUsdMicros *int64
	// Shadow verdict of the HMM cache gate on an authoritative turn: stay or switch. NEVER what was served -- authoritative turns always serve decision_model. NULL when the shadow did not run.
	AuthorityShadowOutcome *string
	// The gate's own verdict that it would have served authority_shadow_stay_model instead of decision_model. Use this, not a string compare: stay_model is a serving identity that may carry ':effort' while decision_model is a bare catalog ID.
	AuthorityShadowWouldDiverge *bool
	// Snake-case reason from the shadow gate (ev_positive, ev_negative, same_model, no_pin, no_prior_usage, hmm_upgrade_confidence_low, ...). Read no_pin carefully: it also covers a pin that exists but whose serving identity carries ':effort', because catalog.ByID strips a date suffix and not an effort suffix, so normalizeHMMStayPin rejects it. no_pin is therefore NOT the same as 'this session had no pin'.
	AuthorityShadowReason *string
	// Pin the shadow gate priced against, as a serving identity -- it carries ':effort' when the pin used one, unlike the bare decision_model. Compare via authority_shadow_would_diverge rather than against decision_model directly.
	AuthorityShadowStayModel *string
	// Provider binding of authority_shadow_stay_model.
	AuthorityShadowStayProvider *string
	// Signed expected savings as USD micros (USD x 1e6) under the deployed economics config. Negative on a typical stay; not clamped. NULL on an early exit (no_pin, no_prior_usage, same_model, pricing_missing) where the cost arithmetic never ran -- a stored 0 there would be a fabricated measurement.
	AuthorityShadowSavingsUsdMicros *int64
	// Signed eviction cost as USD micros (USD x 1e6) under the deployed economics config. NULL on an early exit, like the savings column.
	AuthorityShadowEvictionCostUsdMicros *int64
	// Whether the shadow EV math priced the pin as cache-cold. NULL on an early exit, where the flag is meaningless rather than false.
	AuthorityShadowPinCacheCold *bool
	// Verdict under corrected cache-aware economics, computed by planner.Decide as its own shadow on every EV turn regardless of the deployed config. Pre-gate: the upgrade-confidence and same-tier overrides are NOT applied to it, unlike authority_shadow_outcome. NULL on an early exit -- the enum zero value renders as 'stay', so an uncomputed verdict must never be stored.
	AuthorityShadowCorrectedOutcome *string
	// Signed expected savings under corrected economics as USD micros (USD x 1e6).
	AuthorityShadowCorrectedSavingsUsdMicros *int64
	// Sidecar candidate score for authority_shadow_stay_model this turn. NULL when the sidecar reported no score for the pin -- that NULL rate is the measurement that decides whether a quality tie-band is implementable at all.
	AuthorityShadowStayScore *float64
	// Sidecar candidate score for the served model this turn, paired with authority_shadow_stay_score.
	AuthorityShadowFreshScore *float64
	// The actual served-path pin tier for this turn (for example, authoritative_per_turn or hmm_ev_stay_ev_negative). NULL on rows written before this column existed or when no turn-loop tier was available.
	PinTier *string
	// Consecutive errored tool_results at the tail of history at request time
	SpiralErrStreak *int32
	// Errored tool_results across the whole history at request time
	SpiralErroredResults *int32
	// Total tool_results across the whole history at request time
	SpiralToolResults *int32
	// Edits targeting the single most-edited file path
	SpiralMaxSameFileEdits *int32
	// Truncated sha256 of the most-edited file path: confirms "the same file" across turns without persisting customer file names
	SpiralSameFilePathHash *string
	// Fraction of the last 12 tool-call signatures that are duplicates; 0 before 12 calls exist
	SpiralRepeatFrac *float64
	// Consecutive tool-less assistant messages since the last real user input
	SpiralMonologueLen *int32
	// Assistant tool_use blocks across the whole history at request time
	SpiralToolCallCount *int32
	// Messages in the inbound history at request time
	SpiralMessageCount *int32
	// Length of the trailing A/B/A/B alternation between exactly two tool-call signatures
	SpiralPingPongLen *int32
	// Tool calls made since the last non-errored edit/write result; meaningless unless spiral_edit_attempted is true
	SpiralStepsSinceProgress *int32
	// Whether the session has attempted any edit yet; qualifies spiral_steps_since_progress
	SpiralEditAttempted *bool
	// Signal classes whose thresholds this turn crossed (err_streak, same_file_thrash, repetition, monologue, ping_pong, no_progress); empty array when the snapshot was recorded and nothing fired
	SpiralReasons          []string
	RequestedAllowedModels []string
}

// End-user identities seen on inbound requests, scoped to an installation. Replaces the per-user API key pattern.
type RouterModelRouterUser struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	// Lowercased, trimmed user email (typically git user.email). Nullable: Claude CLI versions that send only account_uuid in metadata.user_id produce email-NULL rows keyed on (installation_id, claude_account_uuid).
	Email *string
	// Optional Claude Code account_uuid carried in metadata.user_id; informational only.
	ClaudeAccountUUID pgtype.UUID
	FirstSeenAt       pgtype.Timestamp
	LastSeenAt        pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
	// Free-form user display name (typically git user.name) carried on the X-Weave-User-Name request header. Nullable: requests without the header leave the column NULL; existing rows are not back-filled.
	DisplayName *string
}

type RouterModelRouterUserClusterModelList struct {
	RouterUserID uuid.UUID
	// Free-form label from the deployed HMM roster artifact (see GET /v1/router/hmm-roster). Not an enum — a roster bump can add or rename clusters.
	ClusterLabel string
	// Denormalized for control-plane queries. The router never reads it — lookups are by router_user_id only.
	OrganizationID string
	Models         []string
	CreatedBy      *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RouterModelRouterUserMonthlySpend struct {
	RouterUserID   uuid.UUID
	Month          pgtype.Date
	SpentUsdMicros int64
	UpdatedAt      pgtype.Timestamptz
}

type RouterModelRouterUserSpendLimit struct {
	RouterUserID          uuid.UUID
	MonthlyLimitUsdMicros *int64
	CreatedBy             *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type RouterOrganizationAutopayConfig struct {
	OrganizationID              string
	Enabled                     bool
	ThresholdUsdMicros          int64
	RechargeUsdMicros           int64
	HasPaymentMethod            bool
	State                       string
	ConsecutiveFailures         int32
	LastAttemptID               pgtype.UUID
	LastAttemptAt               pgtype.Timestamptz
	LastSuccessAt               pgtype.Timestamptz
	CooldownUntil               pgtype.Timestamptz
	CreatedBy                   *string
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	MonthlyRechargeCapUsdMicros *int64
	RechargedMonth              pgtype.Date
	RechargedMonthUsdMicros     int64
}

type RouterOrganizationBillingOverride struct {
	OrganizationID string
	Reason         string
	ExpiresAt      pgtype.Timestamptz
	CreatedBy      *string
	CreatedAt      pgtype.Timestamptz
}

type RouterOrganizationCreditBalance struct {
	OrganizationID       string
	BalanceUsdMicros     int64
	UpdatedAt            pgtype.Timestamptz
	LowBalanceNotifiedAt pgtype.Timestamptz
}

type RouterOrganizationCreditLedger struct {
	ID                    uuid.UUID
	OrganizationID        string
	DeltaUsdMicros        int64
	NotionalCostMicros    int64
	BalanceAfterMicros    int64
	EntryType             string
	StripePaymentIntentID *string
	RouterRequestID       *string
	RouterModel           *string
	CreatedAt             pgtype.Timestamptz
	Memo                  *string
}

type RouterOrganizationMonthlySpend struct {
	OrganizationID string
	Month          pgtype.Date
	SpentUsdMicros int64
	UpdatedAt      pgtype.Timestamptz
}

type RouterOrganizationSpendLimit struct {
	OrganizationID            string
	UserMonthlyLimitUsdMicros *int64
	OrgMonthlyLimitUsdMicros  *int64
	CreatedBy                 *string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

// Content-free serving-vs-shadow policy comparisons; shadow decisions never dispatch or enter online learning
type RouterPolicyShadowDecision struct {
	ID                          uuid.UUID
	CreatedAt                   pgtype.Timestamptz
	InstallationID              uuid.UUID
	OrganizationID              *string
	RolloutID                   *string
	ClientApp                   *string
	TrainingAllowed             bool
	ServingStrategy             string
	ServingModel                string
	ServingProvider             string
	ServingRouteID              *string
	ServingPolicyRouteKey       *string
	ServingPolicyArtifactID     *string
	ServingPolicyArtifactSha256 *string
	ShadowStrategy              string
	ShadowModel                 *string
	ShadowProvider              *string
	ShadowRouteID               *string
	ShadowPolicyRouteKey        *string
	ShadowPolicyArtifactID      *string
	ShadowPolicyArtifactSha256  *string
	ShadowLatencyMs             int64
	ShadowError                 *string
	ModelsAgree                 bool
}

type RouterProductionRequestTelemetry struct {
	ID                     uuid.UUID
	InstallationID         uuid.UUID
	RequestID              string
	SpanType               string
	TraceID                string
	Timestamp              pgtype.Timestamptz
	RequestedModel         *string
	DecisionModel          *string
	DecisionProvider       *string
	DecisionReason         *string
	EstimatedInputTokens   *int32
	StickyHit              *bool
	EmbedInput             *string
	InputTokens            *int32
	OutputTokens           *int32
	RequestedInputCostUsd  *int64
	RequestedOutputCostUsd *int64
	ActualInputCostUsd     *int64
	ActualOutputCostUsd    *int64
	RouteLatencyMs         *int64
	UpstreamLatencyMs      *int64
	TotalLatencyMs         *int64
	CrossFormat            *bool
	UpstreamStatusCode     *int32
	CreatedAt              pgtype.Timestamptz
	ClusterIds             []int32
	CandidateModels        []string
	ChosenScore            *float64
	AlphaBreakdown         []byte
	ClusterRouterVersion   *string
	TtftMs                 *int64
	CacheCreationTokens    *int32
	CacheReadTokens        *int32
	DeviceID               *string
	SessionID              *string
	CandidateScores        []byte
	Propensity             *float64
	RouterUserID           pgtype.UUID
	ClientApp              *string
	TurnType               *string
	RolloutID              *string
	UpstreamFinishReason   *string
	StopReason             *string
	ToolUseBlocks          *int32
	InvalidToolArgsBlocks  *int32
	FailoverUsed           *bool
	DegenerateShadow       *bool
	SessionKey             []byte
	Role                   *string
	FreshDecisionModel     *string
	FreshCandidateScores   []byte
	PinAgeSec              *int64
	ToolResultBytes        *int32
	CredentialKeyPrefix    *string
	CredentialKeySuffix    *string
	CredentialSource       *string
}

// Router-owned per-request human feedback captured via the no-login feedback link; mirrored into Weave via the router.feedback OTLP span
type RouterRequestFeedback struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	InstallationID uuid.UUID
	ExternalID     string
	RequestID      string
	Rating         string
	Comment        *string
	Source         string
	RouterUserID   pgtype.UUID
}

// User-submitted /router-feedback about routing decisions or model performance
type RouterRouterFeedback struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	InstallationID uuid.UUID
	// 16-byte digest matching router.session_pins.session_key
	SessionKey     []byte
	Role           string
	RouterUserID   pgtype.UUID
	ClientApp      *string
	SessionID      *string
	RequestedModel string
	ServedModel    string
	Feedback       string
	// "up", "down", or NULL. Null means abstain or note-only (no verdict).
	Rating *string
	// "fast", "explore", "balanced", "high", or "maximum" — the complexity label the submitter thinks the turn needed. Set when rating is "down", NULL otherwise.
	SuggestedLabel *string
	// How the feedback was submitted: "user" (explicit /rf command), "auto" (automated judge at session stop).
	Source string
	// Telemetry request_id for the specific turn this feedback targets. NULL when no sequence was specified.
	RequestID *string
	// Sidecar correlation id from the telemetry row (HMM/RL). NULL when no sequence was specified.
	RouteID *string
}

// Session-sticky routing pins; sliding 1h TTL matching Anthropic prompt cache
type RouterSessionPin struct {
	// 16-byte digest derived from api_key_id + (metadata.user_id | system+first-user hashes)
	SessionKey []byte
	// Stage 1 always emits "default"; turn-type roles land with §3.3
	Role                      string
	InstallationID            uuid.UUID
	PinnedProvider            string
	PinnedModel               string
	DecisionReason            string
	TurnCount                 int32
	PinnedUntil               pgtype.Timestamp
	FirstPinnedAt             pgtype.Timestamp
	LastSeenAt                pgtype.Timestamp
	LastInputTokens           int32
	LastCachedReadTokens      int32
	LastCachedWriteTokens     int32
	LastOutputTokens          int32
	LastTurnEndedAt           pgtype.Timestamptz
	ConsecutiveUpstreamErrors int32
	LastServedModel           string
	HasEverSwitched           bool
	PairedProvider            string
	PairedModel               string
	ConsecutiveOverloadErrors int32
	DisabledProviders         []string
	PolicyGroup               string
	RoutingStrategy           string
}

// Explicit per-session router strategy preferences
type RouterSessionStrategyPreference struct {
	InstallationID uuid.UUID
	SessionKey     []byte
	Strategy       string
	Enabled        bool
}

// Shadow-mode spiral (death-march) detections: log-only fire-rate corpus measured on live traffic before escalation is armed
type RouterSpiralShadowEvent struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	InstallationID uuid.UUID
	// 16-byte digest matching router.session_pins.session_key; join key for session outcome
	SessionKey       []byte
	Role             string
	RoutedModel      string
	TurnType         string
	Reason           string
	ErrStreak        int32
	ErroredResults   int32
	ToolResults      int32
	MaxSameFileEdits int32
	SameFilePathHash string
	RepeatFrac       float64
	MonologueLen     int32
	ToolCallCount    int32
	MessageCount     int32
	// Length of the trailing A/B/A/B alternation between exactly two tool-call signatures
	PingPongLen int32
	// Tool calls made since the last non-errored edit/write tool_result; 0 when the session has never attempted an edit
	StepsSinceProgress int32
}

type RouterStruggleEscalationEvent struct {
	ID                  uuid.UUID
	CreatedAt           pgtype.Timestamptz
	InstallationID      uuid.UUID
	SessionKey          []byte
	Role                string
	StrugglingModel     string
	Action              string
	EscalationTarget    string
	TurnCount           int32
	WallSeconds         int64
	SessionEverSwitched bool
	// What armed this escalation: turn_wall (turn/wall thresholds) or evidence (behavioral signals)
	ArmingMode string
	// Spiral signal classes present at arming time (err_streak, same_file_thrash, repetition, monologue, ping_pong, no_progress)
	EvidenceReasons []string
}

type RouterStruggleShadowEvent struct {
	ID                  uuid.UUID
	CreatedAt           pgtype.Timestamptz
	InstallationID      uuid.UUID
	SessionKey          []byte
	Role                string
	RoutedModel         string
	TurnType            string
	Reason              string
	TurnCount           int32
	WallSeconds         int64
	SessionEverSwitched bool
	EstInputTokens      int32
}
