// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_subscription_accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createModelRouterSubscriptionAccount = `-- name: CreateModelRouterSubscriptionAccount :one
INSERT INTO router.model_router_subscription_accounts (
  api_key_id, provider, external_account_id, refresh_token_ciphertext
)
VALUES ($1::uuid, $2::varchar, $3::varchar, $4::bytea)
RETURNING id, api_key_id, provider, external_account_id, refresh_token_ciphertext, enabled, cooldown_until, created_at, updated_at
`

type CreateModelRouterSubscriptionAccountParams struct {
	APIKeyID               uuid.UUID
	Provider               string
	ExternalAccountID      string
	RefreshTokenCiphertext []byte
}

// CreateModelRouterSubscriptionAccount
//
//	INSERT INTO router.model_router_subscription_accounts (
//	  api_key_id, provider, external_account_id, refresh_token_ciphertext
//	)
//	VALUES ($1::uuid, $2::varchar, $3::varchar, $4::bytea)
//	RETURNING id, api_key_id, provider, external_account_id, refresh_token_ciphertext, enabled, cooldown_until, created_at, updated_at
func (q *Queries) CreateModelRouterSubscriptionAccount(ctx context.Context, arg CreateModelRouterSubscriptionAccountParams) (RouterModelRouterSubscriptionAccount, error) {
	row := q.db.QueryRow(ctx, createModelRouterSubscriptionAccount,
		arg.APIKeyID,
		arg.Provider,
		arg.ExternalAccountID,
		arg.RefreshTokenCiphertext,
	)
	var i RouterModelRouterSubscriptionAccount
	err := row.Scan(
		&i.ID,
		&i.APIKeyID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.RefreshTokenCiphertext,
		&i.Enabled,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteModelRouterSubscriptionAccount = `-- name: DeleteModelRouterSubscriptionAccount :execrows
DELETE FROM router.model_router_subscription_accounts
WHERE id = $1::uuid AND api_key_id = $2::uuid
`

type DeleteModelRouterSubscriptionAccountParams struct {
	ID       uuid.UUID
	APIKeyID uuid.UUID
}

// DeleteModelRouterSubscriptionAccount
//
//	DELETE FROM router.model_router_subscription_accounts
//	WHERE id = $1::uuid AND api_key_id = $2::uuid
func (q *Queries) DeleteModelRouterSubscriptionAccount(ctx context.Context, arg DeleteModelRouterSubscriptionAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModelRouterSubscriptionAccount, arg.ID, arg.APIKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listModelRouterSubscriptionAccounts = `-- name: ListModelRouterSubscriptionAccounts :many
SELECT id, api_key_id, provider, external_account_id, refresh_token_ciphertext, enabled, cooldown_until, created_at, updated_at
FROM router.model_router_subscription_accounts
WHERE api_key_id = $1::uuid
ORDER BY provider, created_at
`

// Account state is scoped by api_key_id so a router key can never manage another
// user's subscription account.
//
//	SELECT id, api_key_id, provider, external_account_id, refresh_token_ciphertext, enabled, cooldown_until, created_at, updated_at
//	FROM router.model_router_subscription_accounts
//	WHERE api_key_id = $1::uuid
//	ORDER BY provider, created_at
func (q *Queries) ListModelRouterSubscriptionAccounts(ctx context.Context, apiKeyID uuid.UUID) ([]RouterModelRouterSubscriptionAccount, error) {
	rows, err := q.db.Query(ctx, listModelRouterSubscriptionAccounts, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterSubscriptionAccount
	for rows.Next() {
		var i RouterModelRouterSubscriptionAccount
		if err := rows.Scan(
			&i.ID,
			&i.APIKeyID,
			&i.Provider,
			&i.ExternalAccountID,
			&i.RefreshTokenCiphertext,
			&i.Enabled,
			&i.CooldownUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelRouterSubscriptionAccountState = `-- name: UpdateModelRouterSubscriptionAccountState :execrows
UPDATE router.model_router_subscription_accounts
SET enabled = $1::boolean,
    cooldown_until = $2::timestamp,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3::uuid AND api_key_id = $4::uuid
`

type UpdateModelRouterSubscriptionAccountStateParams struct {
	Enabled       bool
	CooldownUntil pgtype.Timestamp
	ID            uuid.UUID
	APIKeyID      uuid.UUID
}

// UpdateModelRouterSubscriptionAccountState
//
//	UPDATE router.model_router_subscription_accounts
//	SET enabled = $1::boolean,
//	    cooldown_until = $2::timestamp,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $3::uuid AND api_key_id = $4::uuid
func (q *Queries) UpdateModelRouterSubscriptionAccountState(ctx context.Context, arg UpdateModelRouterSubscriptionAccountStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterSubscriptionAccountState,
		arg.Enabled,
		arg.CooldownUntil,
		arg.ID,
		arg.APIKeyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterSubscriptionRefreshToken = `-- name: UpdateModelRouterSubscriptionRefreshToken :execrows
UPDATE router.model_router_subscription_accounts
SET refresh_token_ciphertext = $1::bytea,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2::uuid AND api_key_id = $3::uuid
`

type UpdateModelRouterSubscriptionRefreshTokenParams struct {
	RefreshTokenCiphertext []byte
	ID                     uuid.UUID
	APIKeyID               uuid.UUID
}

// UpdateModelRouterSubscriptionRefreshToken
//
//	UPDATE router.model_router_subscription_accounts
//	SET refresh_token_ciphertext = $1::bytea,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $2::uuid AND api_key_id = $3::uuid
func (q *Queries) UpdateModelRouterSubscriptionRefreshToken(ctx context.Context, arg UpdateModelRouterSubscriptionRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterSubscriptionRefreshToken, arg.RefreshTokenCiphertext, arg.ID, arg.APIKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
