// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_inference_attempts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getInferenceAttempts = `-- name: GetInferenceAttempts :many
SELECT id, created_at, installation_id, request_id, operation_id, attempt_index, purpose, policy_id, registry_revision, policy_revision, model, provider, binding_index, outcome, failure_reason, upstream_status_code, latency_ms, usage_known, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd_micros
FROM router.model_router_inference_attempts
WHERE installation_id = $1::uuid
  AND request_id = $2::varchar
ORDER BY operation_id, attempt_index
`

type GetInferenceAttemptsParams struct {
	InstallationID uuid.UUID
	RequestID      string
}

// Returns every attempt of one request in attempt order, grouped by operation,
// for diagnostics and the runtime inspection API.
//
//	SELECT id, created_at, installation_id, request_id, operation_id, attempt_index, purpose, policy_id, registry_revision, policy_revision, model, provider, binding_index, outcome, failure_reason, upstream_status_code, latency_ms, usage_known, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd_micros
//	FROM router.model_router_inference_attempts
//	WHERE installation_id = $1::uuid
//	  AND request_id = $2::varchar
//	ORDER BY operation_id, attempt_index
func (q *Queries) GetInferenceAttempts(ctx context.Context, arg GetInferenceAttemptsParams) ([]RouterModelRouterInferenceAttempt, error) {
	rows, err := q.db.Query(ctx, getInferenceAttempts, arg.InstallationID, arg.RequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterInferenceAttempt
	for rows.Next() {
		var i RouterModelRouterInferenceAttempt
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.InstallationID,
			&i.RequestID,
			&i.OperationID,
			&i.AttemptIndex,
			&i.Purpose,
			&i.PolicyID,
			&i.RegistryRevision,
			&i.PolicyRevision,
			&i.Model,
			&i.Provider,
			&i.BindingIndex,
			&i.Outcome,
			&i.FailureReason,
			&i.UpstreamStatusCode,
			&i.LatencyMs,
			&i.UsageKnown,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.CostUsdMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInferenceAttempt = `-- name: InsertInferenceAttempt :exec
INSERT INTO router.model_router_inference_attempts (
    installation_id,
    request_id,
    operation_id,
    attempt_index,
    purpose,
    policy_id,
    registry_revision,
    policy_revision,
    model,
    provider,
    binding_index,
    outcome,
    failure_reason,
    upstream_status_code,
    latency_ms,
    usage_known,
    input_tokens,
    output_tokens,
    cache_creation_tokens,
    cache_read_tokens,
    cost_usd_micros
) VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::int,
    $5::varchar,
    $6::varchar,
    $7::varchar,
    $8::varchar,
    $9::varchar,
    $10::varchar,
    $11::int,
    $12::varchar,
    $13::varchar,
    $14::int,
    $15::bigint,
    $16::boolean,
    $17::int,
    $18::int,
    $19::int,
    $20::int,
    $21::bigint
)
ON CONFLICT (installation_id, request_id, operation_id, attempt_index) DO NOTHING
`

type InsertInferenceAttemptParams struct {
	InstallationID      uuid.UUID
	RequestID           string
	OperationID         string
	AttemptIndex        int32
	Purpose             string
	PolicyID            string
	RegistryRevision    string
	PolicyRevision      string
	Model               string
	Provider            string
	BindingIndex        int32
	Outcome             string
	FailureReason       *string
	UpstreamStatusCode  *int32
	LatencyMs           *int64
	UsageKnown          bool
	InputTokens         *int32
	OutputTokens        *int32
	CacheCreationTokens *int32
	CacheReadTokens     *int32
	CostUsdMicros       *int64
}

// Records one upstream attempt of an inference operation. Attempts are keyed
// by (installation_id, request_id, operation_id, attempt_index) so they never
// collide with the request summary's (installation_id, request_id, span_type)
// uniqueness, and a request with several operations (main turn plus a handover
// summary) keeps each operation's attempt order intact. Usage columns are NULL
// when usage_known is false; a zero is never fabricated for unknown usage.
// Re-delivery of the same attempt is a no-op.
//
//	INSERT INTO router.model_router_inference_attempts (
//	    installation_id,
//	    request_id,
//	    operation_id,
//	    attempt_index,
//	    purpose,
//	    policy_id,
//	    registry_revision,
//	    policy_revision,
//	    model,
//	    provider,
//	    binding_index,
//	    outcome,
//	    failure_reason,
//	    upstream_status_code,
//	    latency_ms,
//	    usage_known,
//	    input_tokens,
//	    output_tokens,
//	    cache_creation_tokens,
//	    cache_read_tokens,
//	    cost_usd_micros
//	) VALUES (
//	    $1::uuid,
//	    $2::varchar,
//	    $3::varchar,
//	    $4::int,
//	    $5::varchar,
//	    $6::varchar,
//	    $7::varchar,
//	    $8::varchar,
//	    $9::varchar,
//	    $10::varchar,
//	    $11::int,
//	    $12::varchar,
//	    $13::varchar,
//	    $14::int,
//	    $15::bigint,
//	    $16::boolean,
//	    $17::int,
//	    $18::int,
//	    $19::int,
//	    $20::int,
//	    $21::bigint
//	)
//	ON CONFLICT (installation_id, request_id, operation_id, attempt_index) DO NOTHING
func (q *Queries) InsertInferenceAttempt(ctx context.Context, arg InsertInferenceAttemptParams) error {
	_, err := q.db.Exec(ctx, insertInferenceAttempt,
		arg.InstallationID,
		arg.RequestID,
		arg.OperationID,
		arg.AttemptIndex,
		arg.Purpose,
		arg.PolicyID,
		arg.RegistryRevision,
		arg.PolicyRevision,
		arg.Model,
		arg.Provider,
		arg.BindingIndex,
		arg.Outcome,
		arg.FailureReason,
		arg.UpstreamStatusCode,
		arg.LatencyMs,
		arg.UsageKnown,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheCreationTokens,
		arg.CacheReadTokens,
		arg.CostUsdMicros,
	)
	return err
}
