// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_external_api_keys.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createExternalAPIKey = `-- name: CreateExternalAPIKey :one
INSERT INTO router.model_router_external_api_keys (
    installation_id,
    external_id,
    provider,
    key_ciphertext,
    key_prefix,
    key_suffix,
    key_fingerprint,
    name,
    base_url,
    model_aliases,
    identity_header_name,
    identity_header_format,
    forwarded_client_headers,
    baggage_header,
    auth_type,
    auth_account,
    auth_user,
    created_by
)
VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::bytea,
    $5::varchar,
    $6::varchar,
    $7::varchar,
    $8,
    $9,
    $10::jsonb,
    $11::text,
    $12::text,
    $13::text[],
    $14::text,
    $15::text,
    $16::text,
    $17::text,
    $18
)
RETURNING id, installation_id, external_id, provider, key_ciphertext, key_prefix, key_suffix, key_fingerprint, name, last_used_at, created_at, updated_at, deleted_at, created_by, base_url, model_aliases, identity_header_name, identity_header_format, auth_type, auth_account, auth_user, deleted_by, forwarded_client_headers, baggage_header
`

type CreateExternalAPIKeyParams struct {
	InstallationID         uuid.UUID
	ExternalID             string
	Provider               string
	KeyCiphertext          []byte
	KeyPrefix              string
	KeySuffix              string
	KeyFingerprint         string
	Name                   *string
	BaseURL                *string
	ModelAliases           []byte
	IdentityHeaderName     *string
	IdentityHeaderFormat   *string
	ForwardedClientHeaders []string
	BaggageHeader          *string
	AuthType               string
	AuthAccount            *string
	AuthUser               *string
	CreatedBy              *string
}

// Creates a new external API key for an installation. The unique index on
// (installation_id, provider) WHERE deleted_at IS NULL enforces one key per
// provider; callers must soft-delete the existing key before inserting.
//
//	INSERT INTO router.model_router_external_api_keys (
//	    installation_id,
//	    external_id,
//	    provider,
//	    key_ciphertext,
//	    key_prefix,
//	    key_suffix,
//	    key_fingerprint,
//	    name,
//	    base_url,
//	    model_aliases,
//	    identity_header_name,
//	    identity_header_format,
//	    forwarded_client_headers,
//	    baggage_header,
//	    auth_type,
//	    auth_account,
//	    auth_user,
//	    created_by
//	)
//	VALUES (
//	    $1::uuid,
//	    $2::varchar,
//	    $3::varchar,
//	    $4::bytea,
//	    $5::varchar,
//	    $6::varchar,
//	    $7::varchar,
//	    $8,
//	    $9,
//	    $10::jsonb,
//	    $11::text,
//	    $12::text,
//	    $13::text[],
//	    $14::text,
//	    $15::text,
//	    $16::text,
//	    $17::text,
//	    $18
//	)
//	RETURNING id, installation_id, external_id, provider, key_ciphertext, key_prefix, key_suffix, key_fingerprint, name, last_used_at, created_at, updated_at, deleted_at, created_by, base_url, model_aliases, identity_header_name, identity_header_format, auth_type, auth_account, auth_user, deleted_by, forwarded_client_headers, baggage_header
func (q *Queries) CreateExternalAPIKey(ctx context.Context, arg CreateExternalAPIKeyParams) (RouterModelRouterExternalAPIKey, error) {
	row := q.db.QueryRow(ctx, createExternalAPIKey,
		arg.InstallationID,
		arg.ExternalID,
		arg.Provider,
		arg.KeyCiphertext,
		arg.KeyPrefix,
		arg.KeySuffix,
		arg.KeyFingerprint,
		arg.Name,
		arg.BaseURL,
		arg.ModelAliases,
		arg.IdentityHeaderName,
		arg.IdentityHeaderFormat,
		arg.ForwardedClientHeaders,
		arg.BaggageHeader,
		arg.AuthType,
		arg.AuthAccount,
		arg.AuthUser,
		arg.CreatedBy,
	)
	var i RouterModelRouterExternalAPIKey
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.ExternalID,
		&i.Provider,
		&i.KeyCiphertext,
		&i.KeyPrefix,
		&i.KeySuffix,
		&i.KeyFingerprint,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.BaseURL,
		&i.ModelAliases,
		&i.IdentityHeaderName,
		&i.IdentityHeaderFormat,
		&i.AuthType,
		&i.AuthAccount,
		&i.AuthUser,
		&i.DeletedBy,
		&i.ForwardedClientHeaders,
		&i.BaggageHeader,
	)
	return i, err
}

const getActiveExternalAPIKeysForInstallation = `-- name: GetActiveExternalAPIKeysForInstallation :many
SELECT id, installation_id, external_id, provider, key_ciphertext, key_prefix, key_suffix, key_fingerprint, name, last_used_at, created_at, updated_at, deleted_at, created_by, base_url, model_aliases, identity_header_name, identity_header_format, auth_type, auth_account, auth_user, deleted_by, forwarded_client_headers, baggage_header
FROM router.model_router_external_api_keys
WHERE installation_id = $1::uuid
  AND deleted_at IS NULL
ORDER BY provider, created_at DESC
`

// Returns all active external API keys for an installation. Used by the auth
// cache to populate the ExternalKeys map on cache miss.
//
//	SELECT id, installation_id, external_id, provider, key_ciphertext, key_prefix, key_suffix, key_fingerprint, name, last_used_at, created_at, updated_at, deleted_at, created_by, base_url, model_aliases, identity_header_name, identity_header_format, auth_type, auth_account, auth_user, deleted_by, forwarded_client_headers, baggage_header
//	FROM router.model_router_external_api_keys
//	WHERE installation_id = $1::uuid
//	  AND deleted_at IS NULL
//	ORDER BY provider, created_at DESC
func (q *Queries) GetActiveExternalAPIKeysForInstallation(ctx context.Context, installationID uuid.UUID) ([]RouterModelRouterExternalAPIKey, error) {
	rows, err := q.db.Query(ctx, getActiveExternalAPIKeysForInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterExternalAPIKey
	for rows.Next() {
		var i RouterModelRouterExternalAPIKey
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.ExternalID,
			&i.Provider,
			&i.KeyCiphertext,
			&i.KeyPrefix,
			&i.KeySuffix,
			&i.KeyFingerprint,
			&i.Name,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.BaseURL,
			&i.ModelAliases,
			&i.IdentityHeaderName,
			&i.IdentityHeaderFormat,
			&i.AuthType,
			&i.AuthAccount,
			&i.AuthUser,
			&i.DeletedBy,
			&i.ForwardedClientHeaders,
			&i.BaggageHeader,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExternalAPIKeyUsed = `-- name: MarkExternalAPIKeyUsed :exec
UPDATE router.model_router_external_api_keys
SET last_used_at = NOW()
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

// Fire-and-forget update after successful upstream call.
//
//	UPDATE router.model_router_external_api_keys
//	SET last_used_at = NOW()
//	WHERE id = $1::uuid
//	  AND deleted_at IS NULL
func (q *Queries) MarkExternalAPIKeyUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markExternalAPIKeyUsed, id)
	return err
}

const softDeleteExternalAPIKey = `-- name: SoftDeleteExternalAPIKey :exec
UPDATE router.model_router_external_api_keys
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1::uuid
  AND installation_id = $2::uuid
  AND deleted_at IS NULL
`

type SoftDeleteExternalAPIKeyParams struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
}

// Soft-deletes an external API key. Cross-tenant safe via installation_id predicate.
//
//	UPDATE router.model_router_external_api_keys
//	SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1::uuid
//	  AND installation_id = $2::uuid
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteExternalAPIKey(ctx context.Context, arg SoftDeleteExternalAPIKeyParams) error {
	_, err := q.db.Exec(ctx, softDeleteExternalAPIKey, arg.ID, arg.InstallationID)
	return err
}

const softDeleteExternalAPIKeyByProvider = `-- name: SoftDeleteExternalAPIKeyByProvider :exec
UPDATE router.model_router_external_api_keys
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE installation_id = $1::uuid
  AND provider = $2::varchar
  AND deleted_at IS NULL
`

type SoftDeleteExternalAPIKeyByProviderParams struct {
	InstallationID uuid.UUID
	Provider       string
}

// Soft-deletes the existing key for a provider before upsert.
//
//	UPDATE router.model_router_external_api_keys
//	SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
//	WHERE installation_id = $1::uuid
//	  AND provider = $2::varchar
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteExternalAPIKeyByProvider(ctx context.Context, arg SoftDeleteExternalAPIKeyByProviderParams) error {
	_, err := q.db.Exec(ctx, softDeleteExternalAPIKeyByProvider, arg.InstallationID, arg.Provider)
	return err
}

const updateExternalAPIKeyModelAliases = `-- name: UpdateExternalAPIKeyModelAliases :one
UPDATE router.model_router_external_api_keys
SET model_aliases = $1::jsonb, updated_at = CURRENT_TIMESTAMP
WHERE id = $2::uuid
  AND installation_id = $3::uuid
  AND deleted_at IS NULL
RETURNING id, installation_id, external_id, provider, key_ciphertext, key_prefix, key_suffix, key_fingerprint, name, last_used_at, created_at, updated_at, deleted_at, created_by, base_url, model_aliases, identity_header_name, identity_header_format, auth_type, auth_account, auth_user, deleted_by, forwarded_client_headers, baggage_header
`

type UpdateExternalAPIKeyModelAliasesParams struct {
	ModelAliases   []byte
	ID             uuid.UUID
	InstallationID uuid.UUID
}

// Replaces one key's model alias map without touching the stored secret, so the
// dashboard can edit aliases without the operator re-entering the credential.
// Cross-tenant safe via installation_id predicate.
//
//	UPDATE router.model_router_external_api_keys
//	SET model_aliases = $1::jsonb, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $2::uuid
//	  AND installation_id = $3::uuid
//	  AND deleted_at IS NULL
//	RETURNING id, installation_id, external_id, provider, key_ciphertext, key_prefix, key_suffix, key_fingerprint, name, last_used_at, created_at, updated_at, deleted_at, created_by, base_url, model_aliases, identity_header_name, identity_header_format, auth_type, auth_account, auth_user, deleted_by, forwarded_client_headers, baggage_header
func (q *Queries) UpdateExternalAPIKeyModelAliases(ctx context.Context, arg UpdateExternalAPIKeyModelAliasesParams) (RouterModelRouterExternalAPIKey, error) {
	row := q.db.QueryRow(ctx, updateExternalAPIKeyModelAliases, arg.ModelAliases, arg.ID, arg.InstallationID)
	var i RouterModelRouterExternalAPIKey
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.ExternalID,
		&i.Provider,
		&i.KeyCiphertext,
		&i.KeyPrefix,
		&i.KeySuffix,
		&i.KeyFingerprint,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.BaseURL,
		&i.ModelAliases,
		&i.IdentityHeaderName,
		&i.IdentityHeaderFormat,
		&i.AuthType,
		&i.AuthAccount,
		&i.AuthUser,
		&i.DeletedBy,
		&i.ForwardedClientHeaders,
		&i.BaggageHeader,
	)
	return i, err
}
