// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_subscription_accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteModelRouterSubscriptionAccount = `-- name: DeleteModelRouterSubscriptionAccount :execrows
DELETE FROM router.model_router_subscription_accounts
WHERE id = $1::uuid AND api_key_id = $2::uuid
`

type DeleteModelRouterSubscriptionAccountParams struct {
	ID       uuid.UUID
	APIKeyID uuid.UUID
}

// DeleteModelRouterSubscriptionAccount
//
//	DELETE FROM router.model_router_subscription_accounts
//	WHERE id = $1::uuid AND api_key_id = $2::uuid
func (q *Queries) DeleteModelRouterSubscriptionAccount(ctx context.Context, arg DeleteModelRouterSubscriptionAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModelRouterSubscriptionAccount, arg.ID, arg.APIKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getModelRouterSubscriptionCredentialRecord = `-- name: GetModelRouterSubscriptionCredentialRecord :one
SELECT external_account_id,
       provider,
       refresh_token_ciphertext,
       access_token_ciphertext,
       access_token_expires_at,
       token_refresh_version,
       enabled,
       cooldown_until
FROM router.model_router_subscription_accounts
WHERE id = $1::uuid AND api_key_id = $2::uuid
`

type GetModelRouterSubscriptionCredentialRecordParams struct {
	ID       uuid.UUID
	APIKeyID uuid.UUID
}

type GetModelRouterSubscriptionCredentialRecordRow struct {
	ExternalAccountID      string
	Provider               string
	RefreshTokenCiphertext []byte
	AccessTokenCiphertext  []byte
	AccessTokenExpiresAt   pgtype.Timestamp
	TokenRefreshVersion    int64
	Enabled                bool
	CooldownUntil          pgtype.Timestamp
}

// Load encrypted credentials and the refresh version used for optimistic CAS.
// The auth service decrypts the ciphertexts before returning them to Runtime.
//
//	SELECT external_account_id,
//	       provider,
//	       refresh_token_ciphertext,
//	       access_token_ciphertext,
//	       access_token_expires_at,
//	       token_refresh_version,
//	       enabled,
//	       cooldown_until
//	FROM router.model_router_subscription_accounts
//	WHERE id = $1::uuid AND api_key_id = $2::uuid
func (q *Queries) GetModelRouterSubscriptionCredentialRecord(ctx context.Context, arg GetModelRouterSubscriptionCredentialRecordParams) (GetModelRouterSubscriptionCredentialRecordRow, error) {
	row := q.db.QueryRow(ctx, getModelRouterSubscriptionCredentialRecord, arg.ID, arg.APIKeyID)
	var i GetModelRouterSubscriptionCredentialRecordRow
	err := row.Scan(
		&i.ExternalAccountID,
		&i.Provider,
		&i.RefreshTokenCiphertext,
		&i.AccessTokenCiphertext,
		&i.AccessTokenExpiresAt,
		&i.TokenRefreshVersion,
		&i.Enabled,
		&i.CooldownUntil,
	)
	return i, err
}

const listModelRouterSubscriptionAccounts = `-- name: ListModelRouterSubscriptionAccounts :many
SELECT id,
       api_key_id,
       provider,
       external_account_id,
       refresh_token_ciphertext,
       enabled,
       cooldown_until,
       created_at,
       updated_at
FROM router.model_router_subscription_accounts
WHERE api_key_id = $1::uuid
ORDER BY provider, created_at
`

type ListModelRouterSubscriptionAccountsRow struct {
	ID                     uuid.UUID
	APIKeyID               uuid.UUID
	Provider               string
	ExternalAccountID      string
	RefreshTokenCiphertext []byte
	Enabled                bool
	CooldownUntil          pgtype.Timestamp
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
}

// Account state is scoped by api_key_id so a router key can never manage another
// user's subscription account.
//
//	SELECT id,
//	       api_key_id,
//	       provider,
//	       external_account_id,
//	       refresh_token_ciphertext,
//	       enabled,
//	       cooldown_until,
//	       created_at,
//	       updated_at
//	FROM router.model_router_subscription_accounts
//	WHERE api_key_id = $1::uuid
//	ORDER BY provider, created_at
func (q *Queries) ListModelRouterSubscriptionAccounts(ctx context.Context, apiKeyID uuid.UUID) ([]ListModelRouterSubscriptionAccountsRow, error) {
	rows, err := q.db.Query(ctx, listModelRouterSubscriptionAccounts, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelRouterSubscriptionAccountsRow
	for rows.Next() {
		var i ListModelRouterSubscriptionAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.APIKeyID,
			&i.Provider,
			&i.ExternalAccountID,
			&i.RefreshTokenCiphertext,
			&i.Enabled,
			&i.CooldownUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const persistModelRouterSubscriptionTokens = `-- name: PersistModelRouterSubscriptionTokens :execrows
UPDATE router.model_router_subscription_accounts
SET refresh_token_ciphertext = $1::bytea,
    access_token_ciphertext = $2::bytea,
    access_token_expires_at = $3::timestamp,
    token_refresh_lease_until = NULL,
    token_refresh_lease_id = NULL,
    token_refresh_version = token_refresh_version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $4::uuid
  AND api_key_id = $5::uuid
  AND enabled = TRUE
  AND token_refresh_lease_id = $6::uuid
  AND token_refresh_version = $7::bigint
`

type PersistModelRouterSubscriptionTokensParams struct {
	RefreshTokenCiphertext []byte
	AccessTokenCiphertext  []byte
	AccessTokenExpiresAt   pgtype.Timestamp
	ID                     uuid.UUID
	APIKeyID               uuid.UUID
	LeaseID                uuid.UUID
	ExpectedVersion        int64
}

// Persist a refresh result and publish its access token atomically. The lease
// ID fences stale refreshers and the version prevents lost refresh rotations.
//
//	UPDATE router.model_router_subscription_accounts
//	SET refresh_token_ciphertext = $1::bytea,
//	    access_token_ciphertext = $2::bytea,
//	    access_token_expires_at = $3::timestamp,
//	    token_refresh_lease_until = NULL,
//	    token_refresh_lease_id = NULL,
//	    token_refresh_version = token_refresh_version + 1,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $4::uuid
//	  AND api_key_id = $5::uuid
//	  AND enabled = TRUE
//	  AND token_refresh_lease_id = $6::uuid
//	  AND token_refresh_version = $7::bigint
func (q *Queries) PersistModelRouterSubscriptionTokens(ctx context.Context, arg PersistModelRouterSubscriptionTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, persistModelRouterSubscriptionTokens,
		arg.RefreshTokenCiphertext,
		arg.AccessTokenCiphertext,
		arg.AccessTokenExpiresAt,
		arg.ID,
		arg.APIKeyID,
		arg.LeaseID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseModelRouterSubscriptionRefreshLease = `-- name: ReleaseModelRouterSubscriptionRefreshLease :execrows
UPDATE router.model_router_subscription_accounts
SET token_refresh_lease_until = NULL,
    token_refresh_lease_id = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1::uuid
  AND api_key_id = $2::uuid
  AND token_refresh_lease_id = $3::uuid
`

type ReleaseModelRouterSubscriptionRefreshLeaseParams struct {
	ID       uuid.UUID
	APIKeyID uuid.UUID
	LeaseID  uuid.UUID
}

// Release a refresh lease only when this holder still owns it.
//
//	UPDATE router.model_router_subscription_accounts
//	SET token_refresh_lease_until = NULL,
//	    token_refresh_lease_id = NULL,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1::uuid
//	  AND api_key_id = $2::uuid
//	  AND token_refresh_lease_id = $3::uuid
func (q *Queries) ReleaseModelRouterSubscriptionRefreshLease(ctx context.Context, arg ReleaseModelRouterSubscriptionRefreshLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseModelRouterSubscriptionRefreshLease, arg.ID, arg.APIKeyID, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryAcquireModelRouterSubscriptionRefreshLease = `-- name: TryAcquireModelRouterSubscriptionRefreshLease :execrows
UPDATE router.model_router_subscription_accounts
SET token_refresh_lease_until = $1::timestamp,
    token_refresh_lease_id = $2::uuid,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3::uuid
  AND api_key_id = $4::uuid
  AND enabled = TRUE
  AND (cooldown_until IS NULL OR cooldown_until <= $5::timestamp)
  AND (token_refresh_lease_until IS NULL OR token_refresh_lease_until <= $5::timestamp)
`

type TryAcquireModelRouterSubscriptionRefreshLeaseParams struct {
	LeaseUntil pgtype.Timestamp
	LeaseID    uuid.UUID
	ID         uuid.UUID
	APIKeyID   uuid.UUID
	Now        pgtype.Timestamp
}

// Try to reserve one account for a cross-replica token refresh. The lease ID
// fences stale holders after a lease expires and is taken over.
//
//	UPDATE router.model_router_subscription_accounts
//	SET token_refresh_lease_until = $1::timestamp,
//	    token_refresh_lease_id = $2::uuid,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $3::uuid
//	  AND api_key_id = $4::uuid
//	  AND enabled = TRUE
//	  AND (cooldown_until IS NULL OR cooldown_until <= $5::timestamp)
//	  AND (token_refresh_lease_until IS NULL OR token_refresh_lease_until <= $5::timestamp)
func (q *Queries) TryAcquireModelRouterSubscriptionRefreshLease(ctx context.Context, arg TryAcquireModelRouterSubscriptionRefreshLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryAcquireModelRouterSubscriptionRefreshLease,
		arg.LeaseUntil,
		arg.LeaseID,
		arg.ID,
		arg.APIKeyID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterSubscriptionAccountCooldown = `-- name: UpdateModelRouterSubscriptionAccountCooldown :execrows
UPDATE router.model_router_subscription_accounts
SET cooldown_until = $1::timestamp,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2::uuid
  AND api_key_id = $3::uuid
  AND enabled = TRUE
`

type UpdateModelRouterSubscriptionAccountCooldownParams struct {
	CooldownUntil pgtype.Timestamp
	ID            uuid.UUID
	APIKeyID      uuid.UUID
}

// A stale replica must not turn an operator-disabled account back on while
// persisting a quota cooldown.
//
//	UPDATE router.model_router_subscription_accounts
//	SET cooldown_until = $1::timestamp,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $2::uuid
//	  AND api_key_id = $3::uuid
//	  AND enabled = TRUE
func (q *Queries) UpdateModelRouterSubscriptionAccountCooldown(ctx context.Context, arg UpdateModelRouterSubscriptionAccountCooldownParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterSubscriptionAccountCooldown, arg.CooldownUntil, arg.ID, arg.APIKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterSubscriptionAccountState = `-- name: UpdateModelRouterSubscriptionAccountState :execrows
UPDATE router.model_router_subscription_accounts
SET enabled = $1::boolean,
    cooldown_until = $2::timestamp,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3::uuid AND api_key_id = $4::uuid
`

type UpdateModelRouterSubscriptionAccountStateParams struct {
	Enabled       bool
	CooldownUntil pgtype.Timestamp
	ID            uuid.UUID
	APIKeyID      uuid.UUID
}

// UpdateModelRouterSubscriptionAccountState
//
//	UPDATE router.model_router_subscription_accounts
//	SET enabled = $1::boolean,
//	    cooldown_until = $2::timestamp,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $3::uuid AND api_key_id = $4::uuid
func (q *Queries) UpdateModelRouterSubscriptionAccountState(ctx context.Context, arg UpdateModelRouterSubscriptionAccountStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterSubscriptionAccountState,
		arg.Enabled,
		arg.CooldownUntil,
		arg.ID,
		arg.APIKeyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterSubscriptionRefreshToken = `-- name: UpdateModelRouterSubscriptionRefreshToken :execrows
UPDATE router.model_router_subscription_accounts
SET refresh_token_ciphertext = $1::bytea,
    access_token_ciphertext = NULL,
    access_token_expires_at = NULL,
    token_refresh_lease_until = NULL,
    token_refresh_lease_id = NULL,
    token_refresh_version = token_refresh_version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2::uuid AND api_key_id = $3::uuid
`

type UpdateModelRouterSubscriptionRefreshTokenParams struct {
	RefreshTokenCiphertext []byte
	ID                     uuid.UUID
	APIKeyID               uuid.UUID
}

// UpdateModelRouterSubscriptionRefreshToken
//
//	UPDATE router.model_router_subscription_accounts
//	SET refresh_token_ciphertext = $1::bytea,
//	    access_token_ciphertext = NULL,
//	    access_token_expires_at = NULL,
//	    token_refresh_lease_until = NULL,
//	    token_refresh_lease_id = NULL,
//	    token_refresh_version = token_refresh_version + 1,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $2::uuid AND api_key_id = $3::uuid
func (q *Queries) UpdateModelRouterSubscriptionRefreshToken(ctx context.Context, arg UpdateModelRouterSubscriptionRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterSubscriptionRefreshToken, arg.RefreshTokenCiphertext, arg.ID, arg.APIKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertModelRouterSubscriptionAccount = `-- name: UpsertModelRouterSubscriptionAccount :one
INSERT INTO router.model_router_subscription_accounts (
  api_key_id, provider, external_account_id, refresh_token_ciphertext
)
VALUES ($1::uuid, $2::varchar, $3::varchar, $4::bytea)
ON CONFLICT (api_key_id, provider, external_account_id)
DO UPDATE SET
  refresh_token_ciphertext = EXCLUDED.refresh_token_ciphertext,
  enabled = TRUE,
  cooldown_until = NULL,
  access_token_ciphertext = NULL,
  access_token_expires_at = NULL,
  token_refresh_lease_until = NULL,
  token_refresh_lease_id = NULL,
  token_refresh_version = model_router_subscription_accounts.token_refresh_version + 1,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, api_key_id, provider, external_account_id, refresh_token_ciphertext, enabled, cooldown_until, created_at, updated_at, access_token_ciphertext, access_token_expires_at, token_refresh_lease_until, token_refresh_lease_id, token_refresh_version
`

type UpsertModelRouterSubscriptionAccountParams struct {
	APIKeyID               uuid.UUID
	Provider               string
	ExternalAccountID      string
	RefreshTokenCiphertext []byte
}

// UpsertModelRouterSubscriptionAccount
//
//	INSERT INTO router.model_router_subscription_accounts (
//	  api_key_id, provider, external_account_id, refresh_token_ciphertext
//	)
//	VALUES ($1::uuid, $2::varchar, $3::varchar, $4::bytea)
//	ON CONFLICT (api_key_id, provider, external_account_id)
//	DO UPDATE SET
//	  refresh_token_ciphertext = EXCLUDED.refresh_token_ciphertext,
//	  enabled = TRUE,
//	  cooldown_until = NULL,
//	  access_token_ciphertext = NULL,
//	  access_token_expires_at = NULL,
//	  token_refresh_lease_until = NULL,
//	  token_refresh_lease_id = NULL,
//	  token_refresh_version = model_router_subscription_accounts.token_refresh_version + 1,
//	  updated_at = CURRENT_TIMESTAMP
//	RETURNING id, api_key_id, provider, external_account_id, refresh_token_ciphertext, enabled, cooldown_until, created_at, updated_at, access_token_ciphertext, access_token_expires_at, token_refresh_lease_until, token_refresh_lease_id, token_refresh_version
func (q *Queries) UpsertModelRouterSubscriptionAccount(ctx context.Context, arg UpsertModelRouterSubscriptionAccountParams) (RouterModelRouterSubscriptionAccount, error) {
	row := q.db.QueryRow(ctx, upsertModelRouterSubscriptionAccount,
		arg.APIKeyID,
		arg.Provider,
		arg.ExternalAccountID,
		arg.RefreshTokenCiphertext,
	)
	var i RouterModelRouterSubscriptionAccount
	err := row.Scan(
		&i.ID,
		&i.APIKeyID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.RefreshTokenCiphertext,
		&i.Enabled,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessTokenCiphertext,
		&i.AccessTokenExpiresAt,
		&i.TokenRefreshLeaseUntil,
		&i.TokenRefreshLeaseID,
		&i.TokenRefreshVersion,
	)
	return i, err
}
