// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_installations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createModelRouterInstallation = `-- name: CreateModelRouterInstallation :one
INSERT INTO router.model_router_installations (
    external_id,
    name,
    created_by
)
VALUES (
    $1::varchar,
    $2::varchar,
    $3
)
RETURNING id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive
`

type CreateModelRouterInstallationParams struct {
	ExternalID string
	Name       string
	CreatedBy  *string
}

// CreateModelRouterInstallation
//
//	INSERT INTO router.model_router_installations (
//	    external_id,
//	    name,
//	    created_by
//	)
//	VALUES (
//	    $1::varchar,
//	    $2::varchar,
//	    $3
//	)
//	RETURNING id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive
func (q *Queries) CreateModelRouterInstallation(ctx context.Context, arg CreateModelRouterInstallationParams) (RouterModelRouterInstallation, error) {
	row := q.db.QueryRow(ctx, createModelRouterInstallation, arg.ExternalID, arg.Name, arg.CreatedBy)
	var i RouterModelRouterInstallation
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.ExcludedModels,
		&i.ExcludedProviders,
		&i.RoutingQualityWeight,
		&i.UsageBypassEnabled,
		&i.UsageBypassThreshold,
		&i.PreferredModels,
		&i.SubscriptionRoutingDisabled,
		&i.RoutingStrategy,
		&i.RoutingRolloutID,
		&i.PolicyShadowStrategy,
		&i.PolicyDebugEnabled,
		&i.PolicyHeaderOverridesEnabled,
		&i.PolicyRoutingIntent,
		&i.AiTrainingAllowed,
		&i.ByokEnabled,
		&i.ContentCaptureMode,
		&i.HideTerminalSurfaces,
		&i.AllowedModels,
		&i.FirstRequestServedAt,
		&i.FlagOverrides,
		&i.ModelsWhenSubscriptionActive,
		&i.ModelsWhenSubscriptionInactive,
	)
	return i, err
}

const getModelRouterInstallation = `-- name: GetModelRouterInstallation :one
SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive
FROM router.model_router_installations
WHERE id = $1::uuid
  AND external_id = $2::varchar
  AND deleted_at IS NULL
`

type GetModelRouterInstallationParams struct {
	ID         uuid.UUID
	ExternalID string
}

// Gets an installation by id, scoped to an external_id to prevent cross-tenant access.
//
//	SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive
//	FROM router.model_router_installations
//	WHERE id = $1::uuid
//	  AND external_id = $2::varchar
//	  AND deleted_at IS NULL
func (q *Queries) GetModelRouterInstallation(ctx context.Context, arg GetModelRouterInstallationParams) (RouterModelRouterInstallation, error) {
	row := q.db.QueryRow(ctx, getModelRouterInstallation, arg.ID, arg.ExternalID)
	var i RouterModelRouterInstallation
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.ExcludedModels,
		&i.ExcludedProviders,
		&i.RoutingQualityWeight,
		&i.UsageBypassEnabled,
		&i.UsageBypassThreshold,
		&i.PreferredModels,
		&i.SubscriptionRoutingDisabled,
		&i.RoutingStrategy,
		&i.RoutingRolloutID,
		&i.PolicyShadowStrategy,
		&i.PolicyDebugEnabled,
		&i.PolicyHeaderOverridesEnabled,
		&i.PolicyRoutingIntent,
		&i.AiTrainingAllowed,
		&i.ByokEnabled,
		&i.ContentCaptureMode,
		&i.HideTerminalSurfaces,
		&i.AllowedModels,
		&i.FirstRequestServedAt,
		&i.FlagOverrides,
		&i.ModelsWhenSubscriptionActive,
		&i.ModelsWhenSubscriptionInactive,
	)
	return i, err
}

const listModelRouterInstallationsForExternalID = `-- name: ListModelRouterInstallationsForExternalID :many
SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive
FROM router.model_router_installations
WHERE external_id = $1::varchar
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

// ListModelRouterInstallationsForExternalID
//
//	SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive
//	FROM router.model_router_installations
//	WHERE external_id = $1::varchar
//	  AND deleted_at IS NULL
//	ORDER BY created_at DESC
func (q *Queries) ListModelRouterInstallationsForExternalID(ctx context.Context, externalID string) ([]RouterModelRouterInstallation, error) {
	rows, err := q.db.Query(ctx, listModelRouterInstallationsForExternalID, externalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterInstallation
	for rows.Next() {
		var i RouterModelRouterInstallation
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.ExcludedModels,
			&i.ExcludedProviders,
			&i.RoutingQualityWeight,
			&i.UsageBypassEnabled,
			&i.UsageBypassThreshold,
			&i.PreferredModels,
			&i.SubscriptionRoutingDisabled,
			&i.RoutingStrategy,
			&i.RoutingRolloutID,
			&i.PolicyShadowStrategy,
			&i.PolicyDebugEnabled,
			&i.PolicyHeaderOverridesEnabled,
			&i.PolicyRoutingIntent,
			&i.AiTrainingAllowed,
			&i.ByokEnabled,
			&i.ContentCaptureMode,
			&i.HideTerminalSurfaces,
			&i.AllowedModels,
			&i.FirstRequestServedAt,
			&i.FlagOverrides,
			&i.ModelsWhenSubscriptionActive,
			&i.ModelsWhenSubscriptionInactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markModelRouterInstallationFirstRequestServed = `-- name: MarkModelRouterInstallationFirstRequestServed :exec
UPDATE router.model_router_installations
SET first_request_served_at = NOW()
WHERE id = $1::uuid
  AND deleted_at IS NULL
  AND first_request_served_at IS NULL
`

// Stamps first_request_served_at the first time this installation routes a
// request. WHERE IS NULL makes the update a no-op after the first write, so
// the timestamp records the *first* request and rotation never resets it.
//
//	UPDATE router.model_router_installations
//	SET first_request_served_at = NOW()
//	WHERE id = $1::uuid
//	  AND deleted_at IS NULL
//	  AND first_request_served_at IS NULL
func (q *Queries) MarkModelRouterInstallationFirstRequestServed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markModelRouterInstallationFirstRequestServed, id)
	return err
}

const softDeleteModelRouterInstallation = `-- name: SoftDeleteModelRouterInstallation :exec
UPDATE router.model_router_installations
SET deleted_at = NOW()
WHERE id = $1::uuid
  AND external_id = $2::varchar
  AND deleted_at IS NULL
`

type SoftDeleteModelRouterInstallationParams struct {
	ID         uuid.UUID
	ExternalID string
}

// Soft-deletes an installation, scoped to an external_id to prevent cross-tenant deletes.
//
//	UPDATE router.model_router_installations
//	SET deleted_at = NOW()
//	WHERE id = $1::uuid
//	  AND external_id = $2::varchar
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteModelRouterInstallation(ctx context.Context, arg SoftDeleteModelRouterInstallationParams) error {
	_, err := q.db.Exec(ctx, softDeleteModelRouterInstallation, arg.ID, arg.ExternalID)
	return err
}

const updateModelRouterInstallationAllowedModels = `-- name: UpdateModelRouterInstallationAllowedModels :execrows
UPDATE router.model_router_installations
SET allowed_models = $1::text[],
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationAllowedModelsParams struct {
	AllowedModels []string
	ID            uuid.UUID
	ExternalID    string
}

// Replaces the per-installation positive model allowlist, scoped to an
// external_id to prevent cross-tenant updates. Empty array means "no
// restriction" (all models routable), NOT "no models". Bumps updated_at so
// dashboards see the change.
//
//	UPDATE router.model_router_installations
//	SET allowed_models = $1::text[],
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationAllowedModels(ctx context.Context, arg UpdateModelRouterInstallationAllowedModelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationAllowedModels, arg.AllowedModels, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationContentCaptureMode = `-- name: UpdateModelRouterInstallationContentCaptureMode :execrows
UPDATE router.model_router_installations
SET content_capture_mode = $1,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationContentCaptureModeParams struct {
	ContentCaptureMode *string
	ID                 uuid.UUID
	ExternalID         string
}

// Sets the per-installation capture ceiling ('off', 'hashed', or 'full'), scoped
// to an external_id to prevent cross-tenant updates. NULL clears the override.
//
//	UPDATE router.model_router_installations
//	SET content_capture_mode = $1,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationContentCaptureMode(ctx context.Context, arg UpdateModelRouterInstallationContentCaptureModeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationContentCaptureMode, arg.ContentCaptureMode, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationExcludedModels = `-- name: UpdateModelRouterInstallationExcludedModels :execrows
UPDATE router.model_router_installations
SET excluded_models = $1::text[],
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationExcludedModelsParams struct {
	ExcludedModels []string
	ID             uuid.UUID
	ExternalID     string
}

// Replaces the per-installation model exclusion list, scoped to an external_id
// to prevent cross-tenant updates. Empty array means "no exclusion". Bumps
// updated_at so dashboards see the change.
//
//	UPDATE router.model_router_installations
//	SET excluded_models = $1::text[],
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationExcludedModels(ctx context.Context, arg UpdateModelRouterInstallationExcludedModelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationExcludedModels, arg.ExcludedModels, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationExcludedProviders = `-- name: UpdateModelRouterInstallationExcludedProviders :execrows
UPDATE router.model_router_installations
SET excluded_providers = $1::text[],
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationExcludedProvidersParams struct {
	ExcludedProviders []string
	ID                uuid.UUID
	ExternalID        string
}

// Replaces the per-installation provider exclusion list, scoped to an
// external_id to prevent cross-tenant updates. Empty array means "no
// exclusion". Bumps updated_at so dashboards see the change.
//
//	UPDATE router.model_router_installations
//	SET excluded_providers = $1::text[],
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationExcludedProviders(ctx context.Context, arg UpdateModelRouterInstallationExcludedProvidersParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationExcludedProviders, arg.ExcludedProviders, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationFlagOverrides = `-- name: UpdateModelRouterInstallationFlagOverrides :execrows
UPDATE router.model_router_installations
SET flag_overrides = $1::jsonb,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationFlagOverridesParams struct {
	FlagOverrides []byte
	ID            uuid.UUID
	ExternalID    string
}

// Replaces the per-installation behavioral flag override set, scoped to an
// external_id to prevent cross-tenant updates. The payload is the whole sparse
// object, not a delta: callers read-modify-write so clearing an override is
// expressed by omitting its key. Keys are validated against internal/flags'
// registry before this runs. Bumps updated_at so dashboards see the change.
//
//	UPDATE router.model_router_installations
//	SET flag_overrides = $1::jsonb,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationFlagOverrides(ctx context.Context, arg UpdateModelRouterInstallationFlagOverridesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationFlagOverrides, arg.FlagOverrides, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationHideTerminalSurfaces = `-- name: UpdateModelRouterInstallationHideTerminalSurfaces :execrows
UPDATE router.model_router_installations
SET hide_terminal_surfaces = $1::boolean,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationHideTerminalSurfacesParams struct {
	HideTerminalSurfaces bool
	ID                   uuid.UUID
	ExternalID           string
}

// Toggles hiding the router's terminal surfaces (routing marker, feedback
// footer, statusline) for the installation, scoped to an external_id to
// prevent cross-tenant updates. Requests route identically; only what is
// rendered in the caller's terminal changes.
//
//	UPDATE router.model_router_installations
//	SET hide_terminal_surfaces = $1::boolean,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationHideTerminalSurfaces(ctx context.Context, arg UpdateModelRouterInstallationHideTerminalSurfacesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationHideTerminalSurfaces, arg.HideTerminalSurfaces, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationRoutingPreference = `-- name: UpdateModelRouterInstallationRoutingPreference :execrows
UPDATE router.model_router_installations
SET routing_quality_weight = $1,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationRoutingPreferenceParams struct {
	RoutingQualityWeight *float64
	ID                   uuid.UUID
	ExternalID           string
}

// Sets the routing preference quality weight (a normalized fraction in [0, 1]),
// scoped to an external_id to prevent cross-tenant updates. NULL clears the
// preference so the scorer reverts to its tuned defaults.
//
//	UPDATE router.model_router_installations
//	SET routing_quality_weight = $1,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationRoutingPreference(ctx context.Context, arg UpdateModelRouterInstallationRoutingPreferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationRoutingPreference, arg.RoutingQualityWeight, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationSubscriptionRoutingDisabled = `-- name: UpdateModelRouterInstallationSubscriptionRoutingDisabled :execrows
UPDATE router.model_router_installations
SET subscription_routing_disabled = $1::boolean,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationSubscriptionRoutingDisabledParams struct {
	SubscriptionRoutingDisabled bool
	ID                          uuid.UUID
	ExternalID                  string
}

// Toggles subscription-aware routing for the installation, scoped to an
// external_id to prevent cross-tenant updates. When true, the scorer's
// subscription subsidy bonus is suppressed so routing decides on merits and
// non-Claude models compete fairly; the subscription credential is still
// forwarded for turns that route to Claude on their own merits.
//
//	UPDATE router.model_router_installations
//	SET subscription_routing_disabled = $1::boolean,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationSubscriptionRoutingDisabled(ctx context.Context, arg UpdateModelRouterInstallationSubscriptionRoutingDisabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationSubscriptionRoutingDisabled, arg.SubscriptionRoutingDisabled, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationUsageBypass = `-- name: UpdateModelRouterInstallationUsageBypass :execrows
UPDATE router.model_router_installations
SET usage_bypass_enabled = $1::boolean,
    usage_bypass_threshold = $2,
    updated_at = NOW()
WHERE id = $3::uuid
  AND external_id = $4::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationUsageBypassParams struct {
	UsageBypassEnabled   bool
	UsageBypassThreshold *float64
	ID                   uuid.UUID
	ExternalID           string
}

// Sets the subscription usage-bypass gate, scoped to an external_id to prevent
// cross-tenant updates. enabled toggles the gate; threshold is the [0, 1]
// utilization at/above which the gate disengages and normal routing takes over.
// A NULL threshold means "use the deployment default" at request time.
//
//	UPDATE router.model_router_installations
//	SET usage_bypass_enabled = $1::boolean,
//	    usage_bypass_threshold = $2,
//	    updated_at = NOW()
//	WHERE id = $3::uuid
//	  AND external_id = $4::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationUsageBypass(ctx context.Context, arg UpdateModelRouterInstallationUsageBypassParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationUsageBypass,
		arg.UsageBypassEnabled,
		arg.UsageBypassThreshold,
		arg.ID,
		arg.ExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
