// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: serving_admission.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getServingAdmissionClock = `-- name: GetServingAdmissionClock :one
SELECT clock_timestamp()::timestamptz AS admitted_at
`

// Use database wall time after acquiring the admission lock, not transaction-start time.
//
//	SELECT clock_timestamp()::timestamptz AS admitted_at
func (q *Queries) GetServingAdmissionClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getServingAdmissionClock)
	var admitted_at pgtype.Timestamptz
	err := row.Scan(&admitted_at)
	return admitted_at, err
}

const getServingConversationLock = `-- name: GetServingConversationLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// Serialize concurrent first admissions as well as existing bindings. Hash collisions only over-serialize.
//
//	SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
func (q *Queries) GetServingConversationLock(ctx context.Context, admissionLockKey string) error {
	_, err := q.db.Exec(ctx, getServingConversationLock, admissionLockKey)
	return err
}

const getServingCredentialForAdmission = `-- name: GetServingCredentialForAdmission :one
SELECT id, credential_subject_id, scope
FROM router.model_router_api_keys
WHERE id = $1::uuid AND installation_id = $2::uuid AND deleted_at IS NULL
FOR SHARE
`

type GetServingCredentialForAdmissionParams struct {
	APIKeyID       uuid.UUID
	InstallationID uuid.UUID
}

type GetServingCredentialForAdmissionRow struct {
	ID                  uuid.UUID
	CredentialSubjectID pgtype.UUID
	Scope               string
}

// Read the credential again after authentication so cache staleness cannot bypass revocation.
//
//	SELECT id, credential_subject_id, scope
//	FROM router.model_router_api_keys
//	WHERE id = $1::uuid AND installation_id = $2::uuid AND deleted_at IS NULL
//	FOR SHARE
func (q *Queries) GetServingCredentialForAdmission(ctx context.Context, arg GetServingCredentialForAdmissionParams) (GetServingCredentialForAdmissionRow, error) {
	row := q.db.QueryRow(ctx, getServingCredentialForAdmission, arg.APIKeyID, arg.InstallationID)
	var i GetServingCredentialForAdmissionRow
	err := row.Scan(&i.ID, &i.CredentialSubjectID, &i.Scope)
	return i, err
}

const getServingInstallationForAdmission = `-- name: GetServingInstallationForAdmission :one
SELECT id FROM router.model_router_installations
WHERE id = $1::uuid AND deleted_at IS NULL
FOR SHARE
`

// Admission shares the installation lock; assignment changes take its exclusive lock first.
//
//	SELECT id FROM router.model_router_installations
//	WHERE id = $1::uuid AND deleted_at IS NULL
//	FOR SHARE
func (q *Queries) GetServingInstallationForAdmission(ctx context.Context, installationID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getServingInstallationForAdmission, installationID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getServingProfileAssignment = `-- name: GetServingProfileAssignment :one
SELECT profile_key, assignment_generation
FROM router.installation_profile_assignments
WHERE installation_id = $1::uuid
`

type GetServingProfileAssignmentRow struct {
	ProfileKey           pgtype.UUID
	AssignmentGeneration int64
}

// A missing assignment means follow the lane default; the installation lock protects absence too.
//
//	SELECT profile_key, assignment_generation
//	FROM router.installation_profile_assignments
//	WHERE installation_id = $1::uuid
func (q *Queries) GetServingProfileAssignment(ctx context.Context, installationID uuid.UUID) (GetServingProfileAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getServingProfileAssignment, installationID)
	var i GetServingProfileAssignmentRow
	err := row.Scan(&i.ProfileKey, &i.AssignmentGeneration)
	return i, err
}

const getServingSubjectForAdmission = `-- name: GetServingSubjectForAdmission :one
SELECT subject.id, subject.projection_complete, subject.internal_enrolled, subject.enrollment_generation, subject.created_at, subject.revoked_at, access.access_enabled
FROM router.credential_subjects subject
JOIN router.credential_subject_installations access ON access.subject_id = subject.id
WHERE subject.id = $1::uuid AND access.installation_id = $2::uuid
FOR SHARE OF subject, access
`

type GetServingSubjectForAdmissionParams struct {
	SubjectID      uuid.UUID
	InstallationID uuid.UUID
}

type GetServingSubjectForAdmissionRow struct {
	RouterCredentialSubject RouterCredentialSubject
	AccessEnabled           bool
}

// Subject state is authoritative on each admission, independent of client metadata.
//
//	SELECT subject.id, subject.projection_complete, subject.internal_enrolled, subject.enrollment_generation, subject.created_at, subject.revoked_at, access.access_enabled
//	FROM router.credential_subjects subject
//	JOIN router.credential_subject_installations access ON access.subject_id = subject.id
//	WHERE subject.id = $1::uuid AND access.installation_id = $2::uuid
//	FOR SHARE OF subject, access
func (q *Queries) GetServingSubjectForAdmission(ctx context.Context, arg GetServingSubjectForAdmissionParams) (GetServingSubjectForAdmissionRow, error) {
	row := q.db.QueryRow(ctx, getServingSubjectForAdmission, arg.SubjectID, arg.InstallationID)
	var i GetServingSubjectForAdmissionRow
	err := row.Scan(
		&i.RouterCredentialSubject.ID,
		&i.RouterCredentialSubject.ProjectionComplete,
		&i.RouterCredentialSubject.InternalEnrolled,
		&i.RouterCredentialSubject.EnrollmentGeneration,
		&i.RouterCredentialSubject.CreatedAt,
		&i.RouterCredentialSubject.RevokedAt,
		&i.AccessEnabled,
	)
	return i, err
}

const getServingSubjectProfileAssignments = `-- name: GetServingSubjectProfileAssignments :many
SELECT
    assignment_source,
    assignment_state,
    desired_generation,
    effective_generation,
    effective_assignment_state,
    desired_profile_key,
    effective_profile_key,
    router_acknowledgement_id,
    evidence_id,
    projection_attempts,
    projected_at,
    effective_at,
    last_failure_detail
FROM router.credential_subject_profile_assignments
WHERE subject_id = $1::uuid
  AND installation_id = $2::uuid
ORDER BY CASE assignment_source
    WHEN 'cohort' THEN 1
    WHEN 'subscriber_plan' THEN 2
    WHEN 'lane_default' THEN 3
    ELSE 4
END
FOR SHARE
`

type GetServingSubjectProfileAssignmentsParams struct {
	SubjectID      uuid.UUID
	InstallationID uuid.UUID
}

type GetServingSubjectProfileAssignmentsRow struct {
	AssignmentSource         string
	AssignmentState          string
	DesiredGeneration        int64
	EffectiveGeneration      int64
	EffectiveAssignmentState *string
	DesiredProfileKey        pgtype.UUID
	EffectiveProfileKey      pgtype.UUID
	RouterAcknowledgementID  uuid.UUID
	EvidenceID               string
	ProjectionAttempts       int32
	ProjectedAt              pgtype.Timestamptz
	EffectiveAt              pgtype.Timestamptz
	LastFailureDetail        *string
}

// Subject assignment rows are ordered by Router's public precedence after any installation override.
//
//	SELECT
//	    assignment_source,
//	    assignment_state,
//	    desired_generation,
//	    effective_generation,
//	    effective_assignment_state,
//	    desired_profile_key,
//	    effective_profile_key,
//	    router_acknowledgement_id,
//	    evidence_id,
//	    projection_attempts,
//	    projected_at,
//	    effective_at,
//	    last_failure_detail
//	FROM router.credential_subject_profile_assignments
//	WHERE subject_id = $1::uuid
//	  AND installation_id = $2::uuid
//	ORDER BY CASE assignment_source
//	    WHEN 'cohort' THEN 1
//	    WHEN 'subscriber_plan' THEN 2
//	    WHEN 'lane_default' THEN 3
//	    ELSE 4
//	END
//	FOR SHARE
func (q *Queries) GetServingSubjectProfileAssignments(ctx context.Context, arg GetServingSubjectProfileAssignmentsParams) ([]GetServingSubjectProfileAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getServingSubjectProfileAssignments, arg.SubjectID, arg.InstallationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServingSubjectProfileAssignmentsRow
	for rows.Next() {
		var i GetServingSubjectProfileAssignmentsRow
		if err := rows.Scan(
			&i.AssignmentSource,
			&i.AssignmentState,
			&i.DesiredGeneration,
			&i.EffectiveGeneration,
			&i.EffectiveAssignmentState,
			&i.DesiredProfileKey,
			&i.EffectiveProfileKey,
			&i.RouterAcknowledgementID,
			&i.EvidenceID,
			&i.ProjectionAttempts,
			&i.ProjectedAt,
			&i.EffectiveAt,
			&i.LastFailureDetail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionReleaseBinding = `-- name: GetSessionReleaseBinding :one
SELECT binding
FROM router.session_release_bindings
WHERE installation_id = $1::uuid
  AND credential_scope = $2::varchar
  AND conversation_digest = $3::bytea
`

type GetSessionReleaseBindingParams struct {
	InstallationID     uuid.UUID
	CredentialScope    string
	ConversationDigest []byte
}

// Exact scope lookup; never share a pseudo-session across all requests with no client ID.
//
//	SELECT binding
//	FROM router.session_release_bindings
//	WHERE installation_id = $1::uuid
//	  AND credential_scope = $2::varchar
//	  AND conversation_digest = $3::bytea
func (q *Queries) GetSessionReleaseBinding(ctx context.Context, arg GetSessionReleaseBindingParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSessionReleaseBinding, arg.InstallationID, arg.CredentialScope, arg.ConversationDigest)
	var binding []byte
	err := row.Scan(&binding)
	return binding, err
}

const upsertSessionReleaseBinding = `-- name: UpsertSessionReleaseBinding :execrows
INSERT INTO router.session_release_bindings (
    installation_id, credential_scope, conversation_digest, target, activation_id,
    release_sha256, binding_sha256, profile_key, profile_revision_sha256,
    enrollment_generation, assignment_generation, subject_assignment_generation, binding_generation,
    binding, created_at, last_admitted_at
) VALUES (
    $1::uuid, $2::varchar, $3::bytea,
    $4::varchar, $5::uuid, $6::varchar, $7::varchar,
    $8::uuid, $9::varchar,
    $10::bigint, $11::bigint, $12::bigint, $13::bigint,
    $14::jsonb, $15::timestamptz, $16::timestamptz
)
ON CONFLICT (installation_id, credential_scope, conversation_digest) DO UPDATE SET
    target = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.target ELSE router.session_release_bindings.target END,
    activation_id = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.activation_id ELSE router.session_release_bindings.activation_id END,
    release_sha256 = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.release_sha256 ELSE router.session_release_bindings.release_sha256 END,
    binding_sha256 = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.binding_sha256 ELSE router.session_release_bindings.binding_sha256 END,
    profile_key = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.profile_key ELSE router.session_release_bindings.profile_key END,
    profile_revision_sha256 = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.profile_revision_sha256 ELSE router.session_release_bindings.profile_revision_sha256 END,
    enrollment_generation = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.enrollment_generation ELSE router.session_release_bindings.enrollment_generation END,
    assignment_generation = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.assignment_generation ELSE router.session_release_bindings.assignment_generation END,
    subject_assignment_generation = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.subject_assignment_generation ELSE router.session_release_bindings.subject_assignment_generation END,
    binding_generation = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.binding_generation ELSE router.session_release_bindings.binding_generation END,
    binding = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.binding
        ELSE jsonb_set(router.session_release_bindings.binding, '{last_admitted_at}', EXCLUDED.binding->'last_admitted_at') END,
    last_admitted_at = EXCLUDED.last_admitted_at
WHERE router.session_release_bindings.binding_generation < EXCLUDED.binding_generation
   OR (
        router.session_release_bindings.binding_generation = EXCLUDED.binding_generation
        AND router.session_release_bindings.target = EXCLUDED.target
        AND router.session_release_bindings.activation_id = EXCLUDED.activation_id
        AND router.session_release_bindings.release_sha256 = EXCLUDED.release_sha256
        AND router.session_release_bindings.binding_sha256 = EXCLUDED.binding_sha256
        AND router.session_release_bindings.enrollment_generation = EXCLUDED.enrollment_generation
        AND router.session_release_bindings.assignment_generation = EXCLUDED.assignment_generation
        AND router.session_release_bindings.subject_assignment_generation = EXCLUDED.subject_assignment_generation
        AND router.session_release_bindings.profile_key IS NOT DISTINCT FROM EXCLUDED.profile_key
    )
`

type UpsertSessionReleaseBindingParams struct {
	InstallationID              uuid.UUID
	CredentialScope             string
	ConversationDigest          []byte
	Target                      string
	ActivationID                uuid.UUID
	ReleaseSha256               string
	BindingSha256               string
	ProfileKey                  pgtype.UUID
	ProfileRevisionSha256       *string
	EnrollmentGeneration        int64
	AssignmentGeneration        int64
	SubjectAssignmentGeneration int64
	BindingGeneration           int64
	Binding                     []byte
	CreatedAt                   pgtype.Timestamptz
	LastAdmittedAt              pgtype.Timestamptz
}

// Called only while the installation/subject/key/conversation admission locks are held.
//
//	INSERT INTO router.session_release_bindings (
//	    installation_id, credential_scope, conversation_digest, target, activation_id,
//	    release_sha256, binding_sha256, profile_key, profile_revision_sha256,
//	    enrollment_generation, assignment_generation, subject_assignment_generation, binding_generation,
//	    binding, created_at, last_admitted_at
//	) VALUES (
//	    $1::uuid, $2::varchar, $3::bytea,
//	    $4::varchar, $5::uuid, $6::varchar, $7::varchar,
//	    $8::uuid, $9::varchar,
//	    $10::bigint, $11::bigint, $12::bigint, $13::bigint,
//	    $14::jsonb, $15::timestamptz, $16::timestamptz
//	)
//	ON CONFLICT (installation_id, credential_scope, conversation_digest) DO UPDATE SET
//	    target = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.target ELSE router.session_release_bindings.target END,
//	    activation_id = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.activation_id ELSE router.session_release_bindings.activation_id END,
//	    release_sha256 = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.release_sha256 ELSE router.session_release_bindings.release_sha256 END,
//	    binding_sha256 = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.binding_sha256 ELSE router.session_release_bindings.binding_sha256 END,
//	    profile_key = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.profile_key ELSE router.session_release_bindings.profile_key END,
//	    profile_revision_sha256 = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.profile_revision_sha256 ELSE router.session_release_bindings.profile_revision_sha256 END,
//	    enrollment_generation = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.enrollment_generation ELSE router.session_release_bindings.enrollment_generation END,
//	    assignment_generation = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.assignment_generation ELSE router.session_release_bindings.assignment_generation END,
//	    subject_assignment_generation = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.subject_assignment_generation ELSE router.session_release_bindings.subject_assignment_generation END,
//	    binding_generation = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.binding_generation ELSE router.session_release_bindings.binding_generation END,
//	    binding = CASE WHEN router.session_release_bindings.binding_generation < EXCLUDED.binding_generation THEN EXCLUDED.binding
//	        ELSE jsonb_set(router.session_release_bindings.binding, '{last_admitted_at}', EXCLUDED.binding->'last_admitted_at') END,
//	    last_admitted_at = EXCLUDED.last_admitted_at
//	WHERE router.session_release_bindings.binding_generation < EXCLUDED.binding_generation
//	   OR (
//	        router.session_release_bindings.binding_generation = EXCLUDED.binding_generation
//	        AND router.session_release_bindings.target = EXCLUDED.target
//	        AND router.session_release_bindings.activation_id = EXCLUDED.activation_id
//	        AND router.session_release_bindings.release_sha256 = EXCLUDED.release_sha256
//	        AND router.session_release_bindings.binding_sha256 = EXCLUDED.binding_sha256
//	        AND router.session_release_bindings.enrollment_generation = EXCLUDED.enrollment_generation
//	        AND router.session_release_bindings.assignment_generation = EXCLUDED.assignment_generation
//	        AND router.session_release_bindings.subject_assignment_generation = EXCLUDED.subject_assignment_generation
//	        AND router.session_release_bindings.profile_key IS NOT DISTINCT FROM EXCLUDED.profile_key
//	    )
func (q *Queries) UpsertSessionReleaseBinding(ctx context.Context, arg UpsertSessionReleaseBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertSessionReleaseBinding,
		arg.InstallationID,
		arg.CredentialScope,
		arg.ConversationDigest,
		arg.Target,
		arg.ActivationID,
		arg.ReleaseSha256,
		arg.BindingSha256,
		arg.ProfileKey,
		arg.ProfileRevisionSha256,
		arg.EnrollmentGeneration,
		arg.AssignmentGeneration,
		arg.SubjectAssignmentGeneration,
		arg.BindingGeneration,
		arg.Binding,
		arg.CreatedAt,
		arg.LastAdmittedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
