// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_pin_recovery_probe_leases.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const acquireSessionPinRecoveryProbeLease = `-- name: AcquireSessionPinRecoveryProbeLease :execrows
INSERT INTO router.session_pin_recovery_probe_leases (session_key, model, lease_token, lease_until)
VALUES (
  $1::bytea, $2::varchar, $3::uuid,
  CURRENT_TIMESTAMP + make_interval(secs => $4::double precision)
)
ON CONFLICT (session_key, model) DO UPDATE SET
  lease_token = EXCLUDED.lease_token,
  lease_until = EXCLUDED.lease_until
WHERE router.session_pin_recovery_probe_leases.lease_until <= CURRENT_TIMESTAMP
`

type AcquireSessionPinRecoveryProbeLeaseParams struct {
	SessionKey   []byte
	Model        string
	LeaseToken   uuid.UUID
	LeaseSeconds float64
}

// Atomically claim one expired or unused recovery probe lease across all
// router workers. An active lease produces zero affected rows. The expiry is
// computed on the database clock that the conflict guard and sweep compare
// against, so a worker with a skewed clock cannot shorten or extend a lease.
//
//	INSERT INTO router.session_pin_recovery_probe_leases (session_key, model, lease_token, lease_until)
//	VALUES (
//	  $1::bytea, $2::varchar, $3::uuid,
//	  CURRENT_TIMESTAMP + make_interval(secs => $4::double precision)
//	)
//	ON CONFLICT (session_key, model) DO UPDATE SET
//	  lease_token = EXCLUDED.lease_token,
//	  lease_until = EXCLUDED.lease_until
//	WHERE router.session_pin_recovery_probe_leases.lease_until <= CURRENT_TIMESTAMP
func (q *Queries) AcquireSessionPinRecoveryProbeLease(ctx context.Context, arg AcquireSessionPinRecoveryProbeLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, acquireSessionPinRecoveryProbeLease,
		arg.SessionKey,
		arg.Model,
		arg.LeaseToken,
		arg.LeaseSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseSessionPinRecoveryProbeLease = `-- name: ReleaseSessionPinRecoveryProbeLease :exec
DELETE FROM router.session_pin_recovery_probe_leases
WHERE session_key = $1::bytea
  AND model = $2::varchar
  AND lease_token = $3::uuid
`

type ReleaseSessionPinRecoveryProbeLeaseParams struct {
	SessionKey []byte
	Model      string
	LeaseToken uuid.UUID
}

// Release only the lease acquired by this attempt, so a delayed completion
// cannot remove a newer worker's lease.
//
//	DELETE FROM router.session_pin_recovery_probe_leases
//	WHERE session_key = $1::bytea
//	  AND model = $2::varchar
//	  AND lease_token = $3::uuid
func (q *Queries) ReleaseSessionPinRecoveryProbeLease(ctx context.Context, arg ReleaseSessionPinRecoveryProbeLeaseParams) error {
	_, err := q.db.Exec(ctx, releaseSessionPinRecoveryProbeLease, arg.SessionKey, arg.Model, arg.LeaseToken)
	return err
}

const sweepExpiredSessionPinRecoveryProbeLeases = `-- name: SweepExpiredSessionPinRecoveryProbeLeases :exec
DELETE FROM router.session_pin_recovery_probe_leases
WHERE lease_until <= CURRENT_TIMESTAMP
`

// Remove abandoned rows after their safety expiry; active rows remain until
// their request releases them.
//
//	DELETE FROM router.session_pin_recovery_probe_leases
//	WHERE lease_until <= CURRENT_TIMESTAMP
func (q *Queries) SweepExpiredSessionPinRecoveryProbeLeases(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sweepExpiredSessionPinRecoveryProbeLeases)
	return err
}
