// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_strategy_preferences.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getSessionStrategyPreference = `-- name: GetSessionStrategyPreference :one
SELECT strategy
FROM router.session_strategy_preferences
WHERE installation_id = $1::uuid
  AND session_key = $2::bytea
  AND enabled
`

type GetSessionStrategyPreferenceParams struct {
	InstallationID uuid.UUID
	SessionKey     []byte
}

// Reads an explicit beta strategy for one installation-scoped session. A
// missing or disabled row means the session uses stable routing.
//
//	SELECT strategy
//	FROM router.session_strategy_preferences
//	WHERE installation_id = $1::uuid
//	  AND session_key = $2::bytea
//	  AND enabled
func (q *Queries) GetSessionStrategyPreference(ctx context.Context, arg GetSessionStrategyPreferenceParams) (string, error) {
	row := q.db.QueryRow(ctx, getSessionStrategyPreference, arg.InstallationID, arg.SessionKey)
	var strategy string
	err := row.Scan(&strategy)
	return strategy, err
}

const updateSessionStrategyPreferenceDisabled = `-- name: UpdateSessionStrategyPreferenceDisabled :execrows
UPDATE router.session_strategy_preferences
SET enabled = FALSE
WHERE installation_id = $1::uuid
  AND session_key = $2::bytea
  AND enabled
`

type UpdateSessionStrategyPreferenceDisabledParams struct {
	InstallationID uuid.UUID
	SessionKey     []byte
}

// Turns the session's explicit override off and reports one affected row when
// beta had been enabled. Callers use this instead of the toggle when the beta
// policy is unavailable, so a concurrent command can never re-enable it.
//
//	UPDATE router.session_strategy_preferences
//	SET enabled = FALSE
//	WHERE installation_id = $1::uuid
//	  AND session_key = $2::bytea
//	  AND enabled
func (q *Queries) UpdateSessionStrategyPreferenceDisabled(ctx context.Context, arg UpdateSessionStrategyPreferenceDisabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionStrategyPreferenceDisabled, arg.InstallationID, arg.SessionKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertToggledSessionStrategyPreference = `-- name: UpsertToggledSessionStrategyPreference :one
INSERT INTO router.session_strategy_preferences (
  installation_id, session_key, strategy, enabled
) VALUES (
  $1::uuid, $2::bytea, $3::varchar, TRUE
)
ON CONFLICT (installation_id, session_key)
DO UPDATE SET
  strategy = EXCLUDED.strategy,
  enabled = NOT router.session_strategy_preferences.enabled
RETURNING enabled
`

type UpsertToggledSessionStrategyPreferenceParams struct {
	InstallationID uuid.UUID
	SessionKey     []byte
	Strategy       string
}

// Flips the session's explicit override and returns the state now persisted.
// The row lock taken on conflict serializes overlapping toggles across router
// instances, so each caller observes its own flip instead of a stale read.
// The database constraint rejects any strategy other than hmm_beta.
//
//	INSERT INTO router.session_strategy_preferences (
//	  installation_id, session_key, strategy, enabled
//	) VALUES (
//	  $1::uuid, $2::bytea, $3::varchar, TRUE
//	)
//	ON CONFLICT (installation_id, session_key)
//	DO UPDATE SET
//	  strategy = EXCLUDED.strategy,
//	  enabled = NOT router.session_strategy_preferences.enabled
//	RETURNING enabled
func (q *Queries) UpsertToggledSessionStrategyPreference(ctx context.Context, arg UpsertToggledSessionStrategyPreferenceParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertToggledSessionStrategyPreference, arg.InstallationID, arg.SessionKey, arg.Strategy)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}
