// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: struggle_shadow_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countStruggleShadowEvents = `-- name: CountStruggleShadowEvents :one
SELECT COUNT(*)
FROM router.struggle_shadow_events
WHERE session_key = $1::bytea
  AND role        = $2::varchar
  AND reason      = $3::varchar
`

type CountStruggleShadowEventsParams struct {
	SessionKey []byte
	Role       string
	Reason     string
}

// Once-per-(session, role, reason) budget check: any prior event means this
// operating point already fired for this session and must not produce another
// row, even across replicas and in-proc cache expiry.
//
//	SELECT COUNT(*)
//	FROM router.struggle_shadow_events
//	WHERE session_key = $1::bytea
//	  AND role        = $2::varchar
//	  AND reason      = $3::varchar
func (q *Queries) CountStruggleShadowEvents(ctx context.Context, arg CountStruggleShadowEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStruggleShadowEvents, arg.SessionKey, arg.Role, arg.Reason)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertStruggleShadowEvent = `-- name: InsertStruggleShadowEvent :exec
INSERT INTO router.struggle_shadow_events (
    installation_id,
    session_key,
    role,
    routed_model,
    turn_type,
    reason,
    turn_count,
    wall_seconds,
    session_ever_switched,
    est_input_tokens
) VALUES (
    $1::uuid,
    $2::bytea,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::varchar,
    $7::int,
    $8::bigint,
    $9::boolean,
    $10::int
)
`

type InsertStruggleShadowEventParams struct {
	InstallationID      uuid.UUID
	SessionKey          []byte
	Role                string
	RoutedModel         string
	TurnType            string
	Reason              string
	TurnCount           int32
	WallSeconds         int64
	SessionEverSwitched bool
	EstInputTokens      int32
}

// Records one shadow-mode struggle detection. Written at detection time with
// context.Background() (the request ctx may already be canceled); fire rate,
// precision, and lead time are computed offline by joining session_key
// against model_router_request_telemetry / session outcomes.
//
//	INSERT INTO router.struggle_shadow_events (
//	    installation_id,
//	    session_key,
//	    role,
//	    routed_model,
//	    turn_type,
//	    reason,
//	    turn_count,
//	    wall_seconds,
//	    session_ever_switched,
//	    est_input_tokens
//	) VALUES (
//	    $1::uuid,
//	    $2::bytea,
//	    $3::varchar,
//	    $4::varchar,
//	    $5::varchar,
//	    $6::varchar,
//	    $7::int,
//	    $8::bigint,
//	    $9::boolean,
//	    $10::int
//	)
func (q *Queries) InsertStruggleShadowEvent(ctx context.Context, arg InsertStruggleShadowEventParams) error {
	_, err := q.db.Exec(ctx, insertStruggleShadowEvent,
		arg.InstallationID,
		arg.SessionKey,
		arg.Role,
		arg.RoutedModel,
		arg.TurnType,
		arg.Reason,
		arg.TurnCount,
		arg.WallSeconds,
		arg.SessionEverSwitched,
		arg.EstInputTokens,
	)
	return err
}
