// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: struggle_escalation_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countStruggleEscalationEvents = `-- name: CountStruggleEscalationEvents :one
SELECT COUNT(*)
FROM router.struggle_escalation_events
WHERE session_key = $1::bytea
  AND role = $2::varchar
`

type CountStruggleEscalationEventsParams struct {
	SessionKey []byte
	Role       string
}

// CountStruggleEscalationEvents
//
//	SELECT COUNT(*)
//	FROM router.struggle_escalation_events
//	WHERE session_key = $1::bytea
//	  AND role = $2::varchar
func (q *Queries) CountStruggleEscalationEvents(ctx context.Context, arg CountStruggleEscalationEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStruggleEscalationEvents, arg.SessionKey, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertStruggleEscalationEvent = `-- name: InsertStruggleEscalationEvent :exec
INSERT INTO router.struggle_escalation_events (
    installation_id, session_key, role, struggling_model,
    action, escalation_target, turn_count, wall_seconds,
    session_ever_switched, arming_mode, evidence_reasons
) VALUES (
    $1::uuid, $2::bytea, $3::varchar,
    $4::varchar, $5::varchar, $6::varchar,
    $7::int, $8::bigint, $9::boolean,
    $10::varchar, $11::varchar[]
)
`

type InsertStruggleEscalationEventParams struct {
	InstallationID      uuid.UUID
	SessionKey          []byte
	Role                string
	StrugglingModel     string
	Action              string
	EscalationTarget    string
	TurnCount           int32
	WallSeconds         int64
	SessionEverSwitched bool
	ArmingMode          string
	EvidenceReasons     []string
}

// InsertStruggleEscalationEvent
//
//	INSERT INTO router.struggle_escalation_events (
//	    installation_id, session_key, role, struggling_model,
//	    action, escalation_target, turn_count, wall_seconds,
//	    session_ever_switched, arming_mode, evidence_reasons
//	) VALUES (
//	    $1::uuid, $2::bytea, $3::varchar,
//	    $4::varchar, $5::varchar, $6::varchar,
//	    $7::int, $8::bigint, $9::boolean,
//	    $10::varchar, $11::varchar[]
//	)
func (q *Queries) InsertStruggleEscalationEvent(ctx context.Context, arg InsertStruggleEscalationEventParams) error {
	_, err := q.db.Exec(ctx, insertStruggleEscalationEvent,
		arg.InstallationID,
		arg.SessionKey,
		arg.Role,
		arg.StrugglingModel,
		arg.Action,
		arg.EscalationTarget,
		arg.TurnCount,
		arg.WallSeconds,
		arg.SessionEverSwitched,
		arg.ArmingMode,
		arg.EvidenceReasons,
	)
	return err
}
