// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriber_entitlements.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscriberEntitlement = `-- name: GetSubscriberEntitlement :one
SELECT subscriber_id, version, plan, status, billing_period_start, billing_period_end, effective_at, monthly_allowance_usd_micros, nominal_monthly_allowance_usd_micros, six_hour_allowance_usd_micros, auto_top_up_enabled, projected_at, created_at, updated_at
FROM router.subscriber_entitlements
WHERE subscriber_id = $1::uuid
`

// Returns the current projected entitlement for one authenticated credential subject.
//
//	SELECT subscriber_id, version, plan, status, billing_period_start, billing_period_end, effective_at, monthly_allowance_usd_micros, nominal_monthly_allowance_usd_micros, six_hour_allowance_usd_micros, auto_top_up_enabled, projected_at, created_at, updated_at
//	FROM router.subscriber_entitlements
//	WHERE subscriber_id = $1::uuid
func (q *Queries) GetSubscriberEntitlement(ctx context.Context, subscriberID uuid.UUID) (RouterSubscriberEntitlement, error) {
	row := q.db.QueryRow(ctx, getSubscriberEntitlement, subscriberID)
	var i RouterSubscriberEntitlement
	err := row.Scan(
		&i.SubscriberID,
		&i.Version,
		&i.Plan,
		&i.Status,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.EffectiveAt,
		&i.MonthlyAllowanceUsdMicros,
		&i.NominalMonthlyAllowanceUsdMicros,
		&i.SixHourAllowanceUsdMicros,
		&i.AutoTopUpEnabled,
		&i.ProjectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubscriberEntitlement = `-- name: UpsertSubscriberEntitlement :one
INSERT INTO router.subscriber_entitlements (
    subscriber_id,
    version,
    plan,
    status,
    billing_period_start,
    billing_period_end,
    effective_at,
    monthly_allowance_usd_micros,
    nominal_monthly_allowance_usd_micros,
    six_hour_allowance_usd_micros,
    auto_top_up_enabled,
    projected_at
) VALUES (
    $1::uuid,
    $2::bigint,
    $3::varchar,
    $4::varchar,
    $5::timestamptz,
    $6::timestamptz,
    $7::timestamptz,
    $8::bigint,
    $9::bigint,
    $10::bigint,
    $11::boolean,
    $12::timestamptz
)
ON CONFLICT (subscriber_id) DO UPDATE SET
    version = EXCLUDED.version,
    plan = EXCLUDED.plan,
    status = EXCLUDED.status,
    billing_period_start = EXCLUDED.billing_period_start,
    billing_period_end = EXCLUDED.billing_period_end,
    effective_at = EXCLUDED.effective_at,
    monthly_allowance_usd_micros = EXCLUDED.monthly_allowance_usd_micros,
    nominal_monthly_allowance_usd_micros = EXCLUDED.nominal_monthly_allowance_usd_micros,
    six_hour_allowance_usd_micros = EXCLUDED.six_hour_allowance_usd_micros,
    auto_top_up_enabled = EXCLUDED.auto_top_up_enabled,
    projected_at = EXCLUDED.projected_at,
    updated_at = CASE
        WHEN router.subscriber_entitlements.version < EXCLUDED.version THEN CURRENT_TIMESTAMP
        ELSE router.subscriber_entitlements.updated_at
    END
WHERE router.subscriber_entitlements.version < EXCLUDED.version
    OR (
        router.subscriber_entitlements.version = EXCLUDED.version
        AND ROW(
            router.subscriber_entitlements.plan,
            router.subscriber_entitlements.status,
            router.subscriber_entitlements.billing_period_start,
            router.subscriber_entitlements.billing_period_end,
            router.subscriber_entitlements.effective_at,
            router.subscriber_entitlements.monthly_allowance_usd_micros,
            router.subscriber_entitlements.nominal_monthly_allowance_usd_micros,
            router.subscriber_entitlements.six_hour_allowance_usd_micros,
            router.subscriber_entitlements.auto_top_up_enabled,
            router.subscriber_entitlements.projected_at
        ) IS NOT DISTINCT FROM ROW(
            EXCLUDED.plan,
            EXCLUDED.status,
            EXCLUDED.billing_period_start,
            EXCLUDED.billing_period_end,
            EXCLUDED.effective_at,
            EXCLUDED.monthly_allowance_usd_micros,
            EXCLUDED.nominal_monthly_allowance_usd_micros,
            EXCLUDED.six_hour_allowance_usd_micros,
            EXCLUDED.auto_top_up_enabled,
            EXCLUDED.projected_at
        )
    )
RETURNING subscriber_id, version, plan, status, billing_period_start, billing_period_end, effective_at, monthly_allowance_usd_micros, nominal_monthly_allowance_usd_micros, six_hour_allowance_usd_micros, auto_top_up_enabled, projected_at, created_at, updated_at
`

type UpsertSubscriberEntitlementParams struct {
	SubscriberID                     uuid.UUID
	Version                          int64
	Plan                             string
	Status                           string
	BillingPeriodStart               pgtype.Timestamptz
	BillingPeriodEnd                 pgtype.Timestamptz
	EffectiveAt                      pgtype.Timestamptz
	MonthlyAllowanceUsdMicros        int64
	NominalMonthlyAllowanceUsdMicros int64
	SixHourAllowanceUsdMicros        int64
	AutoTopUpEnabled                 bool
	ProjectedAt                      pgtype.Timestamptz
}

// Inserts a subscriber projection, advances a lower stored version, or returns an identical retry.
//
//	INSERT INTO router.subscriber_entitlements (
//	    subscriber_id,
//	    version,
//	    plan,
//	    status,
//	    billing_period_start,
//	    billing_period_end,
//	    effective_at,
//	    monthly_allowance_usd_micros,
//	    nominal_monthly_allowance_usd_micros,
//	    six_hour_allowance_usd_micros,
//	    auto_top_up_enabled,
//	    projected_at
//	) VALUES (
//	    $1::uuid,
//	    $2::bigint,
//	    $3::varchar,
//	    $4::varchar,
//	    $5::timestamptz,
//	    $6::timestamptz,
//	    $7::timestamptz,
//	    $8::bigint,
//	    $9::bigint,
//	    $10::bigint,
//	    $11::boolean,
//	    $12::timestamptz
//	)
//	ON CONFLICT (subscriber_id) DO UPDATE SET
//	    version = EXCLUDED.version,
//	    plan = EXCLUDED.plan,
//	    status = EXCLUDED.status,
//	    billing_period_start = EXCLUDED.billing_period_start,
//	    billing_period_end = EXCLUDED.billing_period_end,
//	    effective_at = EXCLUDED.effective_at,
//	    monthly_allowance_usd_micros = EXCLUDED.monthly_allowance_usd_micros,
//	    nominal_monthly_allowance_usd_micros = EXCLUDED.nominal_monthly_allowance_usd_micros,
//	    six_hour_allowance_usd_micros = EXCLUDED.six_hour_allowance_usd_micros,
//	    auto_top_up_enabled = EXCLUDED.auto_top_up_enabled,
//	    projected_at = EXCLUDED.projected_at,
//	    updated_at = CASE
//	        WHEN router.subscriber_entitlements.version < EXCLUDED.version THEN CURRENT_TIMESTAMP
//	        ELSE router.subscriber_entitlements.updated_at
//	    END
//	WHERE router.subscriber_entitlements.version < EXCLUDED.version
//	    OR (
//	        router.subscriber_entitlements.version = EXCLUDED.version
//	        AND ROW(
//	            router.subscriber_entitlements.plan,
//	            router.subscriber_entitlements.status,
//	            router.subscriber_entitlements.billing_period_start,
//	            router.subscriber_entitlements.billing_period_end,
//	            router.subscriber_entitlements.effective_at,
//	            router.subscriber_entitlements.monthly_allowance_usd_micros,
//	            router.subscriber_entitlements.nominal_monthly_allowance_usd_micros,
//	            router.subscriber_entitlements.six_hour_allowance_usd_micros,
//	            router.subscriber_entitlements.auto_top_up_enabled,
//	            router.subscriber_entitlements.projected_at
//	        ) IS NOT DISTINCT FROM ROW(
//	            EXCLUDED.plan,
//	            EXCLUDED.status,
//	            EXCLUDED.billing_period_start,
//	            EXCLUDED.billing_period_end,
//	            EXCLUDED.effective_at,
//	            EXCLUDED.monthly_allowance_usd_micros,
//	            EXCLUDED.nominal_monthly_allowance_usd_micros,
//	            EXCLUDED.six_hour_allowance_usd_micros,
//	            EXCLUDED.auto_top_up_enabled,
//	            EXCLUDED.projected_at
//	        )
//	    )
//	RETURNING subscriber_id, version, plan, status, billing_period_start, billing_period_end, effective_at, monthly_allowance_usd_micros, nominal_monthly_allowance_usd_micros, six_hour_allowance_usd_micros, auto_top_up_enabled, projected_at, created_at, updated_at
func (q *Queries) UpsertSubscriberEntitlement(ctx context.Context, arg UpsertSubscriberEntitlementParams) (RouterSubscriberEntitlement, error) {
	row := q.db.QueryRow(ctx, upsertSubscriberEntitlement,
		arg.SubscriberID,
		arg.Version,
		arg.Plan,
		arg.Status,
		arg.BillingPeriodStart,
		arg.BillingPeriodEnd,
		arg.EffectiveAt,
		arg.MonthlyAllowanceUsdMicros,
		arg.NominalMonthlyAllowanceUsdMicros,
		arg.SixHourAllowanceUsdMicros,
		arg.AutoTopUpEnabled,
		arg.ProjectedAt,
	)
	var i RouterSubscriberEntitlement
	err := row.Scan(
		&i.SubscriberID,
		&i.Version,
		&i.Plan,
		&i.Status,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.EffectiveAt,
		&i.MonthlyAllowanceUsdMicros,
		&i.NominalMonthlyAllowanceUsdMicros,
		&i.SixHourAllowanceUsdMicros,
		&i.AutoTopUpEnabled,
		&i.ProjectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
