// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriber_billing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const debitSubscriberCredits = `-- name: DebitSubscriberCredits :one
WITH updated AS (
    UPDATE router.subscriber_credit_balance
    SET balance_usd_micros = balance_usd_micros + $2::bigint,
        updated_at = NOW()
    WHERE subscriber_id = $1::uuid
    RETURNING balance_usd_micros
)
INSERT INTO router.subscriber_credit_ledger (
    subscriber_id,
    delta_usd_micros,
    notional_cost_micros,
    balance_after_micros,
    entry_type,
    router_request_id,
    router_model
)
SELECT
    $1::uuid,
    $2::bigint,
    $3::bigint,
    updated.balance_usd_micros,
    $4::varchar,
    $5::varchar,
    $6::varchar
FROM updated
RETURNING balance_after_micros
`

type DebitSubscriberCreditsParams struct {
	SubscriberID       uuid.UUID
	DeltaUsdMicros     int64
	NotionalCostMicros int64
	EntryType          string
	RouterRequestID    *string
	RouterModel        *string
}

// Atomic debit against one subscriber's prepaid book: move the balance and
// append the matching ledger row in a single statement, both keyed by the
// same subscriber_id so a debit can never land on another owner's balance.
// delta_usd_micros is the signed change (negative for a real debit, zero for
// a pass-through), while notional_cost_micros always records the would-be
// charge for the shadow trail.
//
// No `balance >= amount` guard, matching DebitOrgCredits: concurrent turns can
// both clear the preflight check and both must still be recorded.
//
// Returns the post-debit balance; zero rows means the subscriber had no
// balance row, which the caller maps to a missing-balance error.
//
//	WITH updated AS (
//	    UPDATE router.subscriber_credit_balance
//	    SET balance_usd_micros = balance_usd_micros + $2::bigint,
//	        updated_at = NOW()
//	    WHERE subscriber_id = $1::uuid
//	    RETURNING balance_usd_micros
//	)
//	INSERT INTO router.subscriber_credit_ledger (
//	    subscriber_id,
//	    delta_usd_micros,
//	    notional_cost_micros,
//	    balance_after_micros,
//	    entry_type,
//	    router_request_id,
//	    router_model
//	)
//	SELECT
//	    $1::uuid,
//	    $2::bigint,
//	    $3::bigint,
//	    updated.balance_usd_micros,
//	    $4::varchar,
//	    $5::varchar,
//	    $6::varchar
//	FROM updated
//	RETURNING balance_after_micros
func (q *Queries) DebitSubscriberCredits(ctx context.Context, arg DebitSubscriberCreditsParams) (int64, error) {
	row := q.db.QueryRow(ctx, debitSubscriberCredits,
		arg.SubscriberID,
		arg.DeltaUsdMicros,
		arg.NotionalCostMicros,
		arg.EntryType,
		arg.RouterRequestID,
		arg.RouterModel,
	)
	var balance_after_micros int64
	err := row.Scan(&balance_after_micros)
	return balance_after_micros, err
}

const getSubscriberCreditBalance = `-- name: GetSubscriberCreditBalance :one
SELECT balance_usd_micros
FROM router.subscriber_credit_balance
WHERE subscriber_id = $1::uuid
`

// Returns an individual subscriber's current prepaid balance in USD micros.
// The owner is the credential subject, never an organization id, so a
// subscriber's funds are unreachable from any other subscriber in the same
// organization. A missing row surfaces as a no-row error, as with the
// organization book, so callers decide whether "no row" differs from zero.
//
//	SELECT balance_usd_micros
//	FROM router.subscriber_credit_balance
//	WHERE subscriber_id = $1::uuid
func (q *Queries) GetSubscriberCreditBalance(ctx context.Context, subscriberID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSubscriberCreditBalance, subscriberID)
	var balance_usd_micros int64
	err := row.Scan(&balance_usd_micros)
	return balance_usd_micros, err
}
