// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriber_allowances.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accrueSubscriberAllowancePeriod = `-- name: AccrueSubscriberAllowancePeriod :one
INSERT INTO router.subscriber_allowance_periods (
    subscriber_id,
    period_kind,
    period_start,
    period_end,
    entitlement_version,
    plan,
    limit_usd_micros,
    reserved_usd_micros
)
SELECT
    $1::uuid,
    $2::varchar,
    $3::timestamptz,
    $4::timestamptz,
    $5::bigint,
    $6::varchar,
    $7::bigint,
    $8::bigint
WHERE $8::bigint <= $7::bigint
ON CONFLICT (subscriber_id, period_kind, period_start) DO UPDATE SET
    period_end = CASE
        WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.period_end
        ELSE router.subscriber_allowance_periods.period_end
    END,
    entitlement_version = GREATEST(router.subscriber_allowance_periods.entitlement_version, EXCLUDED.entitlement_version),
    plan = CASE
        WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.plan
        ELSE router.subscriber_allowance_periods.plan
    END,
    limit_usd_micros = CASE
        WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.limit_usd_micros
        ELSE router.subscriber_allowance_periods.limit_usd_micros
    END,
    reserved_usd_micros = router.subscriber_allowance_periods.reserved_usd_micros + EXCLUDED.reserved_usd_micros,
    updated_at = CURRENT_TIMESTAMP
WHERE router.subscriber_allowance_periods.reserved_usd_micros
        + router.subscriber_allowance_periods.finalized_usd_micros
        + EXCLUDED.reserved_usd_micros
      <= CASE
        WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.limit_usd_micros
        ELSE router.subscriber_allowance_periods.limit_usd_micros
    END
RETURNING subscriber_id, period_kind, period_start, period_end, entitlement_version, plan, limit_usd_micros, reserved_usd_micros, finalized_usd_micros, created_at, updated_at
`

type AccrueSubscriberAllowancePeriodParams struct {
	SubscriberID       uuid.UUID
	PeriodKind         string
	PeriodStart        pgtype.Timestamptz
	PeriodEnd          pgtype.Timestamptz
	EntitlementVersion int64
	Plan               string
	LimitUsdMicros     int64
	ReservedUsdMicros  int64
}

// Accrues one hold against one enforcement window, refusing it when the hold
// would carry the window's consumed cost past its limit. Both the conflicting
// update and the first insert are gated, so the invariant holds for a window
// whose row does not exist yet. A refusal returns no row: the caller aborts the
// reservation instead of dispatching work the allowance cannot pay for.
//
//	INSERT INTO router.subscriber_allowance_periods (
//	    subscriber_id,
//	    period_kind,
//	    period_start,
//	    period_end,
//	    entitlement_version,
//	    plan,
//	    limit_usd_micros,
//	    reserved_usd_micros
//	)
//	SELECT
//	    $1::uuid,
//	    $2::varchar,
//	    $3::timestamptz,
//	    $4::timestamptz,
//	    $5::bigint,
//	    $6::varchar,
//	    $7::bigint,
//	    $8::bigint
//	WHERE $8::bigint <= $7::bigint
//	ON CONFLICT (subscriber_id, period_kind, period_start) DO UPDATE SET
//	    period_end = CASE
//	        WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.period_end
//	        ELSE router.subscriber_allowance_periods.period_end
//	    END,
//	    entitlement_version = GREATEST(router.subscriber_allowance_periods.entitlement_version, EXCLUDED.entitlement_version),
//	    plan = CASE
//	        WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.plan
//	        ELSE router.subscriber_allowance_periods.plan
//	    END,
//	    limit_usd_micros = CASE
//	        WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.limit_usd_micros
//	        ELSE router.subscriber_allowance_periods.limit_usd_micros
//	    END,
//	    reserved_usd_micros = router.subscriber_allowance_periods.reserved_usd_micros + EXCLUDED.reserved_usd_micros,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE router.subscriber_allowance_periods.reserved_usd_micros
//	        + router.subscriber_allowance_periods.finalized_usd_micros
//	        + EXCLUDED.reserved_usd_micros
//	      <= CASE
//	        WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.limit_usd_micros
//	        ELSE router.subscriber_allowance_periods.limit_usd_micros
//	    END
//	RETURNING subscriber_id, period_kind, period_start, period_end, entitlement_version, plan, limit_usd_micros, reserved_usd_micros, finalized_usd_micros, created_at, updated_at
func (q *Queries) AccrueSubscriberAllowancePeriod(ctx context.Context, arg AccrueSubscriberAllowancePeriodParams) (RouterSubscriberAllowancePeriod, error) {
	row := q.db.QueryRow(ctx, accrueSubscriberAllowancePeriod,
		arg.SubscriberID,
		arg.PeriodKind,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.EntitlementVersion,
		arg.Plan,
		arg.LimitUsdMicros,
		arg.ReservedUsdMicros,
	)
	var i RouterSubscriberAllowancePeriod
	err := row.Scan(
		&i.SubscriberID,
		&i.PeriodKind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.EntitlementVersion,
		&i.Plan,
		&i.LimitUsdMicros,
		&i.ReservedUsdMicros,
		&i.FinalizedUsdMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeSubscriberAllowance = `-- name: FinalizeSubscriberAllowance :one
WITH finalized AS (
    UPDATE router.subscriber_allowance_actions
    SET state = 'finalized',
        served_model = $1::varchar,
        retail_usd_micros = $2::bigint,
        finalized_at = $3::timestamptz,
        updated_at = CURRENT_TIMESTAMP
    WHERE action_id = $4::varchar
      AND state = 'reserved'
      AND capacity_source = $5::varchar
    RETURNING action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end
), billing_window AS (
    UPDATE router.subscriber_allowance_periods
    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - finalized.reserved_usd_micros, 0),
        finalized_usd_micros = router.subscriber_allowance_periods.finalized_usd_micros + finalized.retail_usd_micros,
        updated_at = CURRENT_TIMESTAMP
    FROM finalized
    WHERE router.subscriber_allowance_periods.subscriber_id = finalized.subscriber_id
      AND router.subscriber_allowance_periods.period_kind = 'billing'
      AND router.subscriber_allowance_periods.period_start = finalized.billing_period_start
      AND finalized.capacity_source = 'included_router'
), weekly_window AS (
    UPDATE router.subscriber_allowance_periods
    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - finalized.reserved_usd_micros, 0),
        finalized_usd_micros = router.subscriber_allowance_periods.finalized_usd_micros + finalized.retail_usd_micros,
        updated_at = CURRENT_TIMESTAMP
    FROM finalized
    WHERE router.subscriber_allowance_periods.subscriber_id = finalized.subscriber_id
      AND router.subscriber_allowance_periods.period_kind = 'weekly'
      AND router.subscriber_allowance_periods.period_start = finalized.weekly_period_start
      AND finalized.capacity_source = 'included_router'
), six_hour_window AS (
    UPDATE router.subscriber_allowance_periods
    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - finalized.reserved_usd_micros, 0),
        finalized_usd_micros = router.subscriber_allowance_periods.finalized_usd_micros + finalized.retail_usd_micros,
        updated_at = CURRENT_TIMESTAMP
    FROM finalized
    WHERE router.subscriber_allowance_periods.subscriber_id = finalized.subscriber_id
      AND router.subscriber_allowance_periods.period_kind = 'six_hour'
      AND router.subscriber_allowance_periods.period_start = finalized.six_hour_period_start
      AND finalized.capacity_source = 'included_router'
)
SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM finalized
UNION ALL
SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM router.subscriber_allowance_actions
WHERE action_id = $4::varchar
  AND NOT EXISTS (SELECT 1 FROM finalized)
`

type FinalizeSubscriberAllowanceParams struct {
	ServedModel     string
	RetailUsdMicros int64
	FinalizedAt     pgtype.Timestamptz
	ActionID        string
	CapacitySource  string
}

type FinalizeSubscriberAllowanceRow struct {
	ActionID           string
	RouterRequestID    string
	SubscriberID       uuid.UUID
	EntitlementVersion int64
	Plan               string
	BillingPeriodStart pgtype.Timestamptz
	BillingPeriodEnd   pgtype.Timestamptz
	SixHourPeriodStart pgtype.Timestamptz
	SixHourPeriodEnd   pgtype.Timestamptz
	APIKeyID           uuid.UUID
	ClientSessionID    *string
	RequestedModel     string
	ServedModel        *string
	ReservedUsdMicros  int64
	RetailUsdMicros    *int64
	CapacitySource     string
	State              string
	ReservedAt         pgtype.Timestamptz
	FinalizedAt        pgtype.Timestamptz
	ReleasedAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	WeeklyPeriodStart  pgtype.Timestamptz
	WeeklyPeriodEnd    pgtype.Timestamptz
}

// Settles a reserved action at its actual retail cost, releasing the hold and
// accruing the cost against every window. Matching on the reserved capacity
// source keeps a turn that ended up served elsewhere from silently settling
// against the subscription allowance. A redelivered finalization returns the
// stored action unchanged.
//
//	WITH finalized AS (
//	    UPDATE router.subscriber_allowance_actions
//	    SET state = 'finalized',
//	        served_model = $1::varchar,
//	        retail_usd_micros = $2::bigint,
//	        finalized_at = $3::timestamptz,
//	        updated_at = CURRENT_TIMESTAMP
//	    WHERE action_id = $4::varchar
//	      AND state = 'reserved'
//	      AND capacity_source = $5::varchar
//	    RETURNING action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end
//	), billing_window AS (
//	    UPDATE router.subscriber_allowance_periods
//	    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - finalized.reserved_usd_micros, 0),
//	        finalized_usd_micros = router.subscriber_allowance_periods.finalized_usd_micros + finalized.retail_usd_micros,
//	        updated_at = CURRENT_TIMESTAMP
//	    FROM finalized
//	    WHERE router.subscriber_allowance_periods.subscriber_id = finalized.subscriber_id
//	      AND router.subscriber_allowance_periods.period_kind = 'billing'
//	      AND router.subscriber_allowance_periods.period_start = finalized.billing_period_start
//	      AND finalized.capacity_source = 'included_router'
//	), weekly_window AS (
//	    UPDATE router.subscriber_allowance_periods
//	    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - finalized.reserved_usd_micros, 0),
//	        finalized_usd_micros = router.subscriber_allowance_periods.finalized_usd_micros + finalized.retail_usd_micros,
//	        updated_at = CURRENT_TIMESTAMP
//	    FROM finalized
//	    WHERE router.subscriber_allowance_periods.subscriber_id = finalized.subscriber_id
//	      AND router.subscriber_allowance_periods.period_kind = 'weekly'
//	      AND router.subscriber_allowance_periods.period_start = finalized.weekly_period_start
//	      AND finalized.capacity_source = 'included_router'
//	), six_hour_window AS (
//	    UPDATE router.subscriber_allowance_periods
//	    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - finalized.reserved_usd_micros, 0),
//	        finalized_usd_micros = router.subscriber_allowance_periods.finalized_usd_micros + finalized.retail_usd_micros,
//	        updated_at = CURRENT_TIMESTAMP
//	    FROM finalized
//	    WHERE router.subscriber_allowance_periods.subscriber_id = finalized.subscriber_id
//	      AND router.subscriber_allowance_periods.period_kind = 'six_hour'
//	      AND router.subscriber_allowance_periods.period_start = finalized.six_hour_period_start
//	      AND finalized.capacity_source = 'included_router'
//	)
//	SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM finalized
//	UNION ALL
//	SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM router.subscriber_allowance_actions
//	WHERE action_id = $4::varchar
//	  AND NOT EXISTS (SELECT 1 FROM finalized)
func (q *Queries) FinalizeSubscriberAllowance(ctx context.Context, arg FinalizeSubscriberAllowanceParams) (FinalizeSubscriberAllowanceRow, error) {
	row := q.db.QueryRow(ctx, finalizeSubscriberAllowance,
		arg.ServedModel,
		arg.RetailUsdMicros,
		arg.FinalizedAt,
		arg.ActionID,
		arg.CapacitySource,
	)
	var i FinalizeSubscriberAllowanceRow
	err := row.Scan(
		&i.ActionID,
		&i.RouterRequestID,
		&i.SubscriberID,
		&i.EntitlementVersion,
		&i.Plan,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.SixHourPeriodStart,
		&i.SixHourPeriodEnd,
		&i.APIKeyID,
		&i.ClientSessionID,
		&i.RequestedModel,
		&i.ServedModel,
		&i.ReservedUsdMicros,
		&i.RetailUsdMicros,
		&i.CapacitySource,
		&i.State,
		&i.ReservedAt,
		&i.FinalizedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeeklyPeriodStart,
		&i.WeeklyPeriodEnd,
	)
	return i, err
}

const getSubscriberAllowanceAction = `-- name: GetSubscriberAllowanceAction :one
SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end
FROM router.subscriber_allowance_actions
WHERE action_id = $1::varchar
`

// Reads one stored allowance action. Callers use it after a write statement
// declined to transition a row, because that statement's snapshot cannot see a
// concurrently committed action.
//
//	SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end
//	FROM router.subscriber_allowance_actions
//	WHERE action_id = $1::varchar
func (q *Queries) GetSubscriberAllowanceAction(ctx context.Context, actionID string) (RouterSubscriberAllowanceAction, error) {
	row := q.db.QueryRow(ctx, getSubscriberAllowanceAction, actionID)
	var i RouterSubscriberAllowanceAction
	err := row.Scan(
		&i.ActionID,
		&i.RouterRequestID,
		&i.SubscriberID,
		&i.EntitlementVersion,
		&i.Plan,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.SixHourPeriodStart,
		&i.SixHourPeriodEnd,
		&i.APIKeyID,
		&i.ClientSessionID,
		&i.RequestedModel,
		&i.ServedModel,
		&i.ReservedUsdMicros,
		&i.RetailUsdMicros,
		&i.CapacitySource,
		&i.State,
		&i.ReservedAt,
		&i.FinalizedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeeklyPeriodStart,
		&i.WeeklyPeriodEnd,
	)
	return i, err
}

const insertSubscriberAllowanceAction = `-- name: InsertSubscriberAllowanceAction :one
INSERT INTO router.subscriber_allowance_actions (
    action_id,
    router_request_id,
    subscriber_id,
    entitlement_version,
    plan,
    billing_period_start,
    billing_period_end,
    weekly_period_start,
    weekly_period_end,
    six_hour_period_start,
    six_hour_period_end,
    api_key_id,
    client_session_id,
    requested_model,
    reserved_usd_micros,
    capacity_source,
    state,
    reserved_at
) VALUES (
    $1::varchar,
    $2::varchar,
    $3::uuid,
    $4::bigint,
    $5::varchar,
    $6::timestamptz,
    $7::timestamptz,
    $8::timestamptz,
    $9::timestamptz,
    $10::timestamptz,
    $11::timestamptz,
    $12::uuid,
    $13::varchar,
    $14::varchar,
    $15::bigint,
    $16::varchar,
    'reserved',
    $17::timestamptz
)
ON CONFLICT (action_id) DO NOTHING
RETURNING action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end
`

type InsertSubscriberAllowanceActionParams struct {
	ActionID           string
	RouterRequestID    string
	SubscriberID       uuid.UUID
	EntitlementVersion int64
	Plan               string
	BillingPeriodStart pgtype.Timestamptz
	BillingPeriodEnd   pgtype.Timestamptz
	WeeklyPeriodStart  pgtype.Timestamptz
	WeeklyPeriodEnd    pgtype.Timestamptz
	SixHourPeriodStart pgtype.Timestamptz
	SixHourPeriodEnd   pgtype.Timestamptz
	APIKeyID           uuid.UUID
	ClientSessionID    *string
	RequestedModel     string
	ReservedUsdMicros  int64
	CapacitySource     string
	ReservedAt         pgtype.Timestamptz
}

// Records an allowance hold for one action without accruing it against any
// window. Callers that enforce the limit accrue each window separately, in the
// same transaction, so a refused window leaves no action behind. A redelivered
// action identifier returns no row: its windows were already drawn down by the
// first delivery, and the caller reads the stored action instead.
//
//	INSERT INTO router.subscriber_allowance_actions (
//	    action_id,
//	    router_request_id,
//	    subscriber_id,
//	    entitlement_version,
//	    plan,
//	    billing_period_start,
//	    billing_period_end,
//	    weekly_period_start,
//	    weekly_period_end,
//	    six_hour_period_start,
//	    six_hour_period_end,
//	    api_key_id,
//	    client_session_id,
//	    requested_model,
//	    reserved_usd_micros,
//	    capacity_source,
//	    state,
//	    reserved_at
//	) VALUES (
//	    $1::varchar,
//	    $2::varchar,
//	    $3::uuid,
//	    $4::bigint,
//	    $5::varchar,
//	    $6::timestamptz,
//	    $7::timestamptz,
//	    $8::timestamptz,
//	    $9::timestamptz,
//	    $10::timestamptz,
//	    $11::timestamptz,
//	    $12::uuid,
//	    $13::varchar,
//	    $14::varchar,
//	    $15::bigint,
//	    $16::varchar,
//	    'reserved',
//	    $17::timestamptz
//	)
//	ON CONFLICT (action_id) DO NOTHING
//	RETURNING action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end
func (q *Queries) InsertSubscriberAllowanceAction(ctx context.Context, arg InsertSubscriberAllowanceActionParams) (RouterSubscriberAllowanceAction, error) {
	row := q.db.QueryRow(ctx, insertSubscriberAllowanceAction,
		arg.ActionID,
		arg.RouterRequestID,
		arg.SubscriberID,
		arg.EntitlementVersion,
		arg.Plan,
		arg.BillingPeriodStart,
		arg.BillingPeriodEnd,
		arg.WeeklyPeriodStart,
		arg.WeeklyPeriodEnd,
		arg.SixHourPeriodStart,
		arg.SixHourPeriodEnd,
		arg.APIKeyID,
		arg.ClientSessionID,
		arg.RequestedModel,
		arg.ReservedUsdMicros,
		arg.CapacitySource,
		arg.ReservedAt,
	)
	var i RouterSubscriberAllowanceAction
	err := row.Scan(
		&i.ActionID,
		&i.RouterRequestID,
		&i.SubscriberID,
		&i.EntitlementVersion,
		&i.Plan,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.SixHourPeriodStart,
		&i.SixHourPeriodEnd,
		&i.APIKeyID,
		&i.ClientSessionID,
		&i.RequestedModel,
		&i.ServedModel,
		&i.ReservedUsdMicros,
		&i.RetailUsdMicros,
		&i.CapacitySource,
		&i.State,
		&i.ReservedAt,
		&i.FinalizedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeeklyPeriodStart,
		&i.WeeklyPeriodEnd,
	)
	return i, err
}

const listSubscriberAllowanceWindows = `-- name: ListSubscriberAllowanceWindows :many
SELECT subscriber_id, period_kind, period_start, period_end, entitlement_version, plan, limit_usd_micros, reserved_usd_micros, finalized_usd_micros, created_at, updated_at
FROM router.subscriber_allowance_periods
WHERE subscriber_id = $1::uuid
  AND (
      (period_kind = 'billing' AND period_start = $2::timestamptz)
      OR (period_kind = 'weekly' AND period_start = $3::timestamptz)
      OR (period_kind = 'six_hour' AND period_start = $4::timestamptz)
  )
`

type ListSubscriberAllowanceWindowsParams struct {
	SubscriberID       uuid.UUID
	BillingPeriodStart pgtype.Timestamptz
	WeeklyPeriodStart  pgtype.Timestamptz
	SixHourPeriodStart pgtype.Timestamptz
}

// Reads the consumed amounts for the enforcement windows covering one
// request. A window with no activity yet has no row.
//
//	SELECT subscriber_id, period_kind, period_start, period_end, entitlement_version, plan, limit_usd_micros, reserved_usd_micros, finalized_usd_micros, created_at, updated_at
//	FROM router.subscriber_allowance_periods
//	WHERE subscriber_id = $1::uuid
//	  AND (
//	      (period_kind = 'billing' AND period_start = $2::timestamptz)
//	      OR (period_kind = 'weekly' AND period_start = $3::timestamptz)
//	      OR (period_kind = 'six_hour' AND period_start = $4::timestamptz)
//	  )
func (q *Queries) ListSubscriberAllowanceWindows(ctx context.Context, arg ListSubscriberAllowanceWindowsParams) ([]RouterSubscriberAllowancePeriod, error) {
	rows, err := q.db.Query(ctx, listSubscriberAllowanceWindows,
		arg.SubscriberID,
		arg.BillingPeriodStart,
		arg.WeeklyPeriodStart,
		arg.SixHourPeriodStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterSubscriberAllowancePeriod
	for rows.Next() {
		var i RouterSubscriberAllowancePeriod
		if err := rows.Scan(
			&i.SubscriberID,
			&i.PeriodKind,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.EntitlementVersion,
			&i.Plan,
			&i.LimitUsdMicros,
			&i.ReservedUsdMicros,
			&i.FinalizedUsdMicros,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSubscriberAllowance = `-- name: ReleaseSubscriberAllowance :one
WITH released AS (
    UPDATE router.subscriber_allowance_actions
    SET state = 'released',
        released_at = $1::timestamptz,
        updated_at = CURRENT_TIMESTAMP
    WHERE action_id = $2::varchar
      AND state = 'reserved'
    RETURNING action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end
), billing_window AS (
    UPDATE router.subscriber_allowance_periods
    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - released.reserved_usd_micros, 0),
        updated_at = CURRENT_TIMESTAMP
    FROM released
    WHERE router.subscriber_allowance_periods.subscriber_id = released.subscriber_id
      AND router.subscriber_allowance_periods.period_kind = 'billing'
      AND router.subscriber_allowance_periods.period_start = released.billing_period_start
      AND released.capacity_source = 'included_router'
), weekly_window AS (
    UPDATE router.subscriber_allowance_periods
    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - released.reserved_usd_micros, 0),
        updated_at = CURRENT_TIMESTAMP
    FROM released
    WHERE router.subscriber_allowance_periods.subscriber_id = released.subscriber_id
      AND router.subscriber_allowance_periods.period_kind = 'weekly'
      AND router.subscriber_allowance_periods.period_start = released.weekly_period_start
      AND released.capacity_source = 'included_router'
), six_hour_window AS (
    UPDATE router.subscriber_allowance_periods
    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - released.reserved_usd_micros, 0),
        updated_at = CURRENT_TIMESTAMP
    FROM released
    WHERE router.subscriber_allowance_periods.subscriber_id = released.subscriber_id
      AND router.subscriber_allowance_periods.period_kind = 'six_hour'
      AND router.subscriber_allowance_periods.period_start = released.six_hour_period_start
      AND released.capacity_source = 'included_router'
)
SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM released
UNION ALL
SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM router.subscriber_allowance_actions
WHERE action_id = $2::varchar
  AND NOT EXISTS (SELECT 1 FROM released)
`

type ReleaseSubscriberAllowanceParams struct {
	ReleasedAt pgtype.Timestamptz
	ActionID   string
}

type ReleaseSubscriberAllowanceRow struct {
	ActionID           string
	RouterRequestID    string
	SubscriberID       uuid.UUID
	EntitlementVersion int64
	Plan               string
	BillingPeriodStart pgtype.Timestamptz
	BillingPeriodEnd   pgtype.Timestamptz
	SixHourPeriodStart pgtype.Timestamptz
	SixHourPeriodEnd   pgtype.Timestamptz
	APIKeyID           uuid.UUID
	ClientSessionID    *string
	RequestedModel     string
	ServedModel        *string
	ReservedUsdMicros  int64
	RetailUsdMicros    *int64
	CapacitySource     string
	State              string
	ReservedAt         pgtype.Timestamptz
	FinalizedAt        pgtype.Timestamptz
	ReleasedAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	WeeklyPeriodStart  pgtype.Timestamptz
	WeeklyPeriodEnd    pgtype.Timestamptz
}

// Returns a non-billable hold to every window. A redelivered release returns
// the stored action unchanged.
//
//	WITH released AS (
//	    UPDATE router.subscriber_allowance_actions
//	    SET state = 'released',
//	        released_at = $1::timestamptz,
//	        updated_at = CURRENT_TIMESTAMP
//	    WHERE action_id = $2::varchar
//	      AND state = 'reserved'
//	    RETURNING action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end
//	), billing_window AS (
//	    UPDATE router.subscriber_allowance_periods
//	    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - released.reserved_usd_micros, 0),
//	        updated_at = CURRENT_TIMESTAMP
//	    FROM released
//	    WHERE router.subscriber_allowance_periods.subscriber_id = released.subscriber_id
//	      AND router.subscriber_allowance_periods.period_kind = 'billing'
//	      AND router.subscriber_allowance_periods.period_start = released.billing_period_start
//	      AND released.capacity_source = 'included_router'
//	), weekly_window AS (
//	    UPDATE router.subscriber_allowance_periods
//	    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - released.reserved_usd_micros, 0),
//	        updated_at = CURRENT_TIMESTAMP
//	    FROM released
//	    WHERE router.subscriber_allowance_periods.subscriber_id = released.subscriber_id
//	      AND router.subscriber_allowance_periods.period_kind = 'weekly'
//	      AND router.subscriber_allowance_periods.period_start = released.weekly_period_start
//	      AND released.capacity_source = 'included_router'
//	), six_hour_window AS (
//	    UPDATE router.subscriber_allowance_periods
//	    SET reserved_usd_micros = GREATEST(router.subscriber_allowance_periods.reserved_usd_micros - released.reserved_usd_micros, 0),
//	        updated_at = CURRENT_TIMESTAMP
//	    FROM released
//	    WHERE router.subscriber_allowance_periods.subscriber_id = released.subscriber_id
//	      AND router.subscriber_allowance_periods.period_kind = 'six_hour'
//	      AND router.subscriber_allowance_periods.period_start = released.six_hour_period_start
//	      AND released.capacity_source = 'included_router'
//	)
//	SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM released
//	UNION ALL
//	SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM router.subscriber_allowance_actions
//	WHERE action_id = $2::varchar
//	  AND NOT EXISTS (SELECT 1 FROM released)
func (q *Queries) ReleaseSubscriberAllowance(ctx context.Context, arg ReleaseSubscriberAllowanceParams) (ReleaseSubscriberAllowanceRow, error) {
	row := q.db.QueryRow(ctx, releaseSubscriberAllowance, arg.ReleasedAt, arg.ActionID)
	var i ReleaseSubscriberAllowanceRow
	err := row.Scan(
		&i.ActionID,
		&i.RouterRequestID,
		&i.SubscriberID,
		&i.EntitlementVersion,
		&i.Plan,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.SixHourPeriodStart,
		&i.SixHourPeriodEnd,
		&i.APIKeyID,
		&i.ClientSessionID,
		&i.RequestedModel,
		&i.ServedModel,
		&i.ReservedUsdMicros,
		&i.RetailUsdMicros,
		&i.CapacitySource,
		&i.State,
		&i.ReservedAt,
		&i.FinalizedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeeklyPeriodStart,
		&i.WeeklyPeriodEnd,
	)
	return i, err
}

const reserveSubscriberAllowance = `-- name: ReserveSubscriberAllowance :one
WITH reserved AS (
    INSERT INTO router.subscriber_allowance_actions (
        action_id,
        router_request_id,
        subscriber_id,
        entitlement_version,
        plan,
        billing_period_start,
        billing_period_end,
        weekly_period_start,
        weekly_period_end,
        six_hour_period_start,
        six_hour_period_end,
        api_key_id,
        client_session_id,
        requested_model,
        reserved_usd_micros,
        capacity_source,
        state,
        reserved_at
    ) VALUES (
        $1::varchar,
        $2::varchar,
        $3::uuid,
        $4::bigint,
        $5::varchar,
        $6::timestamptz,
        $7::timestamptz,
        $8::timestamptz,
        $9::timestamptz,
        $10::timestamptz,
        $11::timestamptz,
        $12::uuid,
        $13::varchar,
        $14::varchar,
        $15::bigint,
        $16::varchar,
        'reserved',
        $17::timestamptz
    )
    ON CONFLICT (action_id) DO NOTHING
    RETURNING action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end
), billing_window AS (
    INSERT INTO router.subscriber_allowance_periods (
        subscriber_id,
        period_kind,
        period_start,
        period_end,
        entitlement_version,
        plan,
        limit_usd_micros,
        reserved_usd_micros
    )
    SELECT
        reserved.subscriber_id,
        'billing',
        reserved.billing_period_start,
        reserved.billing_period_end,
        reserved.entitlement_version,
        reserved.plan,
        $18::bigint,
        reserved.reserved_usd_micros
    FROM reserved
    WHERE reserved.capacity_source = 'included_router'
    ON CONFLICT (subscriber_id, period_kind, period_start) DO UPDATE SET
        period_end = CASE
            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.period_end
            ELSE router.subscriber_allowance_periods.period_end
        END,
        entitlement_version = GREATEST(router.subscriber_allowance_periods.entitlement_version, EXCLUDED.entitlement_version),
        plan = CASE
            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.plan
            ELSE router.subscriber_allowance_periods.plan
        END,
        limit_usd_micros = CASE
            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.limit_usd_micros
            ELSE router.subscriber_allowance_periods.limit_usd_micros
        END,
        reserved_usd_micros = router.subscriber_allowance_periods.reserved_usd_micros + EXCLUDED.reserved_usd_micros,
        updated_at = CURRENT_TIMESTAMP
), weekly_window AS (
    INSERT INTO router.subscriber_allowance_periods (
        subscriber_id,
        period_kind,
        period_start,
        period_end,
        entitlement_version,
        plan,
        limit_usd_micros,
        reserved_usd_micros
    )
    SELECT
        reserved.subscriber_id,
        'weekly',
        reserved.weekly_period_start,
        reserved.weekly_period_end,
        reserved.entitlement_version,
        reserved.plan,
        $19::bigint,
        reserved.reserved_usd_micros
    FROM reserved
    WHERE reserved.capacity_source = 'included_router'
    ON CONFLICT (subscriber_id, period_kind, period_start) DO UPDATE SET
        period_end = CASE
            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.period_end
            ELSE router.subscriber_allowance_periods.period_end
        END,
        entitlement_version = GREATEST(router.subscriber_allowance_periods.entitlement_version, EXCLUDED.entitlement_version),
        plan = CASE
            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.plan
            ELSE router.subscriber_allowance_periods.plan
        END,
        limit_usd_micros = CASE
            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.limit_usd_micros
            ELSE router.subscriber_allowance_periods.limit_usd_micros
        END,
        reserved_usd_micros = router.subscriber_allowance_periods.reserved_usd_micros + EXCLUDED.reserved_usd_micros,
        updated_at = CURRENT_TIMESTAMP
), six_hour_window AS (
    INSERT INTO router.subscriber_allowance_periods (
        subscriber_id,
        period_kind,
        period_start,
        period_end,
        entitlement_version,
        plan,
        limit_usd_micros,
        reserved_usd_micros
    )
    SELECT
        reserved.subscriber_id,
        'six_hour',
        reserved.six_hour_period_start,
        reserved.six_hour_period_end,
        reserved.entitlement_version,
        reserved.plan,
        $20::bigint,
        reserved.reserved_usd_micros
    FROM reserved
    WHERE reserved.capacity_source = 'included_router'
    ON CONFLICT (subscriber_id, period_kind, period_start) DO UPDATE SET
        period_end = CASE
            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.period_end
            ELSE router.subscriber_allowance_periods.period_end
        END,
        entitlement_version = GREATEST(router.subscriber_allowance_periods.entitlement_version, EXCLUDED.entitlement_version),
        plan = CASE
            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.plan
            ELSE router.subscriber_allowance_periods.plan
        END,
        limit_usd_micros = CASE
            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.limit_usd_micros
            ELSE router.subscriber_allowance_periods.limit_usd_micros
        END,
        reserved_usd_micros = router.subscriber_allowance_periods.reserved_usd_micros + EXCLUDED.reserved_usd_micros,
        updated_at = CURRENT_TIMESTAMP
)
SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM reserved
UNION ALL
SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM router.subscriber_allowance_actions
WHERE action_id = $1::varchar
  AND NOT EXISTS (SELECT 1 FROM reserved)
`

type ReserveSubscriberAllowanceParams struct {
	ActionID              string
	RouterRequestID       string
	SubscriberID          uuid.UUID
	EntitlementVersion    int64
	Plan                  string
	BillingPeriodStart    pgtype.Timestamptz
	BillingPeriodEnd      pgtype.Timestamptz
	WeeklyPeriodStart     pgtype.Timestamptz
	WeeklyPeriodEnd       pgtype.Timestamptz
	SixHourPeriodStart    pgtype.Timestamptz
	SixHourPeriodEnd      pgtype.Timestamptz
	APIKeyID              uuid.UUID
	ClientSessionID       *string
	RequestedModel        string
	ReservedUsdMicros     int64
	CapacitySource        string
	ReservedAt            pgtype.Timestamptz
	BillingLimitUsdMicros int64
	WeeklyLimitUsdMicros  int64
	SixHourLimitUsdMicros int64
}

type ReserveSubscriberAllowanceRow struct {
	ActionID           string
	RouterRequestID    string
	SubscriberID       uuid.UUID
	EntitlementVersion int64
	Plan               string
	BillingPeriodStart pgtype.Timestamptz
	BillingPeriodEnd   pgtype.Timestamptz
	SixHourPeriodStart pgtype.Timestamptz
	SixHourPeriodEnd   pgtype.Timestamptz
	APIKeyID           uuid.UUID
	ClientSessionID    *string
	RequestedModel     string
	ServedModel        *string
	ReservedUsdMicros  int64
	RetailUsdMicros    *int64
	CapacitySource     string
	State              string
	ReservedAt         pgtype.Timestamptz
	FinalizedAt        pgtype.Timestamptz
	ReleasedAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	WeeklyPeriodStart  pgtype.Timestamptz
	WeeklyPeriodEnd    pgtype.Timestamptz
}

// Records an allowance hold for one action and accrues it against the
// subscriber's billing, weekly, and six-hour windows. A redelivered action_id returns
// the stored action without accruing a second hold. Only included-Router
// capacity draws down the windows; a turn served on a linked or prepaid source
// is audited without consuming the subscription allowance.
//
//	WITH reserved AS (
//	    INSERT INTO router.subscriber_allowance_actions (
//	        action_id,
//	        router_request_id,
//	        subscriber_id,
//	        entitlement_version,
//	        plan,
//	        billing_period_start,
//	        billing_period_end,
//	        weekly_period_start,
//	        weekly_period_end,
//	        six_hour_period_start,
//	        six_hour_period_end,
//	        api_key_id,
//	        client_session_id,
//	        requested_model,
//	        reserved_usd_micros,
//	        capacity_source,
//	        state,
//	        reserved_at
//	    ) VALUES (
//	        $1::varchar,
//	        $2::varchar,
//	        $3::uuid,
//	        $4::bigint,
//	        $5::varchar,
//	        $6::timestamptz,
//	        $7::timestamptz,
//	        $8::timestamptz,
//	        $9::timestamptz,
//	        $10::timestamptz,
//	        $11::timestamptz,
//	        $12::uuid,
//	        $13::varchar,
//	        $14::varchar,
//	        $15::bigint,
//	        $16::varchar,
//	        'reserved',
//	        $17::timestamptz
//	    )
//	    ON CONFLICT (action_id) DO NOTHING
//	    RETURNING action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end
//	), billing_window AS (
//	    INSERT INTO router.subscriber_allowance_periods (
//	        subscriber_id,
//	        period_kind,
//	        period_start,
//	        period_end,
//	        entitlement_version,
//	        plan,
//	        limit_usd_micros,
//	        reserved_usd_micros
//	    )
//	    SELECT
//	        reserved.subscriber_id,
//	        'billing',
//	        reserved.billing_period_start,
//	        reserved.billing_period_end,
//	        reserved.entitlement_version,
//	        reserved.plan,
//	        $18::bigint,
//	        reserved.reserved_usd_micros
//	    FROM reserved
//	    WHERE reserved.capacity_source = 'included_router'
//	    ON CONFLICT (subscriber_id, period_kind, period_start) DO UPDATE SET
//	        period_end = CASE
//	            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.period_end
//	            ELSE router.subscriber_allowance_periods.period_end
//	        END,
//	        entitlement_version = GREATEST(router.subscriber_allowance_periods.entitlement_version, EXCLUDED.entitlement_version),
//	        plan = CASE
//	            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.plan
//	            ELSE router.subscriber_allowance_periods.plan
//	        END,
//	        limit_usd_micros = CASE
//	            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.limit_usd_micros
//	            ELSE router.subscriber_allowance_periods.limit_usd_micros
//	        END,
//	        reserved_usd_micros = router.subscriber_allowance_periods.reserved_usd_micros + EXCLUDED.reserved_usd_micros,
//	        updated_at = CURRENT_TIMESTAMP
//	), weekly_window AS (
//	    INSERT INTO router.subscriber_allowance_periods (
//	        subscriber_id,
//	        period_kind,
//	        period_start,
//	        period_end,
//	        entitlement_version,
//	        plan,
//	        limit_usd_micros,
//	        reserved_usd_micros
//	    )
//	    SELECT
//	        reserved.subscriber_id,
//	        'weekly',
//	        reserved.weekly_period_start,
//	        reserved.weekly_period_end,
//	        reserved.entitlement_version,
//	        reserved.plan,
//	        $19::bigint,
//	        reserved.reserved_usd_micros
//	    FROM reserved
//	    WHERE reserved.capacity_source = 'included_router'
//	    ON CONFLICT (subscriber_id, period_kind, period_start) DO UPDATE SET
//	        period_end = CASE
//	            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.period_end
//	            ELSE router.subscriber_allowance_periods.period_end
//	        END,
//	        entitlement_version = GREATEST(router.subscriber_allowance_periods.entitlement_version, EXCLUDED.entitlement_version),
//	        plan = CASE
//	            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.plan
//	            ELSE router.subscriber_allowance_periods.plan
//	        END,
//	        limit_usd_micros = CASE
//	            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.limit_usd_micros
//	            ELSE router.subscriber_allowance_periods.limit_usd_micros
//	        END,
//	        reserved_usd_micros = router.subscriber_allowance_periods.reserved_usd_micros + EXCLUDED.reserved_usd_micros,
//	        updated_at = CURRENT_TIMESTAMP
//	), six_hour_window AS (
//	    INSERT INTO router.subscriber_allowance_periods (
//	        subscriber_id,
//	        period_kind,
//	        period_start,
//	        period_end,
//	        entitlement_version,
//	        plan,
//	        limit_usd_micros,
//	        reserved_usd_micros
//	    )
//	    SELECT
//	        reserved.subscriber_id,
//	        'six_hour',
//	        reserved.six_hour_period_start,
//	        reserved.six_hour_period_end,
//	        reserved.entitlement_version,
//	        reserved.plan,
//	        $20::bigint,
//	        reserved.reserved_usd_micros
//	    FROM reserved
//	    WHERE reserved.capacity_source = 'included_router'
//	    ON CONFLICT (subscriber_id, period_kind, period_start) DO UPDATE SET
//	        period_end = CASE
//	            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.period_end
//	            ELSE router.subscriber_allowance_periods.period_end
//	        END,
//	        entitlement_version = GREATEST(router.subscriber_allowance_periods.entitlement_version, EXCLUDED.entitlement_version),
//	        plan = CASE
//	            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.plan
//	            ELSE router.subscriber_allowance_periods.plan
//	        END,
//	        limit_usd_micros = CASE
//	            WHEN EXCLUDED.entitlement_version >= router.subscriber_allowance_periods.entitlement_version THEN EXCLUDED.limit_usd_micros
//	            ELSE router.subscriber_allowance_periods.limit_usd_micros
//	        END,
//	        reserved_usd_micros = router.subscriber_allowance_periods.reserved_usd_micros + EXCLUDED.reserved_usd_micros,
//	        updated_at = CURRENT_TIMESTAMP
//	)
//	SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM reserved
//	UNION ALL
//	SELECT action_id, router_request_id, subscriber_id, entitlement_version, plan, billing_period_start, billing_period_end, six_hour_period_start, six_hour_period_end, api_key_id, client_session_id, requested_model, served_model, reserved_usd_micros, retail_usd_micros, capacity_source, state, reserved_at, finalized_at, released_at, created_at, updated_at, weekly_period_start, weekly_period_end FROM router.subscriber_allowance_actions
//	WHERE action_id = $1::varchar
//	  AND NOT EXISTS (SELECT 1 FROM reserved)
func (q *Queries) ReserveSubscriberAllowance(ctx context.Context, arg ReserveSubscriberAllowanceParams) (ReserveSubscriberAllowanceRow, error) {
	row := q.db.QueryRow(ctx, reserveSubscriberAllowance,
		arg.ActionID,
		arg.RouterRequestID,
		arg.SubscriberID,
		arg.EntitlementVersion,
		arg.Plan,
		arg.BillingPeriodStart,
		arg.BillingPeriodEnd,
		arg.WeeklyPeriodStart,
		arg.WeeklyPeriodEnd,
		arg.SixHourPeriodStart,
		arg.SixHourPeriodEnd,
		arg.APIKeyID,
		arg.ClientSessionID,
		arg.RequestedModel,
		arg.ReservedUsdMicros,
		arg.CapacitySource,
		arg.ReservedAt,
		arg.BillingLimitUsdMicros,
		arg.WeeklyLimitUsdMicros,
		arg.SixHourLimitUsdMicros,
	)
	var i ReserveSubscriberAllowanceRow
	err := row.Scan(
		&i.ActionID,
		&i.RouterRequestID,
		&i.SubscriberID,
		&i.EntitlementVersion,
		&i.Plan,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.SixHourPeriodStart,
		&i.SixHourPeriodEnd,
		&i.APIKeyID,
		&i.ClientSessionID,
		&i.RequestedModel,
		&i.ServedModel,
		&i.ReservedUsdMicros,
		&i.RetailUsdMicros,
		&i.CapacitySource,
		&i.State,
		&i.ReservedAt,
		&i.FinalizedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeeklyPeriodStart,
		&i.WeeklyPeriodEnd,
	)
	return i, err
}
