// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_cluster_model_lists.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserClusterModelListsByUser = `-- name: GetUserClusterModelListsByUser :many
SELECT router_user_id, cluster_label, organization_id, models, created_by, created_at, updated_at
FROM router.model_router_user_cluster_model_lists
WHERE router_user_id = $1::uuid
ORDER BY cluster_label
`

// Returns every configured per-cluster model selection for one router user.
// Writes are owned by the Weave control plane (direct inserts to this schema,
// mirroring cluster_model_lists); the router only reads on the auth path.
//
//	SELECT router_user_id, cluster_label, organization_id, models, created_by, created_at, updated_at
//	FROM router.model_router_user_cluster_model_lists
//	WHERE router_user_id = $1::uuid
//	ORDER BY cluster_label
func (q *Queries) GetUserClusterModelListsByUser(ctx context.Context, routerUserID uuid.UUID) ([]RouterModelRouterUserClusterModelList, error) {
	rows, err := q.db.Query(ctx, getUserClusterModelListsByUser, routerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterUserClusterModelList
	for rows.Next() {
		var i RouterModelRouterUserClusterModelList
		if err := rows.Scan(
			&i.RouterUserID,
			&i.ClusterLabel,
			&i.OrganizationID,
			&i.Models,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
