package policy

import (
	"encoding/json"
	"fmt"
	"strings"
)

// StaticRegistryProjection is the safe, content-free review projection of the registry.
type StaticRegistryProjection struct {
	SchemaVersion    string       `json:"schema_version"`
	RegistryRevision string       `json:"registry_revision"`
	Policies         []PolicySpec `json:"policies"`
}

// StaticProjection returns the safe static view used by generated docs and future inspection APIs.
func (r Registry) StaticProjection() StaticRegistryProjection {
	return StaticRegistryProjection{
		SchemaVersion:    InferenceRegistrySchemaVersion,
		RegistryRevision: r.Revision(),
		Policies:         r.Specs(),
	}
}

// StaticJSON renders the deterministic JSON registry projection.
func (r Registry) StaticJSON() ([]byte, error) {
	payload, err := json.MarshalIndent(r.StaticProjection(), "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal static inference policy projection: %w", err)
	}
	return append(payload, '\n'), nil
}

// StaticMarkdown renders the deterministic human-readable registry projection.
func (r Registry) StaticMarkdown() []byte {
	var output strings.Builder
	output.WriteString("<!-- Code generated by go run ./cmd/geninferencepolicy; DO NOT EDIT. -->\n\n")
	output.WriteString("# Router Inference Policy Registry\n\n")
	fmt.Fprintf(&output, "- Schema version: `%s`\n", InferenceRegistrySchemaVersion)
	fmt.Fprintf(&output, "- Registry revision: `%s`\n\n", r.Revision())
	output.WriteString("This static projection contains no tenant credentials, installation overrides, request content, or private gateway details. Migration status describes the current execution boundary; `legacy_direct` entries are inventory, not authorization for new call sites.\n\n")
	output.WriteString("| Purpose | Class | Policy | Selection | Candidates | Constraints | Preferences | Fallback | Budget | Status | Owner | Rationale |\n")
	output.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, spec := range r.Specs() {
		fmt.Fprintf(
			&output,
			"| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n",
			markdownCode(string(spec.Purpose)),
			markdownCode(string(spec.DispatchClass)),
			markdownCode(string(spec.PolicyID)+"@"+string(spec.PolicyRevision)),
			markdownCode(string(spec.SelectionStrategy)),
			markdownCodeList(spec.FixedCatalogModels, string(spec.CandidateSource)),
			markdownConstraintList(spec.HardConstraints),
			markdownPreferenceList(spec.SoftPreferences),
			markdownFallback(spec.Fallback),
			markdownBudget(spec.Budget),
			markdownCode(string(spec.MigrationStatus)),
			markdownCode(spec.Owner),
			escapeMarkdownTable(spec.Rationale),
		)
	}
	return []byte(output.String())
}

func markdownCode(value string) string {
	return "`" + escapeMarkdownTable(value) + "`"
}

func markdownCodeList(values []string, empty string) string {
	if len(values) == 0 {
		return markdownCode(empty)
	}
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = markdownCode(value)
	}
	return strings.Join(quoted, "<br>")
}

func markdownConstraintList(values []Constraint) string {
	if len(values) == 0 {
		return "—"
	}
	labels := make([]string, len(values))
	for i, value := range values {
		labels[i] = string(value)
	}
	return markdownCodeList(labels, "")
}

func markdownPreferenceList(values []SoftPreference) string {
	if len(values) == 0 {
		return "—"
	}
	labels := make([]string, len(values))
	for i, value := range values {
		labels[i] = string(value)
	}
	return markdownCodeList(labels, "")
}

func markdownFallback(fallback FallbackSpec) string {
	if len(fallback.Alternatives) == 0 {
		return markdownCode(string(fallback.Kind))
	}
	return markdownCode(string(fallback.Kind)) + "<br>" + markdownCodeList(fallback.Alternatives, "")
}

func markdownBudget(budget BudgetSpec) string {
	parts := []string{"source=" + string(budget.Source)}
	if budget.MaxAttempts > 0 {
		parts = append(parts, fmt.Sprintf("attempts=%d", budget.MaxAttempts))
	}
	if budget.TimeoutMillis > 0 {
		parts = append(parts, fmt.Sprintf("timeout_ms=%d", budget.TimeoutMillis))
	}
	if budget.MaxOutputTokens > 0 {
		parts = append(parts, fmt.Sprintf("max_output=%d", budget.MaxOutputTokens))
	}
	if budget.MaxSpendUSD > 0 {
		parts = append(parts, fmt.Sprintf("max_spend_usd=%g", budget.MaxSpendUSD))
	}
	return markdownCode(strings.Join(parts, " "))
}

// escapeMarkdownTable keeps arbitrary policy strings inside a single table cell.
func escapeMarkdownTable(value string) string {
	value = strings.ReplaceAll(value, "\r\n", "\n")
	value = strings.ReplaceAll(value, "\r", "\n")
	value = strings.ReplaceAll(value, "\n", " ")
	return strings.ReplaceAll(value, "|", "\\|")
}
